// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package notificationdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claim = `-- name: Claim :many
SELECT id::text AS id, recipient::text AS recipient,
       coalesce(subject, '')::text AS subject, coalesce(body, '')::text AS body,
       attempts
FROM notification.emails
WHERE sent_at IS NULL
  AND dead_at IS NULL
  AND next_attempt_at <= now()
ORDER BY next_attempt_at, id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type ClaimRow struct {
	ID        string
	Recipient string
	Subject   string
	Body      string
	Attempts  int32
}

// FOR UPDATE SKIP LOCKED for the outbox's reason: two senders must not both
// deliver the same email, and a second sender steps over what the first holds
// rather than waiting behind it.
func (q *Queries) Claim(ctx context.Context, limit int32) ([]ClaimRow, error) {
	rows, err := q.db.Query(ctx, claim, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimRow{}
	for rows.Next() {
		var i ClaimRow
		if err := rows.Scan(
			&i.ID,
			&i.Recipient,
			&i.Subject,
			&i.Body,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deliveryStatusByID = `-- name: DeliveryStatusByID :one
SELECT sent_at, bounced_at, complained_at, dead_at, attempts, last_error
FROM notification.emails
WHERE id = $1::uuid
`

type DeliveryStatusByIDRow struct {
	SentAt       *time.Time
	BouncedAt    *time.Time
	ComplainedAt *time.Time
	DeadAt       *time.Time
	Attempts     int32
	LastError    pgtype.Text
}

// The delivery facts about one email, for a context that enqueued it and now
// wants to show whether it arrived. Only the status columns: the body is
// nulled at send and is never anyone else's to read. A caller that holds an
// id from a rolled-back transaction finds no row, which the reader turns into
// an "unknown" rather than a delivered-or-not it cannot honestly answer.
func (q *Queries) DeliveryStatusByID(ctx context.Context, id string) (DeliveryStatusByIDRow, error) {
	row := q.db.QueryRow(ctx, deliveryStatusByID, id)
	var i DeliveryStatusByIDRow
	err := row.Scan(
		&i.SentAt,
		&i.BouncedAt,
		&i.ComplainedAt,
		&i.DeadAt,
		&i.Attempts,
		&i.LastError,
	)
	return i, err
}

const enqueue = `-- name: Enqueue :exec

INSERT INTO notification.emails (id, recipient, template, template_version, subject, body)
VALUES ($1::uuid, $2::citext, $3::text,
        $4::text, $5::text, $6::text)
`

type EnqueueParams struct {
	ID              string
	Recipient       string
	Template        string
	TemplateVersion string
	Subject         string
	Body            string
}

// The email queue's queries. sqlc generates the Go beside this file; ADR-0010
// records why no SQL lives in Go source.
// Runs inside the caller's transaction, which is the guarantee the queue
// exists for: the email and the state change that wants it sent commit
// together or neither does.
func (q *Queries) Enqueue(ctx context.Context, arg EnqueueParams) error {
	_, err := q.db.Exec(ctx, enqueue,
		arg.ID,
		arg.Recipient,
		arg.Template,
		arg.TemplateVersion,
		arg.Subject,
		arg.Body,
	)
	return err
}

const hideClaimed = `-- name: HideClaimed :exec
UPDATE notification.emails
SET next_attempt_at = now() + $1::interval
WHERE id = ANY($2::uuid[])
`

type HideClaimedParams struct {
	Visibility string
	Ids        []string
}

// Marked inside the same transaction that locked the rows, so a sender that
// dies mid-send releases its claim by the visibility window at the latest.
func (q *Queries) HideClaimed(ctx context.Context, arg HideClaimedParams) error {
	_, err := q.db.Exec(ctx, hideClaimed, arg.Visibility, arg.Ids)
	return err
}

const lockAttempts = `-- name: LockAttempts :one
SELECT attempts FROM notification.emails WHERE id = $1::uuid FOR UPDATE
`

// Read here, computed in Go, for the outbox's reason: one backoff formula.
func (q *Queries) LockAttempts(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, lockAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const markSent = `-- name: MarkSent :exec
UPDATE notification.emails
SET sent_at = now(), subject = NULL, body = NULL, last_error = NULL
WHERE id = $1::uuid AND sent_at IS NULL
`

// The body and subject are erased in the same statement that records the
// send. A verification link is a secret, and a sent secret has no reason to
// stay readable at rest.
func (q *Queries) MarkSent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markSent, id)
	return err
}

const recordFailure = `-- name: RecordFailure :exec
UPDATE notification.emails
SET attempts = $1::integer,
    last_error = $2::text,
    next_attempt_at = now() + make_interval(secs => $3::double precision),
    dead_at = $4::timestamptz
WHERE id = $5::uuid
`

type RecordFailureParams struct {
	Attempts       int32
	LastError      string
	BackoffSeconds float64
	DeadAt         *time.Time
	ID             string
}

// After enough failures the caller passes dead_at, because an email nobody
// can deliver is an operational fact somebody needs to see rather than a row
// retried silently forever.
func (q *Queries) RecordFailure(ctx context.Context, arg RecordFailureParams) error {
	_, err := q.db.Exec(ctx, recordFailure,
		arg.Attempts,
		arg.LastError,
		arg.BackoffSeconds,
		arg.DeadAt,
		arg.ID,
	)
	return err
}
