// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package interviewdb

import (
	"context"
	"time"
)

const advanceSessionEpoch = `-- name: AdvanceSessionEpoch :execrows
UPDATE interview.sessions
SET connection_epoch = $1::integer, accepted_sequence = 0
WHERE id = $2::uuid AND connection_epoch < $1::integer
`

type AdvanceSessionEpochParams struct {
	Epoch int32
	ID    string
}

// Monotonic by guard: an epoch can only go up, and the cursor resets with
// it because sequence orders within an epoch.
func (q *Queries) AdvanceSessionEpoch(ctx context.Context, arg AdvanceSessionEpochParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceSessionEpoch, arg.Epoch, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const controlEventExists = `-- name: ControlEventExists :one
SELECT EXISTS (
    SELECT 1 FROM interview.control_events WHERE event_id = $1::uuid
) AS present
`

func (q *Queries) ControlEventExists(ctx context.Context, eventID string) (bool, error) {
	row := q.db.QueryRow(ctx, controlEventExists, eventID)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const currentTimingPolicy = `-- name: CurrentTimingPolicy :one
SELECT version, reconnect_grace_seconds, max_overrun_seconds
FROM interview.timing_policies
ORDER BY version DESC
LIMIT 1
`

type CurrentTimingPolicyRow struct {
	Version               int32
	ReconnectGraceSeconds int32
	MaxOverrunSeconds     int32
}

// The rules in force now: the highest published version. Sessions stamp
// it at start so later policy changes never rewrite a running session.
func (q *Queries) CurrentTimingPolicy(ctx context.Context) (CurrentTimingPolicyRow, error) {
	row := q.db.QueryRow(ctx, currentTimingPolicy)
	var i CurrentTimingPolicyRow
	err := row.Scan(&i.Version, &i.ReconnectGraceSeconds, &i.MaxOverrunSeconds)
	return i, err
}

const getSeal = `-- name: GetSeal :one
SELECT session_id::text AS session_id, sealed_epoch, sealed_sequence,
       gaps, transcript_digest, bundle_digest, media_status, warnings,
       evaluation_input_digest, created_at
FROM interview.seals
WHERE session_id = $1::uuid
`

type GetSealRow struct {
	SessionID             string
	SealedEpoch           int32
	SealedSequence        int32
	Gaps                  []byte
	TranscriptDigest      string
	BundleDigest          string
	MediaStatus           string
	Warnings              []byte
	EvaluationInputDigest string
	CreatedAt             time.Time
}

func (q *Queries) GetSeal(ctx context.Context, sessionID string) (GetSealRow, error) {
	row := q.db.QueryRow(ctx, getSeal, sessionID)
	var i GetSealRow
	err := row.Scan(
		&i.SessionID,
		&i.SealedEpoch,
		&i.SealedSequence,
		&i.Gaps,
		&i.TranscriptDigest,
		&i.BundleDigest,
		&i.MediaStatus,
		&i.Warnings,
		&i.EvaluationInputDigest,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id::text AS id, mode, candidate_id::text AS candidate_id,
       coalesce(tenant_id::text, '')::text AS tenant_id,
       blueprint_id, config, recording_preference, consent_version,
       connection_epoch, accepted_sequence, state, version,
       coalesce(bundle_ref, '')::text AS bundle_ref,
       coalesce(bundle_digest, '')::text AS bundle_digest,
       coalesce(bundle_revision, 0)::integer AS bundle_revision,
       coalesce(failure_code, '')::text AS failure_code,
       coalesce(timing_policy_version, 0)::integer AS timing_policy_version,
       created_at, state_changed_at
FROM interview.sessions
WHERE id = $1::uuid
`

type GetSessionRow struct {
	ID                  string
	Mode                string
	CandidateID         string
	TenantID            string
	BlueprintID         string
	Config              []byte
	RecordingPreference string
	ConsentVersion      string
	ConnectionEpoch     int32
	AcceptedSequence    int32
	State               string
	Version             int32
	BundleRef           string
	BundleDigest        string
	BundleRevision      int32
	FailureCode         string
	TimingPolicyVersion int32
	CreatedAt           time.Time
	StateChangedAt      time.Time
}

func (q *Queries) GetSession(ctx context.Context, id string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.CandidateID,
		&i.TenantID,
		&i.BlueprintID,
		&i.Config,
		&i.RecordingPreference,
		&i.ConsentVersion,
		&i.ConnectionEpoch,
		&i.AcceptedSequence,
		&i.State,
		&i.Version,
		&i.BundleRef,
		&i.BundleDigest,
		&i.BundleRevision,
		&i.FailureCode,
		&i.TimingPolicyVersion,
		&i.CreatedAt,
		&i.StateChangedAt,
	)
	return i, err
}

const getSessionBundle = `-- name: GetSessionBundle :one
SELECT session_id::text AS session_id, digest, body, created_at
FROM interview.session_bundles
WHERE session_id = $1::uuid
`

type GetSessionBundleRow struct {
	SessionID string
	Digest    string
	Body      []byte
	CreatedAt time.Time
}

// What review, replay and audit reconstruct a session's configuration from.
func (q *Queries) GetSessionBundle(ctx context.Context, sessionID string) (GetSessionBundleRow, error) {
	row := q.db.QueryRow(ctx, getSessionBundle, sessionID)
	var i GetSessionBundleRow
	err := row.Scan(
		&i.SessionID,
		&i.Digest,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :exec
INSERT INTO interview.attempts
    (id, session_id, mode, candidate_id, tenant_id, connection_epoch)
VALUES ($1::uuid, $2::uuid, $3::text,
        $4::uuid, nullif($5::text, '')::uuid,
        $6::integer)
`

type InsertAttemptParams struct {
	ID              string
	SessionID       string
	Mode            string
	CandidateID     string
	TenantID        string
	ConnectionEpoch int32
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) error {
	_, err := q.db.Exec(ctx, insertAttempt,
		arg.ID,
		arg.SessionID,
		arg.Mode,
		arg.CandidateID,
		arg.TenantID,
		arg.ConnectionEpoch,
	)
	return err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit.events
    (id, tenant_id, actor_id, actor_type, action, subject_type, subject_id, outcome)
VALUES ($1::uuid, nullif($2::text, '')::uuid,
        $3::uuid, $4::text, $5::text,
        'session', $6::text, $7::text)
`

type InsertAuditEventParams struct {
	ID        string
	TenantID  string
	ActorID   string
	ActorType string
	Action    string
	SessionID string
	Outcome   string
}

// Interview's own audit append, inside the transition's transaction. tenant_id
// is NULL for practice transitions, where the untenanted-write policy binds
// the row to the acting user.
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.TenantID,
		arg.ActorID,
		arg.ActorType,
		arg.Action,
		arg.SessionID,
		arg.Outcome,
	)
	return err
}

const insertControlEvent = `-- name: InsertControlEvent :exec
INSERT INTO interview.control_events
    (event_id, session_id, mode, candidate_id, tenant_id,
     connection_epoch, sequence, event_type, payload, occurred_at)
VALUES ($1::uuid, $2::uuid, $3::text,
        $4::uuid, nullif($5::text, '')::uuid,
        $6::integer, $7::integer,
        $8::text, $9::jsonb, $10::timestamptz)
`

type InsertControlEventParams struct {
	EventID         string
	SessionID       string
	Mode            string
	CandidateID     string
	TenantID        string
	ConnectionEpoch int32
	Sequence        int32
	EventType       string
	Payload         []byte
	OccurredAt      time.Time
}

func (q *Queries) InsertControlEvent(ctx context.Context, arg InsertControlEventParams) error {
	_, err := q.db.Exec(ctx, insertControlEvent,
		arg.EventID,
		arg.SessionID,
		arg.Mode,
		arg.CandidateID,
		arg.TenantID,
		arg.ConnectionEpoch,
		arg.Sequence,
		arg.EventType,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const insertMediaTrack = `-- name: InsertMediaTrack :execrows
INSERT INTO interview.media_tracks
    (id, session_id, mode, candidate_id, tenant_id, track, storage_key, egress_id)
VALUES ($1::uuid, $2::uuid, $3::text,
        $4::uuid, nullif($5::text, '')::uuid,
        $6::text, $7::text, $8::text)
ON CONFLICT (session_id, track) DO NOTHING
`

type InsertMediaTrackParams struct {
	ID          string
	SessionID   string
	Mode        string
	CandidateID string
	TenantID    string
	Track       string
	StorageKey  string
	EgressID    string
}

// Idempotent per (session, track): a reconnection retrying the start must
// converge on the one egress already running, never begin a second.
func (q *Queries) InsertMediaTrack(ctx context.Context, arg InsertMediaTrackParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMediaTrack,
		arg.ID,
		arg.SessionID,
		arg.Mode,
		arg.CandidateID,
		arg.TenantID,
		arg.Track,
		arg.StorageKey,
		arg.EgressID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRedo = `-- name: InsertRedo :exec
INSERT INTO interview.redos (parent_session_id, sequence, redo_session_id, mode, candidate_id)
VALUES ($1::uuid, $2::integer,
        $3::uuid, 'practice', $4::uuid)
`

type InsertRedoParams struct {
	ParentSessionID string
	Sequence        int32
	RedoSessionID   string
	CandidateID     string
}

func (q *Queries) InsertRedo(ctx context.Context, arg InsertRedoParams) error {
	_, err := q.db.Exec(ctx, insertRedo,
		arg.ParentSessionID,
		arg.Sequence,
		arg.RedoSessionID,
		arg.CandidateID,
	)
	return err
}

const insertSeal = `-- name: InsertSeal :exec

INSERT INTO interview.seals
    (session_id, mode, candidate_id, tenant_id, sealed_epoch, sealed_sequence,
     gaps, transcript_digest, bundle_digest, media_status, warnings,
     evaluation_input_digest)
VALUES ($1::uuid, $2::text, $3::uuid,
        nullif($4::text, '')::uuid,
        $5::integer, $6::integer,
        $7::jsonb, $8::text,
        $9::text, $10::text,
        $11::jsonb, $12::text)
`

type InsertSealParams struct {
	SessionID             string
	Mode                  string
	CandidateID           string
	TenantID              string
	SealedEpoch           int32
	SealedSequence        int32
	Gaps                  []byte
	TranscriptDigest      string
	BundleDigest          string
	MediaStatus           string
	Warnings              []byte
	EvaluationInputDigest string
}

// ── SES-04: the seal.
func (q *Queries) InsertSeal(ctx context.Context, arg InsertSealParams) error {
	_, err := q.db.Exec(ctx, insertSeal,
		arg.SessionID,
		arg.Mode,
		arg.CandidateID,
		arg.TenantID,
		arg.SealedEpoch,
		arg.SealedSequence,
		arg.Gaps,
		arg.TranscriptDigest,
		arg.BundleDigest,
		arg.MediaStatus,
		arg.Warnings,
		arg.EvaluationInputDigest,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec

INSERT INTO interview.sessions (id, mode, candidate_id, tenant_id, blueprint_id, config,
                                recording_preference, consent_version)
VALUES ($1::uuid, $2::text, $3::uuid,
        nullif($4::text, '')::uuid, $5::text,
        $6::jsonb,
        $7::text, $8::text)
`

type InsertSessionParams struct {
	ID                  string
	Mode                string
	CandidateID         string
	TenantID            string
	BlueprintID         string
	Config              []byte
	RecordingPreference string
	ConsentVersion      string
}

// The session store's queries. sqlc generates the Go beside this file;
// ADR-0010 records why no SQL lives in Go source.
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.Mode,
		arg.CandidateID,
		arg.TenantID,
		arg.BlueprintID,
		arg.Config,
		arg.RecordingPreference,
		arg.ConsentVersion,
	)
	return err
}

const insertSessionBundle = `-- name: InsertSessionBundle :exec
INSERT INTO interview.session_bundles (session_id, digest, body)
VALUES ($1::uuid, $2::text, $3::jsonb)
`

type InsertSessionBundleParams struct {
	SessionID string
	Digest    string
	Body      []byte
}

// Written in the ready transition's transaction: a session marked ready
// whose bundle failed to persist would pin a digest nothing can resolve.
func (q *Queries) InsertSessionBundle(ctx context.Context, arg InsertSessionBundleParams) error {
	_, err := q.db.Exec(ctx, insertSessionBundle, arg.SessionID, arg.Digest, arg.Body)
	return err
}

const listMediaTracks = `-- name: ListMediaTracks :many
SELECT id::text AS id, track, storage_key, egress_id, state, digest,
       size_bytes, created_at, resolved_at
FROM interview.media_tracks
WHERE session_id = $1::uuid
ORDER BY track
`

type ListMediaTracksRow struct {
	ID         string
	Track      string
	StorageKey string
	EgressID   string
	State      string
	Digest     string
	SizeBytes  int64
	CreatedAt  time.Time
	ResolvedAt *time.Time
}

func (q *Queries) ListMediaTracks(ctx context.Context, sessionID string) ([]ListMediaTracksRow, error) {
	rows, err := q.db.Query(ctx, listMediaTracks, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaTracksRow{}
	for rows.Next() {
		var i ListMediaTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Track,
			&i.StorageKey,
			&i.EgressID,
			&i.State,
			&i.Digest,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRedos = `-- name: ListRedos :many
SELECT sequence, redo_session_id::text AS redo_session_id, created_at
FROM interview.redos
WHERE parent_session_id = $1::uuid
ORDER BY sequence
`

type ListRedosRow struct {
	Sequence      int32
	RedoSessionID string
	CreatedAt     time.Time
}

func (q *Queries) ListRedos(ctx context.Context, parentSessionID string) ([]ListRedosRow, error) {
	rows, err := q.db.Query(ctx, listRedos, parentSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRedosRow{}
	for rows.Next() {
		var i ListRedosRow
		if err := rows.Scan(&i.Sequence, &i.RedoSessionID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id::text AS id, mode, candidate_id::text AS candidate_id,
       coalesce(tenant_id::text, '')::text AS tenant_id,
       blueprint_id, config, recording_preference, consent_version,
       connection_epoch, accepted_sequence, state, version,
       coalesce(bundle_ref, '')::text AS bundle_ref,
       coalesce(bundle_digest, '')::text AS bundle_digest,
       coalesce(bundle_revision, 0)::integer AS bundle_revision,
       coalesce(failure_code, '')::text AS failure_code,
       coalesce(timing_policy_version, 0)::integer AS timing_policy_version,
       created_at, state_changed_at
FROM interview.sessions
ORDER BY created_at DESC
`

type ListSessionsRow struct {
	ID                  string
	Mode                string
	CandidateID         string
	TenantID            string
	BlueprintID         string
	Config              []byte
	RecordingPreference string
	ConsentVersion      string
	ConnectionEpoch     int32
	AcceptedSequence    int32
	State               string
	Version             int32
	BundleRef           string
	BundleDigest        string
	BundleRevision      int32
	FailureCode         string
	TimingPolicyVersion int32
	CreatedAt           time.Time
	StateChangedAt      time.Time
}

// The owner's history, newest first. RLS scopes the rows; the ORDER is
// the only policy here.
func (q *Queries) ListSessions(ctx context.Context) ([]ListSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsRow{}
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.CandidateID,
			&i.TenantID,
			&i.BlueprintID,
			&i.Config,
			&i.RecordingPreference,
			&i.ConsentVersion,
			&i.ConnectionEpoch,
			&i.AcceptedSequence,
			&i.State,
			&i.Version,
			&i.BundleRef,
			&i.BundleDigest,
			&i.BundleRevision,
			&i.FailureCode,
			&i.TimingPolicyVersion,
			&i.CreatedAt,
			&i.StateChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const persistCursor = `-- name: PersistCursor :execrows
UPDATE interview.sessions
SET accepted_sequence = $1::integer
WHERE id = $2::uuid
  AND connection_epoch = $3::integer
  AND accepted_sequence < $1::integer
`

type PersistCursorParams struct {
	Accepted int32
	ID       string
	Epoch    int32
}

// Guarded by epoch so a cursor from a superseded attempt cannot land after
// a takeover already moved the session on.
func (q *Queries) PersistCursor(ctx context.Context, arg PersistCursorParams) (int64, error) {
	result, err := q.db.Exec(ctx, persistCursor, arg.Accepted, arg.ID, arg.Epoch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replayControlEvents = `-- name: ReplayControlEvents :many
SELECT event_id::text AS event_id, connection_epoch, sequence, event_type,
       payload, occurred_at
FROM interview.control_events
WHERE session_id = $1::uuid
  AND (connection_epoch, sequence) > ($2::integer, $3::integer)
ORDER BY connection_epoch, sequence
`

type ReplayControlEventsParams struct {
	SessionID     string
	AfterEpoch    int32
	AfterSequence int32
}

type ReplayControlEventsRow struct {
	EventID         string
	ConnectionEpoch int32
	Sequence        int32
	EventType       string
	Payload         []byte
	OccurredAt      time.Time
}

// The replay read: everything after the cursor, in the one authoritative
// order. Replaying twice from the same cursor answers identically, which
// is the property the client rebuilds itself on.
func (q *Queries) ReplayControlEvents(ctx context.Context, arg ReplayControlEventsParams) ([]ReplayControlEventsRow, error) {
	rows, err := q.db.Query(ctx, replayControlEvents, arg.SessionID, arg.AfterEpoch, arg.AfterSequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReplayControlEventsRow{}
	for rows.Next() {
		var i ReplayControlEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.ConnectionEpoch,
			&i.Sequence,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveMediaTrack = `-- name: ResolveMediaTrack :execrows
UPDATE interview.media_tracks
SET state = $1::text,
    digest = $2::text,
    size_bytes = $3::bigint,
    resolved_at = now()
WHERE session_id = $4::uuid
  AND track = $5::text
  AND state = 'recording'
`

type ResolveMediaTrackParams struct {
	State     string
	Digest    string
	SizeBytes int64
	SessionID string
	Track     string
}

// One-way: only a recording row resolves, to finalized or missing, once.
func (q *Queries) ResolveMediaTrack(ctx context.Context, arg ResolveMediaTrackParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveMediaTrack,
		arg.State,
		arg.Digest,
		arg.SizeBytes,
		arg.SessionID,
		arg.Track,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stampTimingPolicy = `-- name: StampTimingPolicy :exec
UPDATE interview.sessions
SET timing_policy_version = $1::integer
WHERE id = $2::uuid AND timing_policy_version IS NULL
`

type StampTimingPolicyParams struct {
	Version int32
	ID      string
}

func (q *Queries) StampTimingPolicy(ctx context.Context, arg StampTimingPolicyParams) error {
	_, err := q.db.Exec(ctx, stampTimingPolicy, arg.Version, arg.ID)
	return err
}

const storedSequences = `-- name: StoredSequences :many
SELECT sequence FROM interview.control_events
WHERE session_id = $1::uuid
  AND connection_epoch = $2::integer
ORDER BY sequence
`

type StoredSequencesParams struct {
	SessionID string
	Epoch     int32
}

// The contiguity computation's input: which slots this epoch holds.
func (q *Queries) StoredSequences(ctx context.Context, arg StoredSequencesParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, storedSequences, arg.SessionID, arg.Epoch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var sequence int32
		if err := rows.Scan(&sequence); err != nil {
			return nil, err
		}
		items = append(items, sequence)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeAttempts = `-- name: SupersedeAttempts :exec

UPDATE interview.attempts SET superseded_at = now()
WHERE session_id = $1::uuid AND superseded_at IS NULL
`

// ── RTC-02: attempts, epochs and the control event log.
func (q *Queries) SupersedeAttempts(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, supersedeAttempts, sessionID)
	return err
}

const transitionSession = `-- name: TransitionSession :execrows
UPDATE interview.sessions
SET state = $1::text,
    version = version + 1,
    state_changed_at = now(),
    bundle_ref = coalesce(nullif($2::text, ''), bundle_ref),
    bundle_digest = coalesce(nullif($3::text, ''), bundle_digest),
    bundle_revision = CASE WHEN $4::integer > 0
                           THEN $4::integer ELSE bundle_revision END,
    failure_code = nullif($5::text, '')
WHERE id = $6::uuid
  AND state = $7::text
  AND version = $8::integer
`

type TransitionSessionParams struct {
	ToState         string
	BundleRef       string
	BundleDigest    string
	BundleRevision  int32
	FailureCode     string
	ID              string
	FromState       string
	ExpectedVersion int32
}

// The guards are the aggregate's whole concurrency story. Zero rows means the
// state or the version the caller read is no longer true, and the caller
// re-reads to say which; the update never overwrites either silently.
func (q *Queries) TransitionSession(ctx context.Context, arg TransitionSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionSession,
		arg.ToState,
		arg.BundleRef,
		arg.BundleDigest,
		arg.BundleRevision,
		arg.FailureCode,
		arg.ID,
		arg.FromState,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
