// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package interviewdb

import (
	"context"
	"time"
)

const getSession = `-- name: GetSession :one
SELECT id::text AS id, mode, candidate_id::text AS candidate_id,
       coalesce(tenant_id::text, '')::text AS tenant_id,
       blueprint_id, config, recording_preference, consent_version, state, version,
       coalesce(bundle_ref, '')::text AS bundle_ref,
       coalesce(bundle_digest, '')::text AS bundle_digest,
       coalesce(bundle_revision, 0)::integer AS bundle_revision,
       coalesce(failure_code, '')::text AS failure_code,
       created_at, state_changed_at
FROM interview.sessions
WHERE id = $1::uuid
`

type GetSessionRow struct {
	ID                  string
	Mode                string
	CandidateID         string
	TenantID            string
	BlueprintID         string
	Config              []byte
	RecordingPreference string
	ConsentVersion      string
	State               string
	Version             int32
	BundleRef           string
	BundleDigest        string
	BundleRevision      int32
	FailureCode         string
	CreatedAt           time.Time
	StateChangedAt      time.Time
}

func (q *Queries) GetSession(ctx context.Context, id string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.CandidateID,
		&i.TenantID,
		&i.BlueprintID,
		&i.Config,
		&i.RecordingPreference,
		&i.ConsentVersion,
		&i.State,
		&i.Version,
		&i.BundleRef,
		&i.BundleDigest,
		&i.BundleRevision,
		&i.FailureCode,
		&i.CreatedAt,
		&i.StateChangedAt,
	)
	return i, err
}

const getSessionBundle = `-- name: GetSessionBundle :one
SELECT session_id::text AS session_id, digest, body, created_at
FROM interview.session_bundles
WHERE session_id = $1::uuid
`

type GetSessionBundleRow struct {
	SessionID string
	Digest    string
	Body      []byte
	CreatedAt time.Time
}

// What review, replay and audit reconstruct a session's configuration from.
func (q *Queries) GetSessionBundle(ctx context.Context, sessionID string) (GetSessionBundleRow, error) {
	row := q.db.QueryRow(ctx, getSessionBundle, sessionID)
	var i GetSessionBundleRow
	err := row.Scan(
		&i.SessionID,
		&i.Digest,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit.events
    (id, tenant_id, actor_id, actor_type, action, subject_type, subject_id, outcome)
VALUES ($1::uuid, nullif($2::text, '')::uuid,
        $3::uuid, $4::text, $5::text,
        'session', $6::text, $7::text)
`

type InsertAuditEventParams struct {
	ID        string
	TenantID  string
	ActorID   string
	ActorType string
	Action    string
	SessionID string
	Outcome   string
}

// Interview's own audit append, inside the transition's transaction. tenant_id
// is NULL for practice transitions, where the untenanted-write policy binds
// the row to the acting user.
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.TenantID,
		arg.ActorID,
		arg.ActorType,
		arg.Action,
		arg.SessionID,
		arg.Outcome,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec

INSERT INTO interview.sessions (id, mode, candidate_id, tenant_id, blueprint_id, config,
                                recording_preference, consent_version)
VALUES ($1::uuid, $2::text, $3::uuid,
        nullif($4::text, '')::uuid, $5::text,
        $6::jsonb,
        $7::text, $8::text)
`

type InsertSessionParams struct {
	ID                  string
	Mode                string
	CandidateID         string
	TenantID            string
	BlueprintID         string
	Config              []byte
	RecordingPreference string
	ConsentVersion      string
}

// The session store's queries. sqlc generates the Go beside this file;
// ADR-0010 records why no SQL lives in Go source.
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.Mode,
		arg.CandidateID,
		arg.TenantID,
		arg.BlueprintID,
		arg.Config,
		arg.RecordingPreference,
		arg.ConsentVersion,
	)
	return err
}

const insertSessionBundle = `-- name: InsertSessionBundle :exec
INSERT INTO interview.session_bundles (session_id, digest, body)
VALUES ($1::uuid, $2::text, $3::jsonb)
`

type InsertSessionBundleParams struct {
	SessionID string
	Digest    string
	Body      []byte
}

// Written in the ready transition's transaction: a session marked ready
// whose bundle failed to persist would pin a digest nothing can resolve.
func (q *Queries) InsertSessionBundle(ctx context.Context, arg InsertSessionBundleParams) error {
	_, err := q.db.Exec(ctx, insertSessionBundle, arg.SessionID, arg.Digest, arg.Body)
	return err
}

const transitionSession = `-- name: TransitionSession :execrows
UPDATE interview.sessions
SET state = $1::text,
    version = version + 1,
    state_changed_at = now(),
    bundle_ref = coalesce(nullif($2::text, ''), bundle_ref),
    bundle_digest = coalesce(nullif($3::text, ''), bundle_digest),
    bundle_revision = CASE WHEN $4::integer > 0
                           THEN $4::integer ELSE bundle_revision END,
    failure_code = nullif($5::text, '')
WHERE id = $6::uuid
  AND state = $7::text
  AND version = $8::integer
`

type TransitionSessionParams struct {
	ToState         string
	BundleRef       string
	BundleDigest    string
	BundleRevision  int32
	FailureCode     string
	ID              string
	FromState       string
	ExpectedVersion int32
}

// The guards are the aggregate's whole concurrency story. Zero rows means the
// state or the version the caller read is no longer true, and the caller
// re-reads to say which; the update never overwrites either silently.
func (q *Queries) TransitionSession(ctx context.Context, arg TransitionSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionSession,
		arg.ToState,
		arg.BundleRef,
		arg.BundleDigest,
		arg.BundleRevision,
		arg.FailureCode,
		arg.ID,
		arg.FromState,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
