// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package progressiondb

import (
	"context"
	"time"
)

const insertObservation = `-- name: InsertObservation :execrows

INSERT INTO progression.observations
    (id, candidate_id, mode, tenant_id, session_id, evaluation_id,
     competency_id, status, band, confidence, evidence_count,
     supporting, contradictory, unverified, gaps,
     rubric_reference, rubric_version, rubric_digest,
     aggregation_version, extraction_version, model_version, policy_version,
     supersedes, observed_at)
VALUES ($1::uuid, $2::uuid, $3::text,
        nullif($4::text, '')::uuid,
        $5::uuid, $6::uuid,
        $7::text, $8::text,
        $9::text, $10::text,
        $11::integer,
        $12::integer, $13::integer,
        $14::integer, $15::integer,
        $16::text, $17::text,
        $18::text,
        $19::text, $20::text,
        $21::text, $22::text,
        nullif($23::text, '')::uuid,
        $24::timestamptz)
ON CONFLICT (evaluation_id, competency_id) DO NOTHING
`

type InsertObservationParams struct {
	ID                 string
	CandidateID        string
	Mode               string
	TenantID           string
	SessionID          string
	EvaluationID       string
	CompetencyID       string
	Status             string
	Band               string
	Confidence         string
	EvidenceCount      int32
	Supporting         int32
	Contradictory      int32
	Unverified         int32
	Gaps               int32
	RubricReference    string
	RubricVersion      string
	RubricDigest       string
	AggregationVersion string
	ExtractionVersion  string
	ModelVersion       string
	PolicyVersion      string
	Supersedes         string
	ObservedAt         time.Time
}

// The progression store's queries. sqlc generates the Go beside this
// file; ADR-0010 records why no SQL lives in Go source.
// Idempotent per (evaluation, competency): the consumer's retry converges
// on the history already written.
func (q *Queries) InsertObservation(ctx context.Context, arg InsertObservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertObservation,
		arg.ID,
		arg.CandidateID,
		arg.Mode,
		arg.TenantID,
		arg.SessionID,
		arg.EvaluationID,
		arg.CompetencyID,
		arg.Status,
		arg.Band,
		arg.Confidence,
		arg.EvidenceCount,
		arg.Supporting,
		arg.Contradictory,
		arg.Unverified,
		arg.Gaps,
		arg.RubricReference,
		arg.RubricVersion,
		arg.RubricDigest,
		arg.AggregationVersion,
		arg.ExtractionVersion,
		arg.ModelVersion,
		arg.PolicyVersion,
		arg.Supersedes,
		arg.ObservedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listObservations = `-- name: ListObservations :many
SELECT id::text AS id, session_id::text AS session_id,
       evaluation_id::text AS evaluation_id, competency_id,
       status, band, confidence, evidence_count,
       supporting, contradictory, unverified, gaps,
       rubric_reference, rubric_version, rubric_digest,
       aggregation_version, extraction_version, model_version, policy_version,
       coalesce(supersedes::text, '')::text AS supersedes,
       observed_at, created_at
FROM progression.observations
ORDER BY observed_at, competency_id
`

type ListObservationsRow struct {
	ID                 string
	SessionID          string
	EvaluationID       string
	CompetencyID       string
	Status             string
	Band               string
	Confidence         string
	EvidenceCount      int32
	Supporting         int32
	Contradictory      int32
	Unverified         int32
	Gaps               int32
	RubricReference    string
	RubricVersion      string
	RubricDigest       string
	AggregationVersion string
	ExtractionVersion  string
	ModelVersion       string
	PolicyVersion      string
	Supersedes         string
	ObservedAt         time.Time
	CreatedAt          time.Time
}

// The whole history for one candidate, oldest first: what a progression
// chart plots, every version of every reading included.
func (q *Queries) ListObservations(ctx context.Context) ([]ListObservationsRow, error) {
	rows, err := q.db.Query(ctx, listObservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObservationsRow{}
	for rows.Next() {
		var i ListObservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.EvaluationID,
			&i.CompetencyID,
			&i.Status,
			&i.Band,
			&i.Confidence,
			&i.EvidenceCount,
			&i.Supporting,
			&i.Contradictory,
			&i.Unverified,
			&i.Gaps,
			&i.RubricReference,
			&i.RubricVersion,
			&i.RubricDigest,
			&i.AggregationVersion,
			&i.ExtractionVersion,
			&i.ModelVersion,
			&i.PolicyVersion,
			&i.Supersedes,
			&i.ObservedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
