// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package billingdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBillableStarts = `-- name: CountBillableStarts :one
SELECT (count(*) FILTER (WHERE kind = 'session_started')
      - count(*) FILTER (WHERE kind = 'start_credited'))::integer AS billable
FROM billing.usage_entries
WHERE tenant_id = $1::uuid
`

// What counts against the quota: starts minus credits. Computed from the
// ledger every time rather than kept as a counter, because a counter is a
// second copy of the truth and this query is one indexed aggregate.
func (q *Queries) CountBillableStarts(ctx context.Context, tenantID string) (int32, error) {
	row := q.db.QueryRow(ctx, countBillableStarts, tenantID)
	var billable int32
	err := row.Scan(&billable)
	return billable, err
}

const getQuota = `-- name: GetQuota :one
SELECT session_limit, warn_threshold::float8 AS warn_threshold, updated_at
FROM billing.quotas
WHERE tenant_id = $1::uuid
`

type GetQuotaRow struct {
	SessionLimit  pgtype.Int4
	WarnThreshold float64
	UpdatedAt     time.Time
}

func (q *Queries) GetQuota(ctx context.Context, tenantID string) (GetQuotaRow, error) {
	row := q.db.QueryRow(ctx, getQuota, tenantID)
	var i GetQuotaRow
	err := row.Scan(&i.SessionLimit, &i.WarnThreshold, &i.UpdatedAt)
	return i, err
}

const hasEntry = `-- name: HasEntry :one
SELECT EXISTS (
    SELECT 1 FROM billing.usage_entries
    WHERE session_id = $1::uuid AND kind = $2::text
) AS present
`

type HasEntryParams struct {
	SessionID string
	Kind      string
}

func (q *Queries) HasEntry(ctx context.Context, arg HasEntryParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasEntry, arg.SessionID, arg.Kind)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const insertUsageEntry = `-- name: InsertUsageEntry :exec
INSERT INTO billing.usage_entries (id, tenant_id, session_id, kind, reason, mode)
VALUES ($1::uuid, $2::uuid, $3::uuid,
        $4::text, $5::text, $6::text)
`

type InsertUsageEntryParams struct {
	ID        string
	TenantID  string
	SessionID string
	Kind      string
	Reason    string
	Mode      string
}

func (q *Queries) InsertUsageEntry(ctx context.Context, arg InsertUsageEntryParams) error {
	_, err := q.db.Exec(ctx, insertUsageEntry,
		arg.ID,
		arg.TenantID,
		arg.SessionID,
		arg.Kind,
		arg.Reason,
		arg.Mode,
	)
	return err
}

const lockQuota = `-- name: LockQuota :one

SELECT session_limit, warn_threshold::float8 AS warn_threshold
FROM billing.quotas
WHERE tenant_id = $1::uuid
FOR UPDATE
`

type LockQuotaRow struct {
	SessionLimit  pgtype.Int4
	WarnThreshold float64
}

// The billing ledger's queries. sqlc generates the Go beside this file;
// ADR-0010 records why no SQL lives in Go source.
// The reservation's serialisation point: concurrent starts at the boundary
// queue on this row lock rather than both passing at limit minus one.
// Absent row means no quota is configured, which is unlimited.
func (q *Queries) LockQuota(ctx context.Context, tenantID string) (LockQuotaRow, error) {
	row := q.db.QueryRow(ctx, lockQuota, tenantID)
	var i LockQuotaRow
	err := row.Scan(&i.SessionLimit, &i.WarnThreshold)
	return i, err
}

const upsertQuota = `-- name: UpsertQuota :exec
INSERT INTO billing.quotas (tenant_id, session_limit, warn_threshold, updated_at)
VALUES ($1::uuid,
        nullif($2::integer, -1),
        $3::float8, now())
ON CONFLICT (tenant_id) DO UPDATE SET
    session_limit = excluded.session_limit,
    warn_threshold = excluded.warn_threshold,
    updated_at = now()
`

type UpsertQuotaParams struct {
	TenantID      string
	SessionLimit  int32
	WarnThreshold float64
}

// Configuration, not ledger: the quota row may change; the entries never do.
func (q *Queries) UpsertQuota(ctx context.Context, arg UpsertQuotaParams) error {
	_, err := q.db.Exec(ctx, upsertQuota, arg.TenantID, arg.SessionLimit, arg.WarnThreshold)
	return err
}

const usageSummary = `-- name: UsageSummary :one
SELECT count(*) FILTER (WHERE kind = 'session_started')::integer AS started,
       count(*) FILTER (WHERE kind = 'start_credited')::integer  AS credited
FROM billing.usage_entries
WHERE tenant_id = $1::uuid
`

type UsageSummaryRow struct {
	Started  int32
	Credited int32
}

func (q *Queries) UsageSummary(ctx context.Context, tenantID string) (UsageSummaryRow, error) {
	row := q.db.QueryRow(ctx, usageSummary, tenantID)
	var i UsageSummaryRow
	err := row.Scan(&i.Started, &i.Credited)
	return i, err
}
