// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package identitydb

import (
	"context"
	"time"
)

const findActionTokenByHash = `-- name: FindActionTokenByHash :one
SELECT id::text AS id, user_id::text AS user_id, purpose,
       expires_at, used_at, superseded_at, attempts
FROM identity.action_tokens
WHERE token_hash = $1::text
`

type FindActionTokenByHashRow struct {
	ID           string
	UserID       string
	Purpose      string
	ExpiresAt    time.Time
	UsedAt       *time.Time
	SupersededAt *time.Time
	Attempts     int32
}

// Reads the token whatever its state, because the states are the outcomes:
// expired, used and superseded each earn their own explanation, and a query
// that filtered them out would collapse all three into "invalid".
func (q *Queries) FindActionTokenByHash(ctx context.Context, tokenHash string) (FindActionTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, findActionTokenByHash, tokenHash)
	var i FindActionTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.SupersededAt,
		&i.Attempts,
	)
	return i, err
}

const findCredentialsByEmail = `-- name: FindCredentialsByEmail :one

SELECT u.id::text AS user_id, c.password_hash
FROM identity.users u
JOIN identity.credentials c ON c.user_id = u.id
WHERE u.email = $1 AND u.status = 'active'
`

type FindCredentialsByEmailRow struct {
	UserID       string
	PasswordHash string
}

// Identity's queries. sqlc generates the Go in this directory from this file;
// ADR-0008 records why they moved here from hand-written pgx.
//
// Nothing here is tenant scoped, because identity is not: a person is not owned
// by a tenant. Membership carries the tenant and its policy. See ADR-0002.
//
// Several statements below are deliberately reached only inside a transaction
// that has already set the acting user, because row-level security, not a WHERE
// clause, is what decides which rows they can see. The repository is where that
// happens; sqlc's Queries takes the transaction and cannot set it itself.
// The login read. Returns nothing for a suspended or deleted account, so those
// fail exactly as a wrong password does rather than in a distinguishable way.
func (q *Queries) FindCredentialsByEmail(ctx context.Context, email string) (FindCredentialsByEmailRow, error) {
	row := q.db.QueryRow(ctx, findCredentialsByEmail, email)
	var i FindCredentialsByEmailRow
	err := row.Scan(&i.UserID, &i.PasswordHash)
	return i, err
}

const findLiveOTP = `-- name: FindLiveOTP :one
SELECT id::text AS id, token_hash, expires_at, attempts
FROM identity.action_tokens
WHERE user_id = $1::uuid
  AND purpose = 'otp'
  AND used_at IS NULL
  AND superseded_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type FindLiveOTPRow struct {
	ID        string
	TokenHash string
	ExpiresAt time.Time
	Attempts  int32
}

// A code is looked up by who it was issued to rather than by hash, because
// six digits are not unique enough to be an address. Newest first: after a
// resend the person may still have both emails open.
func (q *Queries) FindLiveOTP(ctx context.Context, userID string) (FindLiveOTPRow, error) {
	row := q.db.QueryRow(ctx, findLiveOTP, userID)
	var i FindLiveOTPRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Attempts,
	)
	return i, err
}

const findRole = `-- name: FindRole :one
SELECT role FROM tenancy.memberships
WHERE user_id = $1 AND tenant_id = $2 AND status = 'active'
`

type FindRoleParams struct {
	UserID   string
	TenantID string
}

// A revoked membership is not found, so revoking one takes effect on the next
// request rather than whenever a session happens to end.
func (q *Queries) FindRole(ctx context.Context, arg FindRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, findRole, arg.UserID, arg.TenantID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const findSessionByRefresh = `-- name: FindSessionByRefresh :one
SELECT id::text AS id, user_id::text AS user_id, family_id::text AS family_id,
       session_token_hash, refresh_token_hash,
       issued_at, expires_at, refresh_expires_at, authenticated_at,
       retired_at, revoked_at, coalesce(active_tenant_id::text, '')::text AS active_tenant_id
FROM identity.sessions
WHERE refresh_token_hash = $1
`

type FindSessionByRefreshRow struct {
	ID               string
	UserID           string
	FamilyID         string
	SessionTokenHash string
	RefreshTokenHash string
	IssuedAt         time.Time
	ExpiresAt        time.Time
	RefreshExpiresAt time.Time
	AuthenticatedAt  time.Time
	RetiredAt        *time.Time
	RevokedAt        *time.Time
	ActiveTenantID   string
}

// Finds retired rows too, deliberately. Finding one is exactly how token reuse
// is detected, so excluding them would remove the signal.
func (q *Queries) FindSessionByRefresh(ctx context.Context, refreshTokenHash string) (FindSessionByRefreshRow, error) {
	row := q.db.QueryRow(ctx, findSessionByRefresh, refreshTokenHash)
	var i FindSessionByRefreshRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.SessionTokenHash,
		&i.RefreshTokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RefreshExpiresAt,
		&i.AuthenticatedAt,
		&i.RetiredAt,
		&i.RevokedAt,
		&i.ActiveTenantID,
	)
	return i, err
}

const findSessionByToken = `-- name: FindSessionByToken :one
SELECT id::text AS id, user_id::text AS user_id, family_id::text AS family_id,
       session_token_hash, refresh_token_hash,
       issued_at, expires_at, refresh_expires_at, authenticated_at,
       retired_at, revoked_at, coalesce(active_tenant_id::text, '')::text AS active_tenant_id
FROM identity.sessions
WHERE session_token_hash = $1
`

type FindSessionByTokenRow struct {
	ID               string
	UserID           string
	FamilyID         string
	SessionTokenHash string
	RefreshTokenHash string
	IssuedAt         time.Time
	ExpiresAt        time.Time
	RefreshExpiresAt time.Time
	AuthenticatedAt  time.Time
	RetiredAt        *time.Time
	RevokedAt        *time.Time
	ActiveTenantID   string
}

func (q *Queries) FindSessionByToken(ctx context.Context, sessionTokenHash string) (FindSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, findSessionByToken, sessionTokenHash)
	var i FindSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.SessionTokenHash,
		&i.RefreshTokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RefreshExpiresAt,
		&i.AuthenticatedAt,
		&i.RetiredAt,
		&i.RevokedAt,
		&i.ActiveTenantID,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id::text AS id, coalesce(email::text, '')::text AS email, email_verified
FROM identity.users
WHERE id = $1 AND status <> 'deleted'
`

type FindUserByIDRow struct {
	ID            string
	Email         string
	EmailVerified bool
}

// The fields GET /me reports, and only those. A SELECT * here would put status
// and version into a struct one refactor away from being serialised to a
// browser, and a person's suspension status is not theirs to read from an
// endpoint about themselves.
func (q *Queries) FindUserByID(ctx context.Context, id string) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerified)
	return i, err
}

const insertActionToken = `-- name: InsertActionToken :exec
INSERT INTO identity.action_tokens (id, user_id, purpose, token_hash, expires_at)
VALUES ($1::uuid, $2::uuid, $3::text,
        $4::text, $5::timestamptz)
`

type InsertActionTokenParams struct {
	ID        string
	UserID    string
	Purpose   string
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) InsertActionToken(ctx context.Context, arg InsertActionTokenParams) error {
	_, err := q.db.Exec(ctx, insertActionToken,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit.events
    (id, tenant_id, actor_id, actor_type, action, subject_type, subject_id, outcome, request_id)
VALUES ($1::uuid, NULL, $2::uuid, 'user', $3::text,
        nullif($4::text, ''), nullif($5::text, ''),
        $6::text, nullif($7::text, ''))
`

type InsertAuditEventParams struct {
	ID          string
	ActorID     string
	Action      string
	SubjectType string
	SubjectID   string
	Outcome     string
	RequestID   string
}

// tenant_id is left NULL because tenant selection happens before a tenant is
// chosen. The audit policy makes such a row writable and readable by its own
// actor, which is the only meaningful scope it has.
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.ActorID,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.Outcome,
		arg.RequestID,
	)
	return err
}

const insertCredentials = `-- name: InsertCredentials :exec
INSERT INTO identity.credentials (user_id, password_hash) VALUES ($1, $2)
`

type InsertCredentialsParams struct {
	UserID       string
	PasswordHash string
}

func (q *Queries) InsertCredentials(ctx context.Context, arg InsertCredentialsParams) error {
	_, err := q.db.Exec(ctx, insertCredentials, arg.UserID, arg.PasswordHash)
	return err
}

const insertOwningMembership = `-- name: InsertOwningMembership :exec
INSERT INTO tenancy.memberships (id, tenant_id, user_id, status, role)
VALUES ($1, $2, $3, 'active', 'owner')
`

type InsertOwningMembershipParams struct {
	ID       string
	TenantID string
	UserID   string
}

// What makes a workspace administrable. A tenant without one is a row nobody
// can reach, including support.
func (q *Queries) InsertOwningMembership(ctx context.Context, arg InsertOwningMembershipParams) error {
	_, err := q.db.Exec(ctx, insertOwningMembership, arg.ID, arg.TenantID, arg.UserID)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO identity.sessions
    (id, user_id, family_id, session_token_hash, refresh_token_hash,
     issued_at, expires_at, refresh_expires_at, authenticated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertSessionParams struct {
	ID               string
	UserID           string
	FamilyID         string
	SessionTokenHash string
	RefreshTokenHash string
	IssuedAt         time.Time
	ExpiresAt        time.Time
	RefreshExpiresAt time.Time
	AuthenticatedAt  time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.FamilyID,
		arg.SessionTokenHash,
		arg.RefreshTokenHash,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.RefreshExpiresAt,
		arg.AuthenticatedAt,
	)
	return err
}

const insertTenant = `-- name: InsertTenant :exec
INSERT INTO tenancy.tenants (id, name, slug, region) VALUES ($1, $2, $3, $4)
`

type InsertTenantParams struct {
	ID     string
	Name   string
	Slug   string
	Region string
}

// Reachable only from a transaction already scoped to the identifier being
// inserted: the policy on tenancy.tenants is written against the primary key,
// since a tenants table carrying a tenant_id would be circular. Nothing can
// create the first tenant from outside.
func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) error {
	_, err := q.db.Exec(ctx, insertTenant,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Region,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO identity.users (id, email) VALUES ($1, $2)
`

type InsertUserParams struct {
	ID    string
	Email string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser, arg.ID, arg.Email)
	return err
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT m.tenant_id::text AS tenant_id, t.name AS tenant_name, m.status, m.role
FROM tenancy.memberships m
JOIN tenancy.tenants t ON t.id = m.tenant_id
WHERE m.user_id = $1 AND m.status <> 'revoked'
ORDER BY t.name
`

type ListMembershipsByUserRow struct {
	TenantID   string
	TenantName string
	Status     string
	Role       string
}

// The WHERE on user_id is not the security boundary. It is a filter for the
// planner; the policy from migration 0007 would refuse the rows even if it were
// removed, which is the property that makes forgetting it survivable.
func (q *Queries) ListMembershipsByUser(ctx context.Context, userID string) ([]ListMembershipsByUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByUserRow{}
	for rows.Next() {
		var i ListMembershipsByUserRow
		if err := rows.Scan(
			&i.TenantID,
			&i.TenantName,
			&i.Status,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActionTokenUsed = `-- name: MarkActionTokenUsed :execrows
UPDATE identity.action_tokens
SET used_at = now()
WHERE id = $1::uuid
  AND used_at IS NULL
  AND superseded_at IS NULL
`

// The guard columns repeat the liveness check so that two concurrent
// presentations of one token race on the row update rather than both
// succeeding: the loser sees zero rows and reports the token used.
func (q *Queries) MarkActionTokenUsed(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markActionTokenUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE identity.users SET email_verified = true, updated_at = now()
WHERE id = $1::uuid
`

func (q *Queries) MarkEmailVerified(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markEmailVerified, userID)
	return err
}

const membershipExists = `-- name: MembershipExists :one
SELECT EXISTS (
    SELECT 1 FROM tenancy.memberships
    WHERE user_id = $1 AND tenant_id = $2 AND status = 'active'
) AS permitted
`

type MembershipExistsParams struct {
	UserID   string
	TenantID string
}

// The one membership check in the system. Everything downstream reads the
// selection from the session rather than re-deriving it, so this is the only
// place it can be got wrong.
func (q *Queries) MembershipExists(ctx context.Context, arg MembershipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, membershipExists, arg.UserID, arg.TenantID)
	var permitted bool
	err := row.Scan(&permitted)
	return permitted, err
}

const recordTokenAttempt = `-- name: RecordTokenAttempt :one
UPDATE identity.action_tokens
SET attempts = attempts + 1
WHERE id = $1::uuid
RETURNING attempts
`

// Counts a wrong guess and reports the total, so the caller can kill the
// token at the cap. Only the OTP path calls this: a 32-byte token is not
// guessable, a six-digit code is.
func (q *Queries) RecordTokenAttempt(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, recordTokenAttempt, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const retireSession = `-- name: RetireSession :exec
UPDATE identity.sessions SET retired_at = $2 WHERE id = $1 AND retired_at IS NULL
`

type RetireSessionParams struct {
	ID        string
	RetiredAt *time.Time
}

// Retired is not revoked. A retired row stays valid to look up precisely so
// that presenting its refresh token can be recognised as reuse.
func (q *Queries) RetireSession(ctx context.Context, arg RetireSessionParams) error {
	_, err := q.db.Exec(ctx, retireSession, arg.ID, arg.RetiredAt)
	return err
}

const revokeAllSessions = `-- name: RevokeAllSessions :exec
UPDATE identity.sessions
SET revoked_at = $1::timestamptz,
    revoked_reason = $2::text
WHERE user_id = $3::uuid AND revoked_at IS NULL
`

type RevokeAllSessionsParams struct {
	RevokedAt time.Time
	Reason    string
	UserID    string
}

// Every family, not one: after a password reset the old sessions may be the
// attacker's, and after a recovery the person expects to be the only one
// signed in.
func (q *Queries) RevokeAllSessions(ctx context.Context, arg RevokeAllSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllSessions, arg.RevokedAt, arg.Reason, arg.UserID)
	return err
}

const revokeFamily = `-- name: RevokeFamily :exec
UPDATE identity.sessions
SET revoked_at = $1::timestamptz,
    revoked_reason = $2::text
WHERE family_id = $3::uuid AND revoked_at IS NULL
`

type RevokeFamilyParams struct {
	RevokedAt time.Time
	Reason    string
	FamilyID  string
}

// Whole family rather than one row, because a reused refresh token means the
// legitimate client cannot be told from the attacker, and revoking only the row
// that was reused would leave whichever of them holds the current pair.
func (q *Queries) RevokeFamily(ctx context.Context, arg RevokeFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeFamily, arg.RevokedAt, arg.Reason, arg.FamilyID)
	return err
}

const setSessionActiveTenant = `-- name: SetSessionActiveTenant :exec
UPDATE identity.sessions SET active_tenant_id = nullif($1::text, '')::uuid
WHERE id = $2::uuid
`

type SetSessionActiveTenantParams struct {
	TenantID  string
	SessionID string
}

// An empty string clears the selection rather than failing, which is what
// leaving a workspace means.
func (q *Queries) SetSessionActiveTenant(ctx context.Context, arg SetSessionActiveTenantParams) error {
	_, err := q.db.Exec(ctx, setSessionActiveTenant, arg.TenantID, arg.SessionID)
	return err
}

const supersedeActionTokens = `-- name: SupersedeActionTokens :exec
UPDATE identity.action_tokens
SET superseded_at = now()
WHERE user_id = $1::uuid
  AND purpose = $2::text
  AND used_at IS NULL
  AND superseded_at IS NULL
`

type SupersedeActionTokensParams struct {
	UserID  string
	Purpose string
}

// Requesting a new token invalidates every live one of the same purpose, so
// only the newest email works. Run in the same transaction as the insert that
// replaces them: a supersede that commits without its successor would leave
// the person with no working token at all.
func (q *Queries) SupersedeActionTokens(ctx context.Context, arg SupersedeActionTokensParams) error {
	_, err := q.db.Exec(ctx, supersedeActionTokens, arg.UserID, arg.Purpose)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE identity.credentials SET password_hash = $2, updated_at = now() WHERE user_id = $1
`

type UpdatePasswordHashParams struct {
	UserID       string
	PasswordHash string
}

// Used when a successful login verified against outdated argon2 parameters.
func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.UserID, arg.PasswordHash)
	return err
}
