// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package identitydb

import (
	"context"
	"time"
)

const activateInvitedMembership = `-- name: ActivateInvitedMembership :execrows
UPDATE tenancy.memberships
SET status = 'active', version = version + 1, updated_at = now()
WHERE user_id = $1 AND tenant_id = $2 AND status = 'invited'
`

type ActivateInvitedMembershipParams struct {
	UserID   string
	TenantID string
}

// Selecting the workspace accepts the invitation. Runs under the tenant's
// own scope, entered only after the membership check above passed.
func (q *Queries) ActivateInvitedMembership(ctx context.Context, arg ActivateInvitedMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateInvitedMembership, arg.UserID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const activeElevationByUser = `-- name: ActiveElevationByUser :one
SELECT id::text AS id, reason, ticket, granted_at, expires_at
FROM identity.elevations
WHERE user_id = $1::uuid
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY expires_at DESC
LIMIT 1
`

type ActiveElevationByUserRow struct {
	ID        string
	Reason    string
	Ticket    string
	GrantedAt time.Time
	ExpiresAt time.Time
}

// The newest grant still alive. Expiry is compared here, at read time, so an
// elevation dies at its timestamp whether or not anything else runs.
func (q *Queries) ActiveElevationByUser(ctx context.Context, userID string) (ActiveElevationByUserRow, error) {
	row := q.db.QueryRow(ctx, activeElevationByUser, userID)
	var i ActiveElevationByUserRow
	err := row.Scan(
		&i.ID,
		&i.Reason,
		&i.Ticket,
		&i.GrantedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const changeMembershipRole = `-- name: ChangeMembershipRole :execrows
UPDATE tenancy.memberships
SET role = $1::text, version = version + 1, updated_at = now()
WHERE id = $2::uuid
  AND version = $3::integer
  AND role <> 'owner'
`

type ChangeMembershipRoleParams struct {
	Role            string
	ID              string
	ExpectedVersion int32
}

// Version-guarded, and never touching an owner: the anchor role is not this
// surface's to assign or remove.
func (q *Queries) ChangeMembershipRole(ctx context.Context, arg ChangeMembershipRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, changeMembershipRole, arg.Role, arg.ID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeOAuthState = `-- name: ConsumeOAuthState :one
UPDATE identity.oauth_states
SET used_at = now()
WHERE state_hash = $1::text
  AND used_at IS NULL
RETURNING id::text AS id, provider, code_verifier, redirect_to, expires_at
`

type ConsumeOAuthStateRow struct {
	ID           string
	Provider     string
	CodeVerifier string
	RedirectTo   string
	ExpiresAt    time.Time
}

// Take the state exactly once.
//
// The condition is the guarantee: used_at IS NULL is checked in the UPDATE
// rather than read first and written after, so two callbacks arriving together
// cannot both find it unused. The loser updates no row and is told the state
// is spent, which is what a replay is.
func (q *Queries) ConsumeOAuthState(ctx context.Context, stateHash string) (ConsumeOAuthStateRow, error) {
	row := q.db.QueryRow(ctx, consumeOAuthState, stateHash)
	var i ConsumeOAuthStateRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.CodeVerifier,
		&i.RedirectTo,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredOAuthStates = `-- name: DeleteExpiredOAuthStates :exec
DELETE FROM identity.oauth_states
WHERE expires_at < $1::timestamptz
`

// Sweep the abandoned ones. People start a sign-in and wander off.
func (q *Queries) DeleteExpiredOAuthStates(ctx context.Context, before time.Time) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthStates, before)
	return err
}

const findActionTokenByHash = `-- name: FindActionTokenByHash :one
SELECT id::text AS id, user_id::text AS user_id, purpose,
       expires_at, used_at, superseded_at, attempts
FROM identity.action_tokens
WHERE token_hash = $1::text
`

type FindActionTokenByHashRow struct {
	ID           string
	UserID       string
	Purpose      string
	ExpiresAt    time.Time
	UsedAt       *time.Time
	SupersededAt *time.Time
	Attempts     int32
}

// Reads the token whatever its state, because the states are the outcomes:
// expired, used and superseded each earn their own explanation, and a query
// that filtered them out would collapse all three into "invalid".
func (q *Queries) FindActionTokenByHash(ctx context.Context, tokenHash string) (FindActionTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, findActionTokenByHash, tokenHash)
	var i FindActionTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.SupersededAt,
		&i.Attempts,
	)
	return i, err
}

const findActiveUserByEmail = `-- name: FindActiveUserByEmail :one
SELECT id::text AS id FROM identity.users
WHERE email = $1 AND status = 'active'
`

func (q *Queries) FindActiveUserByEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRow(ctx, findActiveUserByEmail, email)
	var id string
	err := row.Scan(&id)
	return id, err
}

const findCredentialsByEmail = `-- name: FindCredentialsByEmail :one

SELECT u.id::text AS user_id, c.password_hash
FROM identity.users u
JOIN identity.credentials c ON c.user_id = u.id
WHERE u.email = $1 AND u.status = 'active'
`

type FindCredentialsByEmailRow struct {
	UserID       string
	PasswordHash string
}

// Identity's queries. sqlc generates the Go in this directory from this file;
// ADR-0008 records why they moved here from hand-written pgx.
//
// Nothing here is tenant scoped, because identity is not: a person is not owned
// by a tenant. Membership carries the tenant and its policy. See ADR-0002.
//
// Several statements below are deliberately reached only inside a transaction
// that has already set the acting user, because row-level security, not a WHERE
// clause, is what decides which rows they can see. The repository is where that
// happens; sqlc's Queries takes the transaction and cannot set it itself.
// The login read. Returns nothing for a suspended or deleted account, so those
// fail exactly as a wrong password does rather than in a distinguishable way.
func (q *Queries) FindCredentialsByEmail(ctx context.Context, email string) (FindCredentialsByEmailRow, error) {
	row := q.db.QueryRow(ctx, findCredentialsByEmail, email)
	var i FindCredentialsByEmailRow
	err := row.Scan(&i.UserID, &i.PasswordHash)
	return i, err
}

const findLiveOTP = `-- name: FindLiveOTP :one
SELECT id::text AS id, token_hash, expires_at, attempts
FROM identity.action_tokens
WHERE user_id = $1::uuid
  AND purpose = 'otp'
  AND used_at IS NULL
  AND superseded_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type FindLiveOTPRow struct {
	ID        string
	TokenHash string
	ExpiresAt time.Time
	Attempts  int32
}

// A code is looked up by who it was issued to rather than by hash, because
// six digits are not unique enough to be an address. Newest first: after a
// resend the person may still have both emails open.
func (q *Queries) FindLiveOTP(ctx context.Context, userID string) (FindLiveOTPRow, error) {
	row := q.db.QueryRow(ctx, findLiveOTP, userID)
	var i FindLiveOTPRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Attempts,
	)
	return i, err
}

const findMembershipByUser = `-- name: FindMembershipByUser :one
SELECT id::text AS id, role, status, version
FROM tenancy.memberships
WHERE user_id = $1::uuid AND tenant_id = $2::uuid
`

type FindMembershipByUserParams struct {
	UserID   string
	TenantID string
}

type FindMembershipByUserRow struct {
	ID      string
	Role    string
	Status  string
	Version int32
}

func (q *Queries) FindMembershipByUser(ctx context.Context, arg FindMembershipByUserParams) (FindMembershipByUserRow, error) {
	row := q.db.QueryRow(ctx, findMembershipByUser, arg.UserID, arg.TenantID)
	var i FindMembershipByUserRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Status,
		&i.Version,
	)
	return i, err
}

const findMembershipInTenant = `-- name: FindMembershipInTenant :one
SELECT id::text AS id, user_id::text AS user_id, role, status, version
FROM tenancy.memberships
WHERE id = $1::uuid AND tenant_id = $2::uuid
`

type FindMembershipInTenantParams struct {
	ID       string
	TenantID string
}

type FindMembershipInTenantRow struct {
	ID      string
	UserID  string
	Role    string
	Status  string
	Version int32
}

func (q *Queries) FindMembershipInTenant(ctx context.Context, arg FindMembershipInTenantParams) (FindMembershipInTenantRow, error) {
	row := q.db.QueryRow(ctx, findMembershipInTenant, arg.ID, arg.TenantID)
	var i FindMembershipInTenantRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.Version,
	)
	return i, err
}

const findOAuthIdentity = `-- name: FindOAuthIdentity :one
SELECT id::text AS id, user_id::text AS user_id, provider, subject, email
FROM identity.oauth_identities
WHERE provider = $1::text AND subject = $2::text
`

type FindOAuthIdentityParams struct {
	Provider string
	Subject  string
}

type FindOAuthIdentityRow struct {
	ID       string
	UserID   string
	Provider string
	Subject  string
	Email    string
}

// Which person this provider account signs in as, by the provider's own
// subject and never by email.
func (q *Queries) FindOAuthIdentity(ctx context.Context, arg FindOAuthIdentityParams) (FindOAuthIdentityRow, error) {
	row := q.db.QueryRow(ctx, findOAuthIdentity, arg.Provider, arg.Subject)
	var i FindOAuthIdentityRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.Email,
	)
	return i, err
}

const findRole = `-- name: FindRole :one
SELECT role FROM tenancy.memberships
WHERE user_id = $1 AND tenant_id = $2 AND status = 'active'
`

type FindRoleParams struct {
	UserID   string
	TenantID string
}

// A revoked membership is not found, so revoking one takes effect on the next
// request rather than whenever a session happens to end.
func (q *Queries) FindRole(ctx context.Context, arg FindRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, findRole, arg.UserID, arg.TenantID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const findSessionByRefresh = `-- name: FindSessionByRefresh :one
SELECT id::text AS id, user_id::text AS user_id, family_id::text AS family_id,
       session_token_hash, refresh_token_hash,
       issued_at, expires_at, refresh_expires_at, authenticated_at,
       retired_at, revoked_at, coalesce(active_tenant_id::text, '')::text AS active_tenant_id
FROM identity.sessions
WHERE refresh_token_hash = $1
`

type FindSessionByRefreshRow struct {
	ID               string
	UserID           string
	FamilyID         string
	SessionTokenHash string
	RefreshTokenHash string
	IssuedAt         time.Time
	ExpiresAt        time.Time
	RefreshExpiresAt time.Time
	AuthenticatedAt  time.Time
	RetiredAt        *time.Time
	RevokedAt        *time.Time
	ActiveTenantID   string
}

// Finds retired rows too, deliberately. Finding one is exactly how token reuse
// is detected, so excluding them would remove the signal.
func (q *Queries) FindSessionByRefresh(ctx context.Context, refreshTokenHash string) (FindSessionByRefreshRow, error) {
	row := q.db.QueryRow(ctx, findSessionByRefresh, refreshTokenHash)
	var i FindSessionByRefreshRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.SessionTokenHash,
		&i.RefreshTokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RefreshExpiresAt,
		&i.AuthenticatedAt,
		&i.RetiredAt,
		&i.RevokedAt,
		&i.ActiveTenantID,
	)
	return i, err
}

const findSessionByToken = `-- name: FindSessionByToken :one
SELECT id::text AS id, user_id::text AS user_id, family_id::text AS family_id,
       session_token_hash, refresh_token_hash,
       issued_at, expires_at, refresh_expires_at, authenticated_at,
       retired_at, revoked_at, coalesce(active_tenant_id::text, '')::text AS active_tenant_id
FROM identity.sessions
WHERE session_token_hash = $1
`

type FindSessionByTokenRow struct {
	ID               string
	UserID           string
	FamilyID         string
	SessionTokenHash string
	RefreshTokenHash string
	IssuedAt         time.Time
	ExpiresAt        time.Time
	RefreshExpiresAt time.Time
	AuthenticatedAt  time.Time
	RetiredAt        *time.Time
	RevokedAt        *time.Time
	ActiveTenantID   string
}

func (q *Queries) FindSessionByToken(ctx context.Context, sessionTokenHash string) (FindSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, findSessionByToken, sessionTokenHash)
	var i FindSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.SessionTokenHash,
		&i.RefreshTokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RefreshExpiresAt,
		&i.AuthenticatedAt,
		&i.RetiredAt,
		&i.RevokedAt,
		&i.ActiveTenantID,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id::text AS id, coalesce(email::text, '')::text AS email, email_verified
FROM identity.users
WHERE id = $1 AND status <> 'deleted'
`

type FindUserByIDRow struct {
	ID            string
	Email         string
	EmailVerified bool
}

// The fields GET /me reports, and only those. A SELECT * here would put status
// and version into a struct one refactor away from being serialised to a
// browser, and a person's suspension status is not theirs to read from an
// endpoint about themselves.
func (q *Queries) FindUserByID(ctx context.Context, id string) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(&i.ID, &i.Email, &i.EmailVerified)
	return i, err
}

const insertActionToken = `-- name: InsertActionToken :exec
INSERT INTO identity.action_tokens (id, user_id, purpose, token_hash, expires_at)
VALUES ($1::uuid, $2::uuid, $3::text,
        $4::text, $5::timestamptz)
`

type InsertActionTokenParams struct {
	ID        string
	UserID    string
	Purpose   string
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) InsertActionToken(ctx context.Context, arg InsertActionTokenParams) error {
	_, err := q.db.Exec(ctx, insertActionToken,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit.events
    (id, tenant_id, actor_id, actor_type, action, subject_type, subject_id, outcome, request_id)
VALUES ($1::uuid, NULL, $2::uuid, 'user', $3::text,
        nullif($4::text, ''), nullif($5::text, ''),
        $6::text, nullif($7::text, ''))
`

type InsertAuditEventParams struct {
	ID          string
	ActorID     string
	Action      string
	SubjectType string
	SubjectID   string
	Outcome     string
	RequestID   string
}

// tenant_id is left NULL because tenant selection happens before a tenant is
// chosen. The audit policy makes such a row writable and readable by its own
// actor, which is the only meaningful scope it has.
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.ActorID,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.Outcome,
		arg.RequestID,
	)
	return err
}

const insertCredentials = `-- name: InsertCredentials :exec
INSERT INTO identity.credentials (user_id, password_hash) VALUES ($1, $2)
`

type InsertCredentialsParams struct {
	UserID       string
	PasswordHash string
}

func (q *Queries) InsertCredentials(ctx context.Context, arg InsertCredentialsParams) error {
	_, err := q.db.Exec(ctx, insertCredentials, arg.UserID, arg.PasswordHash)
	return err
}

const insertElevatedRequestAudit = `-- name: InsertElevatedRequestAudit :exec
INSERT INTO audit.events
    (id, tenant_id, actor_id, actor_type, action, subject_type, subject_id, outcome, detail, request_id)
VALUES ($1::uuid, NULL, $2::uuid, 'user',
        'identity.elevated_request', 'elevation', $3::text, 'allowed',
        $4::jsonb, nullif($5::text, ''))
`

type InsertElevatedRequestAuditParams struct {
	ID        string
	ActorID   string
	GrantID   string
	Detail    []byte
	RequestID string
}

// One row per authenticated request made under an active grant: the record
// that access happened, whether or not anything was read, which is the
// ticket's own wording. Written from session lookup, the choke point every
// request passes exactly once.
func (q *Queries) InsertElevatedRequestAudit(ctx context.Context, arg InsertElevatedRequestAuditParams) error {
	_, err := q.db.Exec(ctx, insertElevatedRequestAudit,
		arg.ID,
		arg.ActorID,
		arg.GrantID,
		arg.Detail,
		arg.RequestID,
	)
	return err
}

const insertElevation = `-- name: InsertElevation :exec
INSERT INTO identity.elevations (id, user_id, reason, ticket, expires_at)
VALUES ($1::uuid, $2::uuid, $3::text,
        $4::text, $5::timestamptz)
`

type InsertElevationParams struct {
	ID        string
	UserID    string
	Reason    string
	Ticket    string
	ExpiresAt time.Time
}

func (q *Queries) InsertElevation(ctx context.Context, arg InsertElevationParams) error {
	_, err := q.db.Exec(ctx, insertElevation,
		arg.ID,
		arg.UserID,
		arg.Reason,
		arg.Ticket,
		arg.ExpiresAt,
	)
	return err
}

const insertElevationAudit = `-- name: InsertElevationAudit :exec
INSERT INTO audit.events
    (id, tenant_id, actor_id, actor_type, action, subject_type, subject_id, outcome, detail)
VALUES ($1::uuid, NULL, $2::uuid, 'user',
        $3::text, 'elevation', $4::text,
        $5::text, $6::jsonb)
`

type InsertElevationAuditParams struct {
	ID      string
	ActorID string
	Action  string
	GrantID string
	Outcome string
	Detail  []byte
}

// Grants and revocations, with reason and ticket in the detail so the trail
// answers "why" without a join.
func (q *Queries) InsertElevationAudit(ctx context.Context, arg InsertElevationAuditParams) error {
	_, err := q.db.Exec(ctx, insertElevationAudit,
		arg.ID,
		arg.ActorID,
		arg.Action,
		arg.GrantID,
		arg.Outcome,
		arg.Detail,
	)
	return err
}

const insertInvitedMembership = `-- name: InsertInvitedMembership :exec
INSERT INTO tenancy.memberships (id, tenant_id, user_id, status, role)
VALUES ($1::uuid, $2::uuid, $3::uuid,
        'invited', $4::text)
`

type InsertInvitedMembershipParams struct {
	ID       string
	TenantID string
	UserID   string
	Role     string
}

func (q *Queries) InsertInvitedMembership(ctx context.Context, arg InsertInvitedMembershipParams) error {
	_, err := q.db.Exec(ctx, insertInvitedMembership,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Role,
	)
	return err
}

const insertOAuthState = `-- name: InsertOAuthState :exec
INSERT INTO identity.oauth_states (id, provider, state_hash, code_verifier, redirect_to, expires_at)
VALUES ($1::uuid, $2::text, $3::text,
        $4::text, $5::text, $6::timestamptz)
`

type InsertOAuthStateParams struct {
	ID           string
	Provider     string
	StateHash    string
	CodeVerifier string
	RedirectTo   string
	ExpiresAt    time.Time
}

// Mint one in-flight authorisation. The state is stored hashed; the verifier
// must be plaintext because the provider's token endpoint has to receive it.
func (q *Queries) InsertOAuthState(ctx context.Context, arg InsertOAuthStateParams) error {
	_, err := q.db.Exec(ctx, insertOAuthState,
		arg.ID,
		arg.Provider,
		arg.StateHash,
		arg.CodeVerifier,
		arg.RedirectTo,
		arg.ExpiresAt,
	)
	return err
}

const insertOwningMembership = `-- name: InsertOwningMembership :exec
INSERT INTO tenancy.memberships (id, tenant_id, user_id, status, role)
VALUES ($1, $2, $3, 'active', 'owner')
`

type InsertOwningMembershipParams struct {
	ID       string
	TenantID string
	UserID   string
}

// What makes a workspace administrable. A tenant without one is a row nobody
// can reach, including support.
func (q *Queries) InsertOwningMembership(ctx context.Context, arg InsertOwningMembershipParams) error {
	_, err := q.db.Exec(ctx, insertOwningMembership, arg.ID, arg.TenantID, arg.UserID)
	return err
}

const insertSensitiveReadEvent = `-- name: InsertSensitiveReadEvent :exec
INSERT INTO audit.events
    (id, tenant_id, actor_id, actor_type, action, subject_type, subject_id, outcome, request_id)
VALUES ($1::uuid,
        nullif($2::text, '')::uuid,
        nullif($3::text, '')::uuid,
        'user',
        $4::text,
        nullif($5::text, ''),
        nullif($6::text, ''),
        $7::text,
        nullif($8::text, ''))
`

type InsertSensitiveReadEventParams struct {
	ID          string
	TenantID    string
	ActorID     string
	Action      string
	SubjectType string
	SubjectID   string
	Outcome     string
	RequestID   string
}

// One row per access to restricted content, written before the content is
// served.
//
// Separate from InsertAuditEvent because that one hardcodes a NULL tenant for
// the sign-in path, and a sensitive read may happen inside a workspace. The
// actor is nullable here for the case that one is: a request with no usable
// session still made an attempt, and an attempt nobody can attribute is more
// worth recording than less.
func (q *Queries) InsertSensitiveReadEvent(ctx context.Context, arg InsertSensitiveReadEventParams) error {
	_, err := q.db.Exec(ctx, insertSensitiveReadEvent,
		arg.ID,
		arg.TenantID,
		arg.ActorID,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.Outcome,
		arg.RequestID,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO identity.sessions
    (id, user_id, family_id, session_token_hash, refresh_token_hash,
     issued_at, expires_at, refresh_expires_at, authenticated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertSessionParams struct {
	ID               string
	UserID           string
	FamilyID         string
	SessionTokenHash string
	RefreshTokenHash string
	IssuedAt         time.Time
	ExpiresAt        time.Time
	RefreshExpiresAt time.Time
	AuthenticatedAt  time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.FamilyID,
		arg.SessionTokenHash,
		arg.RefreshTokenHash,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.RefreshExpiresAt,
		arg.AuthenticatedAt,
	)
	return err
}

const insertTenant = `-- name: InsertTenant :exec
INSERT INTO tenancy.tenants (id, name, slug, region) VALUES ($1, $2, $3, $4)
`

type InsertTenantParams struct {
	ID     string
	Name   string
	Slug   string
	Region string
}

// Reachable only from a transaction already scoped to the identifier being
// inserted: the policy on tenancy.tenants is written against the primary key,
// since a tenants table carrying a tenant_id would be circular. Nothing can
// create the first tenant from outside.
func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) error {
	_, err := q.db.Exec(ctx, insertTenant,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Region,
	)
	return err
}

const insertTenantAuditEvent = `-- name: InsertTenantAuditEvent :exec
INSERT INTO audit.events
    (id, tenant_id, actor_id, actor_type, action, subject_type, subject_id, outcome, detail)
VALUES ($1::uuid, $2::uuid, $3::uuid, 'user',
        $4::text, nullif($5::text, ''),
        nullif($6::text, ''), $7::text,
        $8::jsonb)
`

type InsertTenantAuditEventParams struct {
	ID          string
	TenantID    string
	ActorID     string
	Action      string
	SubjectType string
	SubjectID   string
	Outcome     string
	Detail      []byte
}

// The member-administration audit row: tenant-scoped, with the detail the
// box demands - a role change carries the previous value.
func (q *Queries) InsertTenantAuditEvent(ctx context.Context, arg InsertTenantAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertTenantAuditEvent,
		arg.ID,
		arg.TenantID,
		arg.ActorID,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.Outcome,
		arg.Detail,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO identity.users (id, email) VALUES ($1, $2)
`

type InsertUserParams struct {
	ID    string
	Email string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser, arg.ID, arg.Email)
	return err
}

const linkOAuthIdentity = `-- name: LinkOAuthIdentity :exec
INSERT INTO identity.oauth_identities (id, user_id, provider, subject, email)
VALUES ($1::uuid, $2::uuid, $3::text,
        $4::text, $5::text)
ON CONFLICT (provider, subject)
DO UPDATE SET email = excluded.email, last_seen = now()
`

type LinkOAuthIdentityParams struct {
	ID       string
	UserID   string
	Provider string
	Subject  string
	Email    string
}

// Link a provider account to a person, or refresh what we know about a link
// that already exists.
func (q *Queries) LinkOAuthIdentity(ctx context.Context, arg LinkOAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, linkOAuthIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.Email,
	)
	return err
}

const listActiveElevations = `-- name: ListActiveElevations :many
SELECT e.id::text AS id, e.user_id::text AS user_id,
       coalesce(u.email::text, '')::text AS email,
       e.reason, e.ticket, e.granted_at, e.expires_at
FROM identity.elevations e
JOIN identity.users u ON u.id = e.user_id
WHERE e.revoked_at IS NULL AND e.expires_at > now()
ORDER BY e.expires_at
`

type ListActiveElevationsRow struct {
	ID        string
	UserID    string
	Email     string
	Reason    string
	Ticket    string
	GrantedAt time.Time
	ExpiresAt time.Time
}

// The visibility criterion: who is elevated right now, for the operator and
// their team. Joined to users so the list names people, not identifiers.
func (q *Queries) ListActiveElevations(ctx context.Context) ([]ListActiveElevationsRow, error) {
	rows, err := q.db.Query(ctx, listActiveElevations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveElevationsRow{}
	for rows.Next() {
		var i ListActiveElevationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Reason,
			&i.Ticket,
			&i.GrantedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many

SELECT m.id::text AS membership_id, m.user_id::text AS user_id,
       coalesce(u.email::text, '')::text AS email,
       m.role, m.status, m.version, m.created_at
FROM tenancy.memberships m
JOIN identity.users u ON u.id = m.user_id
WHERE m.tenant_id = $1::uuid
ORDER BY m.created_at, m.id
`

type ListMembersRow struct {
	MembershipID string
	UserID       string
	Email        string
	Role         string
	Status       string
	Version      int32
	CreatedAt    time.Time
}

// ── TEN-02: member administration. Every statement here runs in a
// transaction scoped to the administrator's active tenant, so the policy
// from 0001 confines each to one workspace.
func (q *Queries) ListMembers(ctx context.Context, tenantID string) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.UserID,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT m.tenant_id::text AS tenant_id, t.name AS tenant_name, m.status, m.role
FROM tenancy.memberships m
JOIN tenancy.tenants t ON t.id = m.tenant_id
WHERE m.user_id = $1 AND m.status <> 'revoked'
ORDER BY t.name
`

type ListMembershipsByUserRow struct {
	TenantID   string
	TenantName string
	Status     string
	Role       string
}

// The WHERE on user_id is not the security boundary. It is a filter for the
// planner; the policy from migration 0007 would refuse the rows even if it were
// removed, which is the property that makes forgetting it survivable.
func (q *Queries) ListMembershipsByUser(ctx context.Context, userID string) ([]ListMembershipsByUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByUserRow{}
	for rows.Next() {
		var i ListMembershipsByUserRow
		if err := rows.Scan(
			&i.TenantID,
			&i.TenantName,
			&i.Status,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActionTokenUsed = `-- name: MarkActionTokenUsed :execrows
UPDATE identity.action_tokens
SET used_at = now()
WHERE id = $1::uuid
  AND used_at IS NULL
  AND superseded_at IS NULL
`

// The guard columns repeat the liveness check so that two concurrent
// presentations of one token race on the row update rather than both
// succeeding: the loser sees zero rows and reports the token used.
func (q *Queries) MarkActionTokenUsed(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markActionTokenUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE identity.users SET email_verified = true, updated_at = now()
WHERE id = $1::uuid
`

func (q *Queries) MarkEmailVerified(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markEmailVerified, userID)
	return err
}

const membershipExists = `-- name: MembershipExists :one
SELECT EXISTS (
    SELECT 1 FROM tenancy.memberships
    WHERE user_id = $1 AND tenant_id = $2 AND status IN ('active', 'invited')
) AS permitted
`

type MembershipExistsParams struct {
	UserID   string
	TenantID string
}

// The one membership check in the system. Everything downstream reads the
// selection from the session rather than re-deriving it, so this is the only
// place it can be got wrong. An invited membership counts: selecting the
// workspace is how an invitation is accepted, and the activation below runs
// in the same transaction. A revoked one never does.
func (q *Queries) MembershipExists(ctx context.Context, arg MembershipExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, membershipExists, arg.UserID, arg.TenantID)
	var permitted bool
	err := row.Scan(&permitted)
	return permitted, err
}

const recordTokenAttempt = `-- name: RecordTokenAttempt :one
UPDATE identity.action_tokens
SET attempts = attempts + 1
WHERE id = $1::uuid
RETURNING attempts
`

// Counts a wrong guess and reports the total, so the caller can kill the
// token at the cap. Only the OTP path calls this: a 32-byte token is not
// guessable, a six-digit code is.
func (q *Queries) RecordTokenAttempt(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, recordTokenAttempt, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const reinviteMembership = `-- name: ReinviteMembership :execrows
UPDATE tenancy.memberships
SET status = 'invited', role = $1::text,
    version = version + 1, updated_at = now()
WHERE id = $2::uuid AND status = 'revoked'
`

type ReinviteMembershipParams struct {
	Role string
	ID   string
}

// A revoked person invited again gets their old row back as a fresh
// invitation, because the row's history - decisions they recorded - is why
// it was never deleted.
func (q *Queries) ReinviteMembership(ctx context.Context, arg ReinviteMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, reinviteMembership, arg.Role, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireSession = `-- name: RetireSession :exec
UPDATE identity.sessions SET retired_at = $2 WHERE id = $1 AND retired_at IS NULL
`

type RetireSessionParams struct {
	ID        string
	RetiredAt *time.Time
}

// Retired is not revoked. A retired row stays valid to look up precisely so
// that presenting its refresh token can be recognised as reuse.
func (q *Queries) RetireSession(ctx context.Context, arg RetireSessionParams) error {
	_, err := q.db.Exec(ctx, retireSession, arg.ID, arg.RetiredAt)
	return err
}

const revokeAllSessions = `-- name: RevokeAllSessions :exec
UPDATE identity.sessions
SET revoked_at = $1::timestamptz,
    revoked_reason = $2::text
WHERE user_id = $3::uuid AND revoked_at IS NULL
`

type RevokeAllSessionsParams struct {
	RevokedAt time.Time
	Reason    string
	UserID    string
}

// Every family, not one: after a password reset the old sessions may be the
// attacker's, and after a recovery the person expects to be the only one
// signed in.
func (q *Queries) RevokeAllSessions(ctx context.Context, arg RevokeAllSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeAllSessions, arg.RevokedAt, arg.Reason, arg.UserID)
	return err
}

const revokeElevation = `-- name: RevokeElevation :execrows
UPDATE identity.elevations
SET revoked_at = now(), revoked_by = $1::uuid
WHERE id = $2::uuid AND revoked_at IS NULL AND expires_at > now()
`

type RevokeElevationParams struct {
	RevokedBy string
	ID        string
}

// Guarded on liveness: revoking an already-dead grant reports zero rows and
// the caller says so, rather than stamping a second ending on it.
func (q *Queries) RevokeElevation(ctx context.Context, arg RevokeElevationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeElevation, arg.RevokedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeFamily = `-- name: RevokeFamily :exec
UPDATE identity.sessions
SET revoked_at = $1::timestamptz,
    revoked_reason = $2::text
WHERE family_id = $3::uuid AND revoked_at IS NULL
`

type RevokeFamilyParams struct {
	RevokedAt time.Time
	Reason    string
	FamilyID  string
}

// Whole family rather than one row, because a reused refresh token means the
// legitimate client cannot be told from the attacker, and revoking only the row
// that was reused would leave whichever of them holds the current pair.
func (q *Queries) RevokeFamily(ctx context.Context, arg RevokeFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeFamily, arg.RevokedAt, arg.Reason, arg.FamilyID)
	return err
}

const revokeMembership = `-- name: RevokeMembership :execrows
UPDATE tenancy.memberships
SET status = 'revoked', version = version + 1, updated_at = now()
WHERE id = $1::uuid
  AND version = $2::integer
  AND role <> 'owner' AND status <> 'revoked'
`

type RevokeMembershipParams struct {
	ID              string
	ExpectedVersion int32
}

func (q *Queries) RevokeMembership(ctx context.Context, arg RevokeMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeMembership, arg.ID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSessionActiveTenant = `-- name: SetSessionActiveTenant :exec
UPDATE identity.sessions SET active_tenant_id = nullif($1::text, '')::uuid
WHERE id = $2::uuid
`

type SetSessionActiveTenantParams struct {
	TenantID  string
	SessionID string
}

// An empty string clears the selection rather than failing, which is what
// leaving a workspace means.
func (q *Queries) SetSessionActiveTenant(ctx context.Context, arg SetSessionActiveTenantParams) error {
	_, err := q.db.Exec(ctx, setSessionActiveTenant, arg.TenantID, arg.SessionID)
	return err
}

const supersedeActionTokens = `-- name: SupersedeActionTokens :exec
UPDATE identity.action_tokens
SET superseded_at = now()
WHERE user_id = $1::uuid
  AND purpose = $2::text
  AND used_at IS NULL
  AND superseded_at IS NULL
`

type SupersedeActionTokensParams struct {
	UserID  string
	Purpose string
}

// Requesting a new token invalidates every live one of the same purpose, so
// only the newest email works. Run in the same transaction as the insert that
// replaces them: a supersede that commits without its successor would leave
// the person with no working token at all.
func (q *Queries) SupersedeActionTokens(ctx context.Context, arg SupersedeActionTokensParams) error {
	_, err := q.db.Exec(ctx, supersedeActionTokens, arg.UserID, arg.Purpose)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE identity.credentials SET password_hash = $2, updated_at = now() WHERE user_id = $1
`

type UpdatePasswordHashParams struct {
	UserID       string
	PasswordHash string
}

// Used when a successful login verified against outdated argon2 parameters.
func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.UserID, arg.PasswordHash)
	return err
}
