// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package ratelimitdb

import (
	"context"
	"time"
)

const increment = `-- name: Increment :one

INSERT INTO security_rate_limit_counters (key, window_start, count)
VALUES ($1, $2, 1)
ON CONFLICT (key, window_start)
DO UPDATE SET count = security_rate_limit_counters.count + 1
RETURNING count
`

type IncrementParams struct {
	Key         string
	WindowStart time.Time
}

// The rate limiter's queries. sqlc generates the Go in this directory from this
// file; ADR-0008 records why they moved here from hand-written pgx.
// One statement, not a read followed by a write. INSERT ... ON CONFLICT DO
// UPDATE ... RETURNING increments and reads the new value atomically, so two
// requests arriving together cannot both read the old count and both be
// allowed. That race is the whole failure mode of a rate limiter.
func (q *Queries) Increment(ctx context.Context, arg IncrementParams) (int32, error) {
	row := q.db.QueryRow(ctx, increment, arg.Key, arg.WindowStart)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const sweep = `-- name: Sweep :execrows
DELETE FROM security_rate_limit_counters WHERE window_start < $1
`

// Old windows are deleted rather than left, because the table is unlogged and
// its only value is the current window; keeping the rest would grow a table
// nobody reads.
func (q *Queries) Sweep(ctx context.Context, windowStart time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, sweep, windowStart)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
