// Command authzgen generates the capability catalogue from its contract.
//
// The contract at packages/contracts/authz/capabilities.yaml is the source, per
// ADR-0004, and this writes the Go and TypeScript that must agree with it. A
// capability therefore cannot exist in one language and not another, and a
// requirement cannot be changed in code without changing the document that
// describes it to whoever has to review it.
//
// Run through `make generate`, which runs from the repository root, because
// output paths resolve against the working directory rather than against this
// file.
package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// contract is the shape of capabilities.yaml.
type contract struct {
	Version      int                `yaml:"version"`
	Requirements map[string]string  `yaml:"requirements"`
	Scopes       []string           `yaml:"scopes"`
	Capabilities []capabilityEntry  `yaml:"capabilities"`
}

type capabilityEntry struct {
	Name       string `yaml:"name"`
	Tenant     bool   `yaml:"tenant"`
	Scope      string `yaml:"scope"`
	Owner      bool   `yaml:"owner"`
	Platform   bool   `yaml:"platform"`
	Privileged bool   `yaml:"privileged"`
	StepUp     bool   `yaml:"step_up"`
	Reason     string `yaml:"reason"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "authzgen: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	const (
		source = "packages/contracts/authz/capabilities.yaml"
		goOut  = "services/platform/platform/authz/catalogue.gen.go"
		tsOut  = "packages/generated/typescript/capabilities.gen.ts"
	)

	raw, err := os.ReadFile(source)
	if err != nil {
		return fmt.Errorf("reading %s: %w", source, err)
	}

	var doc contract
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		return fmt.Errorf("parsing %s: %w", source, err)
	}
	if len(doc.Capabilities) == 0 {
		// A contract that parsed to nothing would generate an empty catalogue,
		// and an empty catalogue denies everything, which looks like a policy
		// change rather than a broken build.
		return fmt.Errorf("%s declares no capabilities", source)
	}

	// Sorted, so the generated files do not change when the document is
	// reordered and a diff shows only what actually changed.
	sort.Slice(doc.Capabilities, func(i, j int) bool {
		return doc.Capabilities[i].Name < doc.Capabilities[j].Name
	})

	for _, entry := range doc.Capabilities {
		if strings.TrimSpace(entry.Reason) == "" {
			// Enforced here rather than left to review. A requirement without a
			// reason is a rule nobody can argue against later.
			return fmt.Errorf("capability %q has no reason", entry.Name)
		}
	}

	if err := os.WriteFile(goOut, []byte(generateGo(doc)), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", goOut, err)
	}
	if err := os.WriteFile(tsOut, []byte(generateTypeScript(doc)), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", tsOut, err)
	}
	return nil
}

// identifier turns a capability name into a Go identifier.
//
// candidate.practice.read_own becomes CandidatePracticeReadOwn, which is what
// the hand-written catalogue used, so existing call sites keep compiling.
func identifier(name string) string {
	var out strings.Builder
	for _, part := range strings.FieldsFunc(name, func(r rune) bool { return r == '.' || r == '_' }) {
		out.WriteString(strings.ToUpper(part[:1]))
		out.WriteString(part[1:])
	}
	return out.String()
}

// comment wraps a reason as a Go or TypeScript comment body.
func comment(reason, indent string) string {
	var lines []string
	var current string
	for _, word := range strings.Fields(reason) {
		if len(current)+len(word)+1 > 68 {
			lines = append(lines, current)
			current = word
			continue
		}
		if current == "" {
			current = word
		} else {
			current += " " + word
		}
	}
	if current != "" {
		lines = append(lines, current)
	}
	for i, line := range lines {
		lines[i] = indent + "// " + line
	}
	return strings.Join(lines, "\n")
}

func generateGo(doc contract) string {
	var out strings.Builder

	fmt.Fprintf(&out, `// Code generated by tools/authzgen. DO NOT EDIT.
//
// Source: packages/contracts/authz/capabilities.yaml (version %d)
//
// The contract is the source and this file is derived from it. Editing here is
// undone by the next %s generate, and the drift gate in CI fails first.

package authz

// The catalogue, version %d.
const CatalogueVersion = %d

const (
`, doc.Version, "`make`", doc.Version, doc.Version)

	for _, entry := range doc.Capabilities {
		fmt.Fprintf(&out, "%s\n\t%s Capability = %q\n\n", comment(entry.Reason, "\t"), identifier(entry.Name), entry.Name)
	}

	out.WriteString(")\n\n// catalogue maps every capability to what it requires.\nvar catalogue = map[Capability]Requirement{\n")
	for _, entry := range doc.Capabilities {
		var parts []string
		if entry.Tenant {
			parts = append(parts, "Tenant: true")
		}
		if entry.Scope != "" {
			parts = append(parts, fmt.Sprintf("Scope: Scope%s", strings.ToUpper(entry.Scope[:1])+entry.Scope[1:]))
		}
		if entry.Owner {
			parts = append(parts, "Owner: true")
		}
		if entry.Platform {
			parts = append(parts, "Platform: true")
		}
		if entry.Privileged {
			parts = append(parts, "Privileged: true")
		}
		if entry.StepUp {
			parts = append(parts, "StepUp: true")
		}
		fmt.Fprintf(&out, "\t%s: {%s},\n", identifier(entry.Name), strings.Join(parts, ", "))
	}
	out.WriteString("}\n")

	return out.String()
}

func generateTypeScript(doc contract) string {
	var out strings.Builder

	fmt.Fprintf(&out, `/**
 * Code generated by tools/authzgen. DO NOT EDIT.
 *
 * Source: packages/contracts/authz/capabilities.yaml (version %d)
 *
 * The browser uses these to decide what to render. Rendering is never the thing
 * that stops access: the server decides, and hiding a control that somebody
 * could still reach by typing the URL would be a decoration rather than a
 * protection. What this is for is not offering somebody a button that will
 * refuse them.
 */

export const CATALOGUE_VERSION = %d;

export const CAPABILITIES = [
`, doc.Version, doc.Version)

	for _, entry := range doc.Capabilities {
		fmt.Fprintf(&out, "%s\n  %q,\n\n", comment(entry.Reason, "  "), entry.Name)
	}

	out.WriteString(`] as const;

/** Every capability name the catalogue defines. */
export type Capability = (typeof CAPABILITIES)[number];
`)

	return out.String()
}
