// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package outboxdb

import (
	"context"
	"time"
)

const claim = `-- name: Claim :many
SELECT id::text AS id, event_type, schema_version,
       coalesce(tenant_id::text, '')::text AS tenant_id,
       occurred_at, producer, actor_type, actor_id,
       coalesce(purpose, '')::text AS purpose,
       coalesce(correlation_id, '')::text AS correlation_id,
       coalesce(causation_id, '')::text AS causation_id,
       payload, attempts
FROM integration.outbox
WHERE published_at IS NULL
  AND dead_at IS NULL
  AND next_attempt_at <= now()
ORDER BY next_attempt_at, id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type ClaimRow struct {
	ID            string
	EventType     string
	SchemaVersion string
	TenantID      string
	OccurredAt    time.Time
	Producer      string
	ActorType     string
	ActorID       string
	Purpose       string
	CorrelationID string
	CausationID   string
	Payload       []byte
	Attempts      int32
}

// FOR UPDATE SKIP LOCKED is what makes more than one dispatcher safe. Without
// it two dispatchers reading the same rows would both deliver them, and a
// tenant's ATS would see one candidate submitted twice. With it, the second
// steps over the rows the first holds, so adding dispatchers adds throughput
// rather than duplicates.
//
// The rows stay claimed only for the life of the caller's transaction. A
// dispatcher that dies mid-delivery releases them and they are redelivered,
// which is the at-least-once guarantee showing its edges.
func (q *Queries) Claim(ctx context.Context, limit int32) ([]ClaimRow, error) {
	rows, err := q.db.Query(ctx, claim, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimRow{}
	for rows.Next() {
		var i ClaimRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.SchemaVersion,
			&i.TenantID,
			&i.OccurredAt,
			&i.Producer,
			&i.ActorType,
			&i.ActorID,
			&i.Purpose,
			&i.CorrelationID,
			&i.CausationID,
			&i.Payload,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hideClaimed = `-- name: HideClaimed :exec
UPDATE integration.outbox
SET next_attempt_at = now() + $1::interval
WHERE id = ANY($2::uuid[])
`

type HideClaimedParams struct {
	Visibility string
	Ids        []string
}

// Marked inside the same transaction that locked the rows, so releasing the
// lock and recording the attempt happen together.
func (q *Queries) HideClaimed(ctx context.Context, arg HideClaimedParams) error {
	_, err := q.db.Exec(ctx, hideClaimed, arg.Visibility, arg.Ids)
	return err
}

const insertEvent = `-- name: InsertEvent :exec

INSERT INTO integration.outbox
    (id, event_type, schema_version, tenant_id, occurred_at, producer,
     actor_type, actor_id, purpose, correlation_id, causation_id, payload)
VALUES ($1::uuid, $2::text, $3::text,
        nullif($4::text, '')::uuid, $5::timestamptz,
        $6::text, $7::text, $8::text,
        nullif($9::text, ''), nullif($10::text, ''),
        nullif($11::text, ''), $12::jsonb)
`

type InsertEventParams struct {
	ID            string
	EventType     string
	SchemaVersion string
	TenantID      string
	OccurredAt    time.Time
	Producer      string
	ActorType     string
	ActorID       string
	Purpose       string
	CorrelationID string
	CausationID   string
	Payload       []byte
}

// The outbox's queries. sqlc generates the Go in this directory from this file;
// ADR-0008 records why they moved here from hand-written pgx.
// Written inside the caller's transaction, which is the whole point of an
// outbox: the event and the state change it describes commit together or
// neither does.
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.EventType,
		arg.SchemaVersion,
		arg.TenantID,
		arg.OccurredAt,
		arg.Producer,
		arg.ActorType,
		arg.ActorID,
		arg.Purpose,
		arg.CorrelationID,
		arg.CausationID,
		arg.Payload,
	)
	return err
}

const lockAttempts = `-- name: LockAttempts :one
SELECT attempts FROM integration.outbox WHERE id = $1 FOR UPDATE
`

// The attempt count is read here and the wait computed in Go, so the backoff
// curve lives in exactly one place. Computing it in SQL as well would mean two
// formulas that agree until somebody changes one.
func (q *Queries) LockAttempts(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, lockAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const markDelivered = `-- name: MarkDelivered :exec
UPDATE integration.outbox SET published_at = now() WHERE id = $1 AND published_at IS NULL
`

func (q *Queries) MarkDelivered(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markDelivered, id)
	return err
}

const recordFailure = `-- name: RecordFailure :exec
UPDATE integration.outbox
SET attempts = $1::integer,
    last_error = $2::text,
    next_attempt_at = now() + make_interval(secs => $3::double precision),
    dead_at = $4::timestamptz
WHERE id = $5::uuid
`

type RecordFailureParams struct {
	Attempts       int32
	LastError      string
	BackoffSeconds float64
	DeadAt         *time.Time
	ID             string
}

// After MaxAttempts the caller passes a dead_at, because an event nobody can
// deliver is an operational fact somebody needs to see rather than a row
// retried silently forever.
func (q *Queries) RecordFailure(ctx context.Context, arg RecordFailureParams) error {
	_, err := q.db.Exec(ctx, recordFailure,
		arg.Attempts,
		arg.LastError,
		arg.BackoffSeconds,
		arg.DeadAt,
		arg.ID,
	)
	return err
}
