// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package contentdb

import (
	"context"
	"time"
)

const getArtifact = `-- name: GetArtifact :one
SELECT id::text AS id, artifact_type, reference, version, schema_version, digest, body,
       status, coalesce(tenant_id::text, '')::text AS tenant_id,
       created_by::text AS created_by, created_at,
       coalesce(published_by::text, '')::text AS published_by, published_at
FROM content.artifacts
WHERE id = $1::uuid
`

type GetArtifactRow struct {
	ID            string
	ArtifactType  string
	Reference     string
	Version       string
	SchemaVersion string
	Digest        string
	Body          []byte
	Status        string
	TenantID      string
	CreatedBy     string
	CreatedAt     time.Time
	PublishedBy   string
	PublishedAt   *time.Time
}

func (q *Queries) GetArtifact(ctx context.Context, id string) (GetArtifactRow, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i GetArtifactRow
	err := row.Scan(
		&i.ID,
		&i.ArtifactType,
		&i.Reference,
		&i.Version,
		&i.SchemaVersion,
		&i.Digest,
		&i.Body,
		&i.Status,
		&i.TenantID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const getArtifactByDigest = `-- name: GetArtifactByDigest :one
SELECT id::text AS id, artifact_type, reference, version, schema_version, digest, body,
       status, coalesce(tenant_id::text, '')::text AS tenant_id,
       created_by::text AS created_by, created_at,
       coalesce(published_by::text, '')::text AS published_by, published_at
FROM content.artifacts
WHERE digest = $1::text
`

type GetArtifactByDigestRow struct {
	ID            string
	ArtifactType  string
	Reference     string
	Version       string
	SchemaVersion string
	Digest        string
	Body          []byte
	Status        string
	TenantID      string
	CreatedBy     string
	CreatedAt     time.Time
	PublishedBy   string
	PublishedAt   *time.Time
}

// The pin-resolution path: anything holding a digest reads by it, and what it
// reads can never differ from what was pinned, because published rows are
// immutable and never deleted.
func (q *Queries) GetArtifactByDigest(ctx context.Context, digest string) (GetArtifactByDigestRow, error) {
	row := q.db.QueryRow(ctx, getArtifactByDigest, digest)
	var i GetArtifactByDigestRow
	err := row.Scan(
		&i.ID,
		&i.ArtifactType,
		&i.Reference,
		&i.Version,
		&i.SchemaVersion,
		&i.Digest,
		&i.Body,
		&i.Status,
		&i.TenantID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const getArtifactByVersion = `-- name: GetArtifactByVersion :one
SELECT id::text AS id, artifact_type, reference, version, schema_version, digest, body,
       status, coalesce(tenant_id::text, '')::text AS tenant_id,
       created_by::text AS created_by, created_at,
       coalesce(published_by::text, '')::text AS published_by, published_at
FROM content.artifacts
WHERE reference = $1::text
  AND version = $2::text
  AND tenant_id IS NOT DISTINCT FROM nullif($3::text, '')::uuid
`

type GetArtifactByVersionParams struct {
	Reference string
	Version   string
	TenantID  string
}

type GetArtifactByVersionRow struct {
	ID            string
	ArtifactType  string
	Reference     string
	Version       string
	SchemaVersion string
	Digest        string
	Body          []byte
	Status        string
	TenantID      string
	CreatedBy     string
	CreatedAt     time.Time
	PublishedBy   string
	PublishedAt   *time.Time
}

func (q *Queries) GetArtifactByVersion(ctx context.Context, arg GetArtifactByVersionParams) (GetArtifactByVersionRow, error) {
	row := q.db.QueryRow(ctx, getArtifactByVersion, arg.Reference, arg.Version, arg.TenantID)
	var i GetArtifactByVersionRow
	err := row.Scan(
		&i.ID,
		&i.ArtifactType,
		&i.Reference,
		&i.Version,
		&i.SchemaVersion,
		&i.Digest,
		&i.Body,
		&i.Status,
		&i.TenantID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :exec

INSERT INTO content.artifacts
    (id, artifact_type, reference, version, schema_version, digest, body, tenant_id, created_by)
VALUES ($1::uuid, $2::text, $3::text,
        $4::text, $5::text, $6::text,
        $7::jsonb, nullif($8::text, '')::uuid,
        $9::uuid)
`

type InsertArtifactParams struct {
	ID            string
	ArtifactType  string
	Reference     string
	Version       string
	SchemaVersion string
	Digest        string
	Body          []byte
	TenantID      string
	CreatedBy     string
}

// The registry's queries. sqlc generates the Go beside this file; ADR-0010
// records why no SQL lives in Go source.
func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) error {
	_, err := q.db.Exec(ctx, insertArtifact,
		arg.ID,
		arg.ArtifactType,
		arg.Reference,
		arg.Version,
		arg.SchemaVersion,
		arg.Digest,
		arg.Body,
		arg.TenantID,
		arg.CreatedBy,
	)
	return err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit.events
    (id, tenant_id, actor_id, actor_type, action, subject_type, subject_id, outcome)
VALUES ($1::uuid, nullif($2::text, '')::uuid,
        $3::uuid, 'user', $4::text,
        'artifact', $5::text, $6::text)
`

type InsertAuditEventParams struct {
	ID        string
	TenantID  string
	ActorID   string
	Action    string
	SubjectID string
	Outcome   string
}

// Content's own audit append; pointer moves are the decisions worth reviewing.
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.TenantID,
		arg.ActorID,
		arg.Action,
		arg.SubjectID,
		arg.Outcome,
	)
	return err
}

const markPublished = `-- name: MarkPublished :execrows
UPDATE content.artifacts
SET status = 'published',
    published_by = $1::uuid,
    published_at = now()
WHERE id = $2::uuid AND status = 'approved'
`

type MarkPublishedParams struct {
	PublishedBy string
	ID          string
}

// Publication stamps provenance in the same statement that moves the status,
// so a published row without a publisher cannot exist even transiently.
func (q *Queries) MarkPublished(ctx context.Context, arg MarkPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPublished, arg.PublishedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolvePointer = `-- name: ResolvePointer :one
SELECT a.id::text AS id, a.artifact_type, a.reference, a.version, a.schema_version,
       a.digest, a.body, a.status, coalesce(a.tenant_id::text, '')::text AS tenant_id,
       a.created_by::text AS created_by, a.created_at,
       coalesce(a.published_by::text, '')::text AS published_by, a.published_at
FROM content.artifact_pointers p
JOIN content.artifacts a ON a.id = p.artifact_id
WHERE p.reference = $1::text
  AND (p.tenant_id IS NULL
       OR p.tenant_id = nullif($2::text, '')::uuid)
ORDER BY (p.tenant_id IS NOT NULL) DESC
LIMIT 1
`

type ResolvePointerParams struct {
	Reference string
	TenantID  string
}

type ResolvePointerRow struct {
	ID            string
	ArtifactType  string
	Reference     string
	Version       string
	SchemaVersion string
	Digest        string
	Body          []byte
	Status        string
	TenantID      string
	CreatedBy     string
	CreatedAt     time.Time
	PublishedBy   string
	PublishedAt   *time.Time
}

// What a composition uses next: the pointer's target, joined so one round
// trip answers both "which version" and "with what content".
//
// A tenant resolving a reference gets its own pointer where one exists and
// the platform's otherwise - a tenant's calibration of a rubric overrides
// the platform default without hiding the catalogue from everyone else. The
// ORDER BY is that precedence; row-level security has already removed other
// tenants' pointers before it runs.
func (q *Queries) ResolvePointer(ctx context.Context, arg ResolvePointerParams) (ResolvePointerRow, error) {
	row := q.db.QueryRow(ctx, resolvePointer, arg.Reference, arg.TenantID)
	var i ResolvePointerRow
	err := row.Scan(
		&i.ID,
		&i.ArtifactType,
		&i.Reference,
		&i.Version,
		&i.SchemaVersion,
		&i.Digest,
		&i.Body,
		&i.Status,
		&i.TenantID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const transitionArtifact = `-- name: TransitionArtifact :execrows
UPDATE content.artifacts
SET status = $1::text
WHERE id = $2::uuid AND status = $3::text
`

type TransitionArtifactParams struct {
	ToStatus   string
	ID         string
	FromStatus string
}

// Guarded by the current status, so a concurrent transition loses on rows
// affected rather than overwriting.
func (q *Queries) TransitionArtifact(ctx context.Context, arg TransitionArtifactParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionArtifact, arg.ToStatus, arg.ID, arg.FromStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPointer = `-- name: UpsertPointer :exec
INSERT INTO content.artifact_pointers (reference, tenant_id, artifact_id, updated_by)
VALUES ($1::text, nullif($2::text, '')::uuid,
        $3::uuid, $4::uuid)
ON CONFLICT (tenant_id, reference)
DO UPDATE SET artifact_id = excluded.artifact_id,
              updated_by = excluded.updated_by,
              updated_at = now()
`

type UpsertPointerParams struct {
	Reference  string
	TenantID   string
	ArtifactID string
	UpdatedBy  string
}

// The one mutable surface. Publication and rollback both land here, and the
// audit trail is where the history of moves lives.
func (q *Queries) UpsertPointer(ctx context.Context, arg UpsertPointerParams) error {
	_, err := q.db.Exec(ctx, upsertPointer,
		arg.Reference,
		arg.TenantID,
		arg.ArtifactID,
		arg.UpdatedBy,
	)
	return err
}
