// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package candidatedb

import (
	"context"
	"time"
)

const getProfile = `-- name: GetProfile :one

SELECT user_id::text AS user_id, disciplines, target_roles,
       coalesce(seniority, '')::text AS seniority,
       coalesce(career_context, '')::text AS career_context,
       coalesce(default_duration_minutes, 0)::integer AS default_duration_minutes,
       coalesce(default_style, '')::text AS default_style,
       coalesce(default_pressure, '')::text AS default_pressure,
       extended_time, captions, reduced_motion,
       coalesce(accessibility_notes, '')::text AS accessibility_notes,
       notify_product_updates, notify_practice_reminders,
       created_at, updated_at
FROM candidate.profiles
WHERE user_id = $1::uuid
`

type GetProfileRow struct {
	UserID                  string
	Disciplines             []string
	TargetRoles             []string
	Seniority               string
	CareerContext           string
	DefaultDurationMinutes  int32
	DefaultStyle            string
	DefaultPressure         string
	ExtendedTime            bool
	Captions                bool
	ReducedMotion           bool
	AccessibilityNotes      string
	NotifyProductUpdates    bool
	NotifyPracticeReminders bool
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

// The profile's queries. sqlc generates the Go beside this file; ADR-0010
// records why no SQL lives in Go source.
func (q *Queries) GetProfile(ctx context.Context, userID string) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i GetProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Disciplines,
		&i.TargetRoles,
		&i.Seniority,
		&i.CareerContext,
		&i.DefaultDurationMinutes,
		&i.DefaultStyle,
		&i.DefaultPressure,
		&i.ExtendedTime,
		&i.Captions,
		&i.ReducedMotion,
		&i.AccessibilityNotes,
		&i.NotifyProductUpdates,
		&i.NotifyPracticeReminders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO candidate.profiles
    (user_id, disciplines, target_roles, seniority, career_context,
     default_duration_minutes, default_style, default_pressure,
     extended_time, captions, reduced_motion, accessibility_notes,
     notify_product_updates, notify_practice_reminders)
VALUES ($1::uuid, $2::text[], $3::text[],
        nullif($4::text, ''), nullif($5::text, ''),
        nullif($6::integer, 0),
        nullif($7::text, ''), nullif($8::text, ''),
        $9::boolean, $10::boolean,
        $11::boolean, nullif($12::text, ''),
        $13::boolean, $14::boolean)
ON CONFLICT (user_id) DO UPDATE SET
    disciplines = excluded.disciplines,
    target_roles = excluded.target_roles,
    seniority = excluded.seniority,
    career_context = excluded.career_context,
    default_duration_minutes = excluded.default_duration_minutes,
    default_style = excluded.default_style,
    default_pressure = excluded.default_pressure,
    extended_time = excluded.extended_time,
    captions = excluded.captions,
    reduced_motion = excluded.reduced_motion,
    accessibility_notes = excluded.accessibility_notes,
    notify_product_updates = excluded.notify_product_updates,
    notify_practice_reminders = excluded.notify_practice_reminders,
    updated_at = now()
`

type UpsertProfileParams struct {
	UserID                  string
	Disciplines             []string
	TargetRoles             []string
	Seniority               string
	CareerContext           string
	DefaultDurationMinutes  int32
	DefaultStyle            string
	DefaultPressure         string
	ExtendedTime            bool
	Captions                bool
	ReducedMotion           bool
	AccessibilityNotes      string
	NotifyProductUpdates    bool
	NotifyPracticeReminders bool
}

// One statement for create and update, because the row's existence is an
// implementation detail: a candidate who never saved has the empty profile,
// and their first save is not a different operation from their tenth.
func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.Exec(ctx, upsertProfile,
		arg.UserID,
		arg.Disciplines,
		arg.TargetRoles,
		arg.Seniority,
		arg.CareerContext,
		arg.DefaultDurationMinutes,
		arg.DefaultStyle,
		arg.DefaultPressure,
		arg.ExtendedTime,
		arg.Captions,
		arg.ReducedMotion,
		arg.AccessibilityNotes,
		arg.NotifyProductUpdates,
		arg.NotifyPracticeReminders,
	)
	return err
}
