// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package candidatedb

import (
	"context"
	"time"
)

const deleteProposedFacts = `-- name: DeleteProposedFacts :exec
DELETE FROM candidate.extracted_facts
WHERE document_id = $1::uuid AND status = 'proposed'
`

// The idempotency half of storing an extraction: proposals for this document
// are replaced wholesale, so a replayed StoreFacts converges instead of
// duplicating. Rows the candidate has already acted on keep their status and
// are left alone.
func (q *Queries) DeleteProposedFacts(ctx context.Context, documentID string) error {
	_, err := q.db.Exec(ctx, deleteProposedFacts, documentID)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id::text AS id, user_id::text AS user_id, kind, version, storage_key,
       media_type, size_bytes, state,
       coalesce(upload_id, '')::text AS upload_id,
       coalesce(sha256, '')::text AS sha256,
       extraction_state, created_at, stored_at, deleted_at
FROM candidate.documents
WHERE id = $1::uuid
`

type GetDocumentRow struct {
	ID              string
	UserID          string
	Kind            string
	Version         int32
	StorageKey      string
	MediaType       string
	SizeBytes       int64
	State           string
	UploadID        string
	Sha256          string
	ExtractionState string
	CreatedAt       time.Time
	StoredAt        *time.Time
	DeletedAt       *time.Time
}

func (q *Queries) GetDocument(ctx context.Context, id string) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Version,
		&i.StorageKey,
		&i.MediaType,
		&i.SizeBytes,
		&i.State,
		&i.UploadID,
		&i.Sha256,
		&i.ExtractionState,
		&i.CreatedAt,
		&i.StoredAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one

SELECT user_id::text AS user_id, disciplines, target_roles,
       coalesce(seniority, '')::text AS seniority,
       coalesce(career_context, '')::text AS career_context,
       coalesce(default_duration_minutes, 0)::integer AS default_duration_minutes,
       coalesce(default_style, '')::text AS default_style,
       coalesce(default_pressure, '')::text AS default_pressure,
       extended_time, captions, reduced_motion,
       coalesce(accessibility_notes, '')::text AS accessibility_notes,
       notify_product_updates, notify_practice_reminders,
       created_at, updated_at
FROM candidate.profiles
WHERE user_id = $1::uuid
`

type GetProfileRow struct {
	UserID                  string
	Disciplines             []string
	TargetRoles             []string
	Seniority               string
	CareerContext           string
	DefaultDurationMinutes  int32
	DefaultStyle            string
	DefaultPressure         string
	ExtendedTime            bool
	Captions                bool
	ReducedMotion           bool
	AccessibilityNotes      string
	NotifyProductUpdates    bool
	NotifyPracticeReminders bool
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

// The profile's queries. sqlc generates the Go beside this file; ADR-0010
// records why no SQL lives in Go source.
func (q *Queries) GetProfile(ctx context.Context, userID string) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i GetProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Disciplines,
		&i.TargetRoles,
		&i.Seniority,
		&i.CareerContext,
		&i.DefaultDurationMinutes,
		&i.DefaultStyle,
		&i.DefaultPressure,
		&i.ExtendedTime,
		&i.Captions,
		&i.ReducedMotion,
		&i.AccessibilityNotes,
		&i.NotifyProductUpdates,
		&i.NotifyPracticeReminders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDocument = `-- name: InsertDocument :exec
INSERT INTO candidate.documents
    (id, user_id, kind, version, storage_key, media_type, size_bytes, upload_id)
VALUES ($1::uuid, $2::uuid, $3::text,
        $4::integer, $5::text,
        $6::text, $7::bigint,
        $8::text)
`

type InsertDocumentParams struct {
	ID         string
	UserID     string
	Kind       string
	Version    int32
	StorageKey string
	MediaType  string
	SizeBytes  int64
	UploadID   string
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) error {
	_, err := q.db.Exec(ctx, insertDocument,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Version,
		arg.StorageKey,
		arg.MediaType,
		arg.SizeBytes,
		arg.UploadID,
	)
	return err
}

const insertFact = `-- name: InsertFact :exec
INSERT INTO candidate.extracted_facts
    (id, user_id, document_id, kind, value, span_start, span_end,
     confidence, extractor_version)
VALUES ($1::uuid, $2::uuid, $3::uuid,
        $4::text, $5::jsonb,
        $6::integer, $7::integer,
        $8::float8, $9::text)
`

type InsertFactParams struct {
	ID               string
	UserID           string
	DocumentID       string
	Kind             string
	Value            []byte
	SpanStart        int32
	SpanEnd          int32
	Confidence       float64
	ExtractorVersion string
}

func (q *Queries) InsertFact(ctx context.Context, arg InsertFactParams) error {
	_, err := q.db.Exec(ctx, insertFact,
		arg.ID,
		arg.UserID,
		arg.DocumentID,
		arg.Kind,
		arg.Value,
		arg.SpanStart,
		arg.SpanEnd,
		arg.Confidence,
		arg.ExtractorVersion,
	)
	return err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id::text AS id, user_id::text AS user_id, kind, version, storage_key,
       media_type, size_bytes, state,
       coalesce(upload_id, '')::text AS upload_id,
       coalesce(sha256, '')::text AS sha256,
       extraction_state, created_at, stored_at, deleted_at
FROM candidate.documents
WHERE user_id = $1::uuid AND kind = $2::text
ORDER BY version DESC
`

type ListDocumentsParams struct {
	UserID string
	Kind   string
}

type ListDocumentsRow struct {
	ID              string
	UserID          string
	Kind            string
	Version         int32
	StorageKey      string
	MediaType       string
	SizeBytes       int64
	State           string
	UploadID        string
	Sha256          string
	ExtractionState string
	CreatedAt       time.Time
	StoredAt        *time.Time
	DeletedAt       *time.Time
}

// Every version, newest first: the history PRO-02 requires, states included,
// so a stuck upload is visible beside the version that superseded it.
func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]ListDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDocuments, arg.UserID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsRow{}
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Version,
			&i.StorageKey,
			&i.MediaType,
			&i.SizeBytes,
			&i.State,
			&i.UploadID,
			&i.Sha256,
			&i.ExtractionState,
			&i.CreatedAt,
			&i.StoredAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEffectiveFacts = `-- name: ListEffectiveFacts :many
SELECT f.id::text AS id, f.document_id::text AS document_id, f.kind,
       coalesce(f.corrected_value, f.value) AS value,
       f.span_start, f.span_end, f.status, f.extractor_version
FROM candidate.extracted_facts f
WHERE f.user_id = $1::uuid AND f.status <> 'rejected'
ORDER BY f.span_start, f.span_end, f.kind
`

type ListEffectiveFactsRow struct {
	ID               string
	DocumentID       string
	Kind             string
	Value            []byte
	SpanStart        int32
	SpanEnd          int32
	Status           string
	ExtractorVersion string
}

// What downstream consumers read: the correction where one exists, the
// extraction otherwise, and no rejected facts at all. This query is the
// contract behind PRO-04's third criterion - composition reads facts through
// it, so a corrected fact is the one used from the moment it is corrected.
func (q *Queries) ListEffectiveFacts(ctx context.Context, userID string) ([]ListEffectiveFactsRow, error) {
	rows, err := q.db.Query(ctx, listEffectiveFacts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEffectiveFactsRow{}
	for rows.Next() {
		var i ListEffectiveFactsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Kind,
			&i.Value,
			&i.SpanStart,
			&i.SpanEnd,
			&i.Status,
			&i.ExtractorVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFactsByDocument = `-- name: ListFactsByDocument :many
SELECT id::text AS id, document_id::text AS document_id, kind, value,
       coalesce(corrected_value, 'null'::jsonb) AS corrected_value,
       span_start, span_end, confidence::float8 AS confidence,
       extractor_version, status, created_at, reviewed_at
FROM candidate.extracted_facts
WHERE document_id = $1::uuid
ORDER BY span_start, span_end, kind
`

type ListFactsByDocumentRow struct {
	ID               string
	DocumentID       string
	Kind             string
	Value            []byte
	CorrectedValue   []byte
	SpanStart        int32
	SpanEnd          int32
	Confidence       float64
	ExtractorVersion string
	Status           string
	CreatedAt        time.Time
	ReviewedAt       *time.Time
}

// In span order, because the facts are read beside the document they came
// from and the span is the join.
func (q *Queries) ListFactsByDocument(ctx context.Context, documentID string) ([]ListFactsByDocumentRow, error) {
	rows, err := q.db.Query(ctx, listFactsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFactsByDocumentRow{}
	for rows.Next() {
		var i ListFactsByDocumentRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Kind,
			&i.Value,
			&i.CorrectedValue,
			&i.SpanStart,
			&i.SpanEnd,
			&i.Confidence,
			&i.ExtractorVersion,
			&i.Status,
			&i.CreatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDocumentDeleted = `-- name: MarkDocumentDeleted :execrows
UPDATE candidate.documents
SET state = 'deleted', deleted_at = now()
WHERE id = $1::uuid AND state = 'stored'
`

// The row survives its object: the digest record is what a composed bundle
// pinned, and destroying it would leave a session's provenance unanswerable.
func (q *Queries) MarkDocumentDeleted(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markDocumentDeleted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDocumentFailed = `-- name: MarkDocumentFailed :execrows
UPDATE candidate.documents
SET state = 'failed', upload_id = NULL
WHERE id = $1::uuid AND state = 'uploading'
`

func (q *Queries) MarkDocumentFailed(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markDocumentFailed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDocumentStored = `-- name: MarkDocumentStored :execrows
UPDATE candidate.documents
SET state = 'stored', sha256 = $1::text,
    size_bytes = $2::bigint, stored_at = now(), upload_id = NULL,
    extraction_state = 'pending'
WHERE id = $3::uuid AND state = 'uploading'
`

type MarkDocumentStoredParams struct {
	Sha256    string
	SizeBytes int64
	ID        string
}

// Guarded on the uploading state, so completing twice - or completing an
// aborted upload - loses on rows affected rather than rewriting history.
// Storing also queues extraction: pending is set here, in the same statement
// that records the digest, so there is no stored document whose extraction
// state nobody decided.
func (q *Queries) MarkDocumentStored(ctx context.Context, arg MarkDocumentStoredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDocumentStored, arg.Sha256, arg.SizeBytes, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nextDocumentVersion = `-- name: NextDocumentVersion :one
SELECT coalesce(max(version), 0)::integer + 1 AS next_version
FROM candidate.documents
WHERE user_id = $1::uuid AND kind = $2::text
`

type NextDocumentVersionParams struct {
	UserID string
	Kind   string
}

// The next version for one person's document kind, computed under the row
// lock of the aggregate's own scope so two concurrent uploads cannot both be
// version 3. Absence is version 1.
func (q *Queries) NextDocumentVersion(ctx context.Context, arg NextDocumentVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextDocumentVersion, arg.UserID, arg.Kind)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}

const reviewFact = `-- name: ReviewFact :one
UPDATE candidate.extracted_facts
SET status = $1::text,
    corrected_value = CASE WHEN $1::text = 'corrected'
                           THEN $2::jsonb ELSE NULL END,
    reviewed_at = now()
WHERE id = $3::uuid
RETURNING id::text AS id, document_id::text AS document_id, kind, value,
       coalesce(corrected_value, 'null'::jsonb) AS corrected_value,
       span_start, span_end, confidence::float8 AS confidence,
       extractor_version, status, created_at, reviewed_at
`

type ReviewFactParams struct {
	Status         string
	CorrectedValue []byte
	ID             string
}

type ReviewFactRow struct {
	ID               string
	DocumentID       string
	Kind             string
	Value            []byte
	CorrectedValue   []byte
	SpanStart        int32
	SpanEnd          int32
	Confidence       float64
	ExtractorVersion string
	Status           string
	CreatedAt        time.Time
	ReviewedAt       *time.Time
}

// The candidate's move on one fact, in one statement. The extracted value is
// untouched by construction - only status, corrected_value and reviewed_at
// change - and the correction is cleared on any move away from corrected, so
// the CHECK that a status and its correction agree can never be argued with.
func (q *Queries) ReviewFact(ctx context.Context, arg ReviewFactParams) (ReviewFactRow, error) {
	row := q.db.QueryRow(ctx, reviewFact, arg.Status, arg.CorrectedValue, arg.ID)
	var i ReviewFactRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Kind,
		&i.Value,
		&i.CorrectedValue,
		&i.SpanStart,
		&i.SpanEnd,
		&i.Confidence,
		&i.ExtractorVersion,
		&i.Status,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const setDocumentExtractionState = `-- name: SetDocumentExtractionState :execrows
UPDATE candidate.documents
SET extraction_state = $1::text
WHERE id = $2::uuid
  AND extraction_state IN ('pending', $1::text)
`

type SetDocumentExtractionStateParams struct {
	State string
	ID    string
}

// Moves extraction to its outcome. The guard admits pending - the normal
// path - and the target state itself, so a workflow activity replayed after
// its commit lands on success rather than on a refusal it must special-case.
func (q *Queries) SetDocumentExtractionState(ctx context.Context, arg SetDocumentExtractionStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDocumentExtractionState, arg.State, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO candidate.profiles
    (user_id, disciplines, target_roles, seniority, career_context,
     default_duration_minutes, default_style, default_pressure,
     extended_time, captions, reduced_motion, accessibility_notes,
     notify_product_updates, notify_practice_reminders)
VALUES ($1::uuid, $2::text[], $3::text[],
        nullif($4::text, ''), nullif($5::text, ''),
        nullif($6::integer, 0),
        nullif($7::text, ''), nullif($8::text, ''),
        $9::boolean, $10::boolean,
        $11::boolean, nullif($12::text, ''),
        $13::boolean, $14::boolean)
ON CONFLICT (user_id) DO UPDATE SET
    disciplines = excluded.disciplines,
    target_roles = excluded.target_roles,
    seniority = excluded.seniority,
    career_context = excluded.career_context,
    default_duration_minutes = excluded.default_duration_minutes,
    default_style = excluded.default_style,
    default_pressure = excluded.default_pressure,
    extended_time = excluded.extended_time,
    captions = excluded.captions,
    reduced_motion = excluded.reduced_motion,
    accessibility_notes = excluded.accessibility_notes,
    notify_product_updates = excluded.notify_product_updates,
    notify_practice_reminders = excluded.notify_practice_reminders,
    updated_at = now()
`

type UpsertProfileParams struct {
	UserID                  string
	Disciplines             []string
	TargetRoles             []string
	Seniority               string
	CareerContext           string
	DefaultDurationMinutes  int32
	DefaultStyle            string
	DefaultPressure         string
	ExtendedTime            bool
	Captions                bool
	ReducedMotion           bool
	AccessibilityNotes      string
	NotifyProductUpdates    bool
	NotifyPracticeReminders bool
}

// One statement for create and update, because the row's existence is an
// implementation detail: a candidate who never saved has the empty profile,
// and their first save is not a different operation from their tenth.
func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.Exec(ctx, upsertProfile,
		arg.UserID,
		arg.Disciplines,
		arg.TargetRoles,
		arg.Seniority,
		arg.CareerContext,
		arg.DefaultDurationMinutes,
		arg.DefaultStyle,
		arg.DefaultPressure,
		arg.ExtendedTime,
		arg.Captions,
		arg.ReducedMotion,
		arg.AccessibilityNotes,
		arg.NotifyProductUpdates,
		arg.NotifyPracticeReminders,
	)
	return err
}
