// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package recruitingdb

import (
	"time"
)

// The unit an invitation is issued under: one role, one pinned configuration, one jurisdiction determination. Opening is the moment every pin is checked and frozen.
type RecruitingCampaign struct {
	ID              string
	TenantID        string
	Name            string
	Status          string
	RoleReference   string
	Jurisdiction    string
	DeterminationID *string
	OpenedAt        *time.Time
	ClosedAt        *time.Time
	CreatedAt       time.Time
	CreatedBy       string
}
