// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package recruitingdb

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitationByToken = `-- name: AcceptInvitationByToken :one
UPDATE recruiting.invitation
SET outcome = 'accepted', outcome_at = now(), accepted_candidate = $1::uuid
WHERE token_hash = $2::text AND outcome IS NULL AND expires_at > now()
RETURNING id, tenant_id, campaign_id, recipient, email_id, issued_by,
          issued_at, expires_at, outcome, outcome_at
`

type AcceptInvitationByTokenParams struct {
	Candidate string
	TokenHash string
}

type AcceptInvitationByTokenRow struct {
	ID         string
	TenantID   string
	CampaignID string
	Recipient  string
	EmailID    string
	IssuedBy   string
	IssuedAt   time.Time
	ExpiresAt  time.Time
	Outcome    pgtype.Text
	OutcomeAt  *time.Time
}

// Accept, single-use and not past expiry. The guard on a null outcome makes the
// accept a one-winner race: two clicks on one link produce one accepted
// interview and one refusal, not two. The expires_at guard refuses a link that
// lapsed while it sat in an inbox; the caller reads the current state first and
// tells the candidate which of expired, revoked or already-answered it was, so
// this returning no row is an outcome to explain rather than an error.
func (q *Queries) AcceptInvitationByToken(ctx context.Context, arg AcceptInvitationByTokenParams) (AcceptInvitationByTokenRow, error) {
	row := q.db.QueryRow(ctx, acceptInvitationByToken, arg.Candidate, arg.TokenHash)
	var i AcceptInvitationByTokenRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CampaignID,
		&i.Recipient,
		&i.EmailID,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Outcome,
		&i.OutcomeAt,
	)
	return i, err
}

const acceptancesFor = `-- name: AcceptancesFor :many
SELECT id, campaign_id, candidate_id, disclosure_digest, disclosure_version, accepted_at
FROM recruiting.disclosure_acceptance
WHERE campaign_id = $1 AND candidate_id = $2
ORDER BY accepted_at DESC
`

type AcceptancesForParams struct {
	CampaignID  string
	CandidateID string
}

type AcceptancesForRow struct {
	ID                string
	CampaignID        string
	CandidateID       string
	DisclosureDigest  string
	DisclosureVersion string
	AcceptedAt        time.Time
}

// Every acceptance, newest first. All of them rather than the latest, because
// "what had this person been told when they sat the interview" is a question
// about a moment, and answering it needs the history.
func (q *Queries) AcceptancesFor(ctx context.Context, arg AcceptancesForParams) ([]AcceptancesForRow, error) {
	rows, err := q.db.Query(ctx, acceptancesFor, arg.CampaignID, arg.CandidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcceptancesForRow{}
	for rows.Next() {
		var i AcceptancesForRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.CandidateID,
			&i.DisclosureDigest,
			&i.DisclosureVersion,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const acceptedInvitationForCandidate = `-- name: AcceptedInvitationForCandidate :one
SELECT id, tenant_id, campaign_id, recipient, email_id, issued_by,
       issued_at, expires_at, outcome, outcome_at
FROM recruiting.invitation
WHERE campaign_id = $1 AND accepted_candidate = $2 AND outcome = 'accepted'
`

type AcceptedInvitationForCandidateParams struct {
	CampaignID        string
	AcceptedCandidate *string
}

type AcceptedInvitationForCandidateRow struct {
	ID         string
	TenantID   string
	CampaignID string
	Recipient  string
	EmailID    string
	IssuedBy   string
	IssuedAt   time.Time
	ExpiresAt  time.Time
	Outcome    pgtype.Text
	OutcomeAt  *time.Time
}

// The invitation this candidate accepted to this campaign, read as the
// candidate themselves through the owner policy 0059 added. It is how the
// screening session creation path proves authority: a candidate who did not
// accept an invitation to the campaign finds no row here and cannot start one.
func (q *Queries) AcceptedInvitationForCandidate(ctx context.Context, arg AcceptedInvitationForCandidateParams) (AcceptedInvitationForCandidateRow, error) {
	row := q.db.QueryRow(ctx, acceptedInvitationForCandidate, arg.CampaignID, arg.AcceptedCandidate)
	var i AcceptedInvitationForCandidateRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CampaignID,
		&i.Recipient,
		&i.EmailID,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Outcome,
		&i.OutcomeAt,
	)
	return i, err
}

const accommodationRequestsFor = `-- name: AccommodationRequestsFor :many
SELECT id, campaign_id, candidate_id, adjustment, requested_at
FROM recruiting.accommodation_request
WHERE campaign_id = $1 AND candidate_id = $2
ORDER BY requested_at DESC
`

type AccommodationRequestsForParams struct {
	CampaignID  string
	CandidateID string
}

type AccommodationRequestsForRow struct {
	ID          string
	CampaignID  string
	CandidateID string
	Adjustment  string
	RequestedAt time.Time
}

// Every request this candidate made on this campaign, newest first. The
// standing decision is read per request through StandingAccommodationDecision
// rather than joined here: a request nobody has answered has no decision row,
// and "no row" is an answer this store gives a specific meaning to
// ("requested") rather than a null it has to reinterpret.
func (q *Queries) AccommodationRequestsFor(ctx context.Context, arg AccommodationRequestsForParams) ([]AccommodationRequestsForRow, error) {
	rows, err := q.db.Query(ctx, accommodationRequestsFor, arg.CampaignID, arg.CandidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccommodationRequestsForRow{}
	for rows.Next() {
		var i AccommodationRequestsForRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.CandidateID,
			&i.Adjustment,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accommodationsForSession = `-- name: AccommodationsForSession :many
SELECT r.adjustment, f.request_id, f.session_id, f.fulfilled_at
FROM recruiting.accommodation_fulfilment f
JOIN recruiting.accommodation_request r ON r.id = f.request_id
WHERE f.session_id = $1
ORDER BY f.fulfilled_at
`

type AccommodationsForSessionRow struct {
	Adjustment  string
	RequestID   string
	SessionID   string
	FulfilledAt time.Time
}

// What was actually applied to one session: the read the interview runner's
// port will serve when the composition root wires it. This is the record of
// an accommodation being exercised, and it lives here so that evaluation,
// which cannot name this schema, can never make a signal of it.
func (q *Queries) AccommodationsForSession(ctx context.Context, sessionID string) ([]AccommodationsForSessionRow, error) {
	rows, err := q.db.Query(ctx, accommodationsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccommodationsForSessionRow{}
	for rows.Next() {
		var i AccommodationsForSessionRow
		if err := rows.Scan(
			&i.Adjustment,
			&i.RequestID,
			&i.SessionID,
			&i.FulfilledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assignReReview = `-- name: AssignReReview :execrows
UPDATE recruiting.re_review
SET assigned_to = $1::uuid
WHERE id = $2::uuid
  AND campaign_id = $3::uuid
  AND outcome IS NULL
`

type AssignReReviewParams struct {
	AssignedTo string
	ID         string
	CampaignID string
}

// Assignment while open. The independence CHECK refuses the original
// reviewer at the schema; zero rows means no such open appeal on the
// campaign, which the store names.
func (q *Queries) AssignReReview(ctx context.Context, arg AssignReReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignReReview, arg.AssignedTo, arg.ID, arg.CampaignID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const authorizeReInvitation = `-- name: AuthorizeReInvitation :one
INSERT INTO recruiting.re_invitation
    (id, campaign_id, tenant_id, candidate_id, reason, decided_by, interrupted_session)
VALUES ($1, $2, $3, $4, $5, $6, nullif($7::text, '')::uuid)
RETURNING id, campaign_id, candidate_id, reason, decided_by, interrupted_session, consumed_session, created_at
`

type AuthorizeReInvitationParams struct {
	ID                 string
	CampaignID         string
	TenantID           string
	CandidateID        string
	Reason             string
	DecidedBy          string
	InterruptedSession string
}

type AuthorizeReInvitationRow struct {
	ID                 string
	CampaignID         string
	CandidateID        string
	Reason             string
	DecidedBy          string
	InterruptedSession *string
	ConsumedSession    *string
	CreatedAt          time.Time
}

// Records a recruiter's decision to let a candidate take one further session.
// The reason and decider are required by the table; this writes them.
func (q *Queries) AuthorizeReInvitation(ctx context.Context, arg AuthorizeReInvitationParams) (AuthorizeReInvitationRow, error) {
	row := q.db.QueryRow(ctx, authorizeReInvitation,
		arg.ID,
		arg.CampaignID,
		arg.TenantID,
		arg.CandidateID,
		arg.Reason,
		arg.DecidedBy,
		arg.InterruptedSession,
	)
	var i AuthorizeReInvitationRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CandidateID,
		&i.Reason,
		&i.DecidedBy,
		&i.InterruptedSession,
		&i.ConsumedSession,
		&i.CreatedAt,
	)
	return i, err
}

const campaignByID = `-- name: CampaignByID :one
SELECT id, tenant_id, name, status, role_reference, jurisdiction,
       determination_id, opened_at, closed_at, created_at, created_by
FROM recruiting.campaign
WHERE id = $1
`

// One campaign by id, tenant-scoped by the row-level security policy. Unlike
// CampaignsForRecruiter this carries no recruiter join, so it is not a way to
// read a campaign a recruiter is not on: it exists for the candidate
// acceptance path, which is authorised by a valid invitation token rather than
// by campaign membership, and needs the role the invitation is for. A recruiter
// surface must keep using the join; this is not that.
func (q *Queries) CampaignByID(ctx context.Context, id string) (RecruitingCampaign, error) {
	row := q.db.QueryRow(ctx, campaignByID, id)
	var i RecruitingCampaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.RoleReference,
		&i.Jurisdiction,
		&i.DeterminationID,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const campaignsForRecruiter = `-- name: CampaignsForRecruiter :many
SELECT c.id, c.tenant_id, c.name, c.status, c.role_reference, c.jurisdiction,
       c.determination_id, c.opened_at, c.closed_at, c.created_at, c.created_by
FROM recruiting.campaign c
JOIN recruiting.campaign_recruiter r ON r.campaign_id = c.id
WHERE r.user_id = $1
ORDER BY c.created_at DESC
`

// Scoped by the join rather than by a filter the caller supplies, so a caller
// that forgets to filter gets nothing rather than everything.
func (q *Queries) CampaignsForRecruiter(ctx context.Context, userID string) ([]RecruitingCampaign, error) {
	rows, err := q.db.Query(ctx, campaignsForRecruiter, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecruitingCampaign{}
	for rows.Next() {
		var i RecruitingCampaign
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Status,
			&i.RoleReference,
			&i.Jurisdiction,
			&i.DeterminationID,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const campaignsUsingArtifact = `-- name: CampaignsUsingArtifact :many
SELECT c.name
FROM recruiting.campaign c
JOIN recruiting.campaign_pin p ON p.campaign_id = c.id
WHERE c.status = 'open' AND p.reference = $1::text
ORDER BY c.name
`

// The open campaigns that pinned a given artifact reference.
//
// By reference rather than by digest, which is the opposite of how a campaign
// identifies its configuration and is deliberate. The question this answers is
// the author's: "may I remove this rubric", and they think in references. A
// digest match would answer only for the exact version pinned and would let
// the draft behind a running campaign be discarded.
//
// Open only. A closed campaign runs nothing and issues nothing, so it does not
// block an author from tidying up; what it already evaluated is pinned by
// digest and stays resolvable either way.
//
// Tenant scoping comes from the row-level security policy rather than a
// predicate here, so a caller who forgets to scope gets nothing rather than
// another workspace's campaign names.
func (q *Queries) CampaignsUsingArtifact(ctx context.Context, reference string) ([]string, error) {
	rows, err := q.db.Query(ctx, campaignsUsingArtifact, reference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimReInvitation = `-- name: ClaimReInvitation :one
UPDATE recruiting.re_invitation
SET consumed_session = $1::uuid
WHERE id = (
    SELECT id FROM recruiting.re_invitation
    WHERE campaign_id = $2::uuid
      AND candidate_id = $3::uuid
      AND consumed_session IS NULL
    ORDER BY created_at
    LIMIT 1
)
RETURNING id, campaign_id, candidate_id, consumed_session
`

type ClaimReInvitationParams struct {
	SessionID   string
	CampaignID  string
	CandidateID string
}

type ClaimReInvitationRow struct {
	ID              string
	CampaignID      string
	CandidateID     string
	ConsumedSession *string
}

// The candidate claims their oldest unclaimed re-invitation, binding it to the
// new session, so one authorization admits exactly one further attempt. Run as
// the candidate through the claim policy; returns nothing when they hold none.
func (q *Queries) ClaimReInvitation(ctx context.Context, arg ClaimReInvitationParams) (ClaimReInvitationRow, error) {
	row := q.db.QueryRow(ctx, claimReInvitation, arg.SessionID, arg.CampaignID, arg.CandidateID)
	var i ClaimReInvitationRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CandidateID,
		&i.ConsumedSession,
	)
	return i, err
}

const closeCampaign = `-- name: CloseCampaign :one
UPDATE recruiting.campaign
SET status = 'closed', closed_at = now()
WHERE id = $1 AND status = 'open'
RETURNING id, tenant_id, name, status, role_reference, jurisdiction,
          determination_id, opened_at, closed_at, created_at, created_by
`

func (q *Queries) CloseCampaign(ctx context.Context, id string) (RecruitingCampaign, error) {
	row := q.db.QueryRow(ctx, closeCampaign, id)
	var i RecruitingCampaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.RoleReference,
		&i.Jurisdiction,
		&i.DeterminationID,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const correctRequirement = `-- name: CorrectRequirement :one
UPDATE recruiting.campaign_requirement
SET text = COALESCE(NULLIF($1::text, ''), text), status = $2::text
WHERE id = $3::uuid AND campaign_id = $4::uuid
RETURNING id, campaign_id, text, span_start, span_end, status, extraction_version, created_at
`

type CorrectRequirementParams struct {
	Text       string
	Status     string
	ID         string
	CampaignID string
}

type CorrectRequirementRow struct {
	ID                string
	CampaignID        string
	Text              string
	SpanStart         int32
	SpanEnd           int32
	Status            string
	ExtractionVersion string
	CreatedAt         time.Time
}

// Correct or reject one requirement on one campaign. Scoped by campaign_id so a
// recruiter admitted to one campaign cannot rewrite another's requirement by id;
// the freeze trigger refuses it once the campaign has opened.
func (q *Queries) CorrectRequirement(ctx context.Context, arg CorrectRequirementParams) (CorrectRequirementRow, error) {
	row := q.db.QueryRow(ctx, correctRequirement,
		arg.Text,
		arg.Status,
		arg.ID,
		arg.CampaignID,
	)
	var i CorrectRequirementRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Text,
		&i.SpanStart,
		&i.SpanEnd,
		&i.Status,
		&i.ExtractionVersion,
		&i.CreatedAt,
	)
	return i, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO recruiting.campaign (id, tenant_id, name, role_reference, jurisdiction, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, status, role_reference, jurisdiction,
          determination_id, opened_at, closed_at, created_at, created_by
`

type CreateCampaignParams struct {
	ID            string
	TenantID      string
	Name          string
	RoleReference string
	Jurisdiction  string
	CreatedBy     string
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (RecruitingCampaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.RoleReference,
		arg.Jurisdiction,
		arg.CreatedBy,
	)
	var i RecruitingCampaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.RoleReference,
		&i.Jurisdiction,
		&i.DeterminationID,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const declineInvitationByToken = `-- name: DeclineInvitationByToken :one
UPDATE recruiting.invitation
SET outcome = 'declined', outcome_at = now()
WHERE token_hash = $1 AND outcome IS NULL AND expires_at > now()
RETURNING id, tenant_id, campaign_id, recipient, email_id, issued_by,
          issued_at, expires_at, outcome, outcome_at
`

type DeclineInvitationByTokenRow struct {
	ID         string
	TenantID   string
	CampaignID string
	Recipient  string
	EmailID    string
	IssuedBy   string
	IssuedAt   time.Time
	ExpiresAt  time.Time
	Outcome    pgtype.Text
	OutcomeAt  *time.Time
}

// Decline, the candidate's first-class no. Guarded on a null outcome like
// accept, so declining a link already answered or revoked changes nothing and
// returns nothing. Declining is recorded, never penalised: the row simply ends
// as declined, and nothing downstream treats that differently from never having
// been asked.
func (q *Queries) DeclineInvitationByToken(ctx context.Context, tokenHash string) (DeclineInvitationByTokenRow, error) {
	row := q.db.QueryRow(ctx, declineInvitationByToken, tokenHash)
	var i DeclineInvitationByTokenRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CampaignID,
		&i.Recipient,
		&i.EmailID,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Outcome,
		&i.OutcomeAt,
	)
	return i, err
}

const deleteRequirementsForCampaign = `-- name: DeleteRequirementsForCampaign :exec
DELETE FROM recruiting.campaign_requirement WHERE campaign_id = $1
`

// Clears a draft campaign's requirements before a fresh extraction replaces
// them. The freeze trigger refuses this once the campaign has opened, so a
// running campaign's requirements cannot be cleared out from under it.
func (q *Queries) DeleteRequirementsForCampaign(ctx context.Context, campaignID string) error {
	_, err := q.db.Exec(ctx, deleteRequirementsForCampaign, campaignID)
	return err
}

const determinationByID = `-- name: DeterminationByID :one
SELECT id, jurisdiction, version, result_disclosure, appeal_status, approver, approved_at
FROM recruiting.jurisdiction_determination
WHERE id = $1
`

type DeterminationByIDRow struct {
	ID               string
	Jurisdiction     string
	Version          int32
	ResultDisclosure string
	AppealStatus     string
	Approver         string
	ApprovedAt       time.Time
}

func (q *Queries) DeterminationByID(ctx context.Context, id string) (DeterminationByIDRow, error) {
	row := q.db.QueryRow(ctx, determinationByID, id)
	var i DeterminationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Jurisdiction,
		&i.Version,
		&i.ResultDisclosure,
		&i.AppealStatus,
		&i.Approver,
		&i.ApprovedAt,
	)
	return i, err
}

const grantCampaignAccess = `-- name: GrantCampaignAccess :exec
INSERT INTO recruiting.campaign_recruiter (campaign_id, tenant_id, user_id, granted_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (campaign_id, user_id) DO NOTHING
`

type GrantCampaignAccessParams struct {
	CampaignID string
	TenantID   string
	UserID     string
	GrantedBy  string
}

func (q *Queries) GrantCampaignAccess(ctx context.Context, arg GrantCampaignAccessParams) error {
	_, err := q.db.Exec(ctx, grantCampaignAccess,
		arg.CampaignID,
		arg.TenantID,
		arg.UserID,
		arg.GrantedBy,
	)
	return err
}

const insertRequirement = `-- name: InsertRequirement :one
INSERT INTO recruiting.campaign_requirement
    (id, campaign_id, tenant_id, text, span_start, span_end, extraction_version)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, campaign_id, text, span_start, span_end, status, extraction_version, created_at
`

type InsertRequirementParams struct {
	ID                string
	CampaignID        string
	TenantID          string
	Text              string
	SpanStart         int32
	SpanEnd           int32
	ExtractionVersion string
}

type InsertRequirementRow struct {
	ID                string
	CampaignID        string
	Text              string
	SpanStart         int32
	SpanEnd           int32
	Status            string
	ExtractionVersion string
	CreatedAt         time.Time
}

func (q *Queries) InsertRequirement(ctx context.Context, arg InsertRequirementParams) (InsertRequirementRow, error) {
	row := q.db.QueryRow(ctx, insertRequirement,
		arg.ID,
		arg.CampaignID,
		arg.TenantID,
		arg.Text,
		arg.SpanStart,
		arg.SpanEnd,
		arg.ExtractionVersion,
	)
	var i InsertRequirementRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Text,
		&i.SpanStart,
		&i.SpanEnd,
		&i.Status,
		&i.ExtractionVersion,
		&i.CreatedAt,
	)
	return i, err
}

const invitationByID = `-- name: InvitationByID :one
SELECT id, tenant_id, campaign_id, recipient, email_id, issued_by,
       issued_at, expires_at, outcome, outcome_at
FROM recruiting.invitation
WHERE id = $1 AND campaign_id = $2
`

type InvitationByIDParams struct {
	ID         string
	CampaignID string
}

type InvitationByIDRow struct {
	ID         string
	TenantID   string
	CampaignID string
	Recipient  string
	EmailID    string
	IssuedBy   string
	IssuedAt   time.Time
	ExpiresAt  time.Time
	Outcome    pgtype.Text
	OutcomeAt  *time.Time
}

// One invitation on one campaign, for the resend path that needs its recipient
// and its outcome before deciding whether a fresh link may be sent. Scoped by
// campaign_id for the same reason revoke is: a recruiter on one campaign cannot
// reach another's invitation by id. Tenant scoping is the policy's.
func (q *Queries) InvitationByID(ctx context.Context, arg InvitationByIDParams) (InvitationByIDRow, error) {
	row := q.db.QueryRow(ctx, invitationByID, arg.ID, arg.CampaignID)
	var i InvitationByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CampaignID,
		&i.Recipient,
		&i.EmailID,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Outcome,
		&i.OutcomeAt,
	)
	return i, err
}

const invitationsForCampaign = `-- name: InvitationsForCampaign :many
SELECT id, tenant_id, campaign_id, recipient, email_id, issued_by,
       issued_at, expires_at, outcome, outcome_at,
       COALESCE(accepted_candidate::text, '')::text AS accepted_candidate
FROM recruiting.invitation
WHERE campaign_id = $1
ORDER BY issued_at DESC
`

type InvitationsForCampaignRow struct {
	ID                string
	TenantID          string
	CampaignID        string
	Recipient         string
	EmailID           string
	IssuedBy          string
	IssuedAt          time.Time
	ExpiresAt         time.Time
	Outcome           pgtype.Text
	OutcomeAt         *time.Time
	AcceptedCandidate string
}

// The recruiter's roster for one campaign, newest first. email_id rides along
// so cmd can join delivery status from notification, which this context does
// not read, and accepted_candidate rides along so cmd can join the candidate's
// interview from the interview context, which this context does not read
// either. Tenant scoping is the policy's.
func (q *Queries) InvitationsForCampaign(ctx context.Context, campaignID string) ([]InvitationsForCampaignRow, error) {
	rows, err := q.db.Query(ctx, invitationsForCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvitationsForCampaignRow{}
	for rows.Next() {
		var i InvitationsForCampaignRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CampaignID,
			&i.Recipient,
			&i.EmailID,
			&i.IssuedBy,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.Outcome,
			&i.OutcomeAt,
			&i.AcceptedCandidate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const issueInvitation = `-- name: IssueInvitation :one
INSERT INTO recruiting.invitation
    (id, tenant_id, campaign_id, recipient, token_hash, email_id, issued_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, campaign_id, recipient, email_id, issued_by,
          issued_at, expires_at, outcome, outcome_at
`

type IssueInvitationParams struct {
	ID         string
	TenantID   string
	CampaignID string
	Recipient  string
	TokenHash  string
	EmailID    string
	IssuedBy   string
	ExpiresAt  time.Time
}

type IssueInvitationRow struct {
	ID         string
	TenantID   string
	CampaignID string
	Recipient  string
	EmailID    string
	IssuedBy   string
	IssuedAt   time.Time
	ExpiresAt  time.Time
	Outcome    pgtype.Text
	OutcomeAt  *time.Time
}

// Store one invitation. Only the hash reaches the table; the plaintext was
// handed to the email in the same transaction and exists nowhere else. Tenant
// scoping is the policy's, so an unscoped caller inserts nothing it can then
// read back.
func (q *Queries) IssueInvitation(ctx context.Context, arg IssueInvitationParams) (IssueInvitationRow, error) {
	row := q.db.QueryRow(ctx, issueInvitation,
		arg.ID,
		arg.TenantID,
		arg.CampaignID,
		arg.Recipient,
		arg.TokenHash,
		arg.EmailID,
		arg.IssuedBy,
		arg.ExpiresAt,
	)
	var i IssueInvitationRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CampaignID,
		&i.Recipient,
		&i.EmailID,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Outcome,
		&i.OutcomeAt,
	)
	return i, err
}

const jobContextFor = `-- name: JobContextFor :one
SELECT campaign_id, source_text, extraction_version, submitted_at
FROM recruiting.job_context
WHERE campaign_id = $1
`

type JobContextForRow struct {
	CampaignID        string
	SourceText        string
	ExtractionVersion string
	SubmittedAt       time.Time
}

func (q *Queries) JobContextFor(ctx context.Context, campaignID string) (JobContextForRow, error) {
	row := q.db.QueryRow(ctx, jobContextFor, campaignID)
	var i JobContextForRow
	err := row.Scan(
		&i.CampaignID,
		&i.SourceText,
		&i.ExtractionVersion,
		&i.SubmittedAt,
	)
	return i, err
}

const latestDeterminationFor = `-- name: LatestDeterminationFor :one
SELECT id, jurisdiction, version, result_disclosure, appeal_status, approver, approved_at
FROM recruiting.jurisdiction_determination
WHERE jurisdiction = $1
ORDER BY version DESC
LIMIT 1
`

type LatestDeterminationForRow struct {
	ID               string
	Jurisdiction     string
	Version          int32
	ResultDisclosure string
	AppealStatus     string
	Approver         string
	ApprovedAt       time.Time
}

// The current determination for a jurisdiction. Absence is the answer that
// matters: ADR-0020 makes a missing determination a refusal to open, not a
// permissive default.
func (q *Queries) LatestDeterminationFor(ctx context.Context, jurisdiction string) (LatestDeterminationForRow, error) {
	row := q.db.QueryRow(ctx, latestDeterminationFor, jurisdiction)
	var i LatestDeterminationForRow
	err := row.Scan(
		&i.ID,
		&i.Jurisdiction,
		&i.Version,
		&i.ResultDisclosure,
		&i.AppealStatus,
		&i.Approver,
		&i.ApprovedAt,
	)
	return i, err
}

const latestReviewDecision = `-- name: LatestReviewDecision :one

SELECT id, session_id, decided_by, decision, reason, evaluation_id,
       result_digest, rubric_digest, overrides, created_at
FROM recruiting.review_decision
WHERE session_id = $1::uuid
  AND campaign_id = $2::uuid
ORDER BY created_at DESC
LIMIT 1
`

type LatestReviewDecisionParams struct {
	SessionID  string
	CampaignID string
}

type LatestReviewDecisionRow struct {
	ID           string
	SessionID    string
	DecidedBy    string
	Decision     string
	Reason       string
	EvaluationID string
	ResultDigest string
	RubricDigest string
	Overrides    []byte
	CreatedAt    time.Time
}

// ── REV-06: re-review, the appeal against a recorded decision.
// The decision an appeal is raised against: the newest on the session.
func (q *Queries) LatestReviewDecision(ctx context.Context, arg LatestReviewDecisionParams) (LatestReviewDecisionRow, error) {
	row := q.db.QueryRow(ctx, latestReviewDecision, arg.SessionID, arg.CampaignID)
	var i LatestReviewDecisionRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DecidedBy,
		&i.Decision,
		&i.Reason,
		&i.EvaluationID,
		&i.ResultDigest,
		&i.RubricDigest,
		&i.Overrides,
		&i.CreatedAt,
	)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, tenant_id, name, status, role_reference, jurisdiction,
       determination_id, opened_at, closed_at, created_at, created_by
FROM recruiting.campaign
ORDER BY created_at DESC
`

// Every campaign in the tenant, newest first.
//
// Deliberately not joined to campaign_recruiter: campaign.read is unscoped in
// the catalogue precisely so a recruiter can see which campaigns exist before
// being assigned to one. What stays behind the join is everything about a
// particular campaign. Tenant scoping is the row-level security policy's, so a
// caller who forgets to scope gets nothing rather than another workspace's
// roster of roles.
func (q *Queries) ListCampaigns(ctx context.Context) ([]RecruitingCampaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecruitingCampaign{}
	for rows.Next() {
		var i RecruitingCampaign
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Status,
			&i.RoleReference,
			&i.Jurisdiction,
			&i.DeterminationID,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openCampaign = `-- name: OpenCampaign :one
UPDATE recruiting.campaign
SET status = 'open', determination_id = $2, opened_at = now()
WHERE id = $1 AND status = 'draft'
RETURNING id, tenant_id, name, status, role_reference, jurisdiction,
          determination_id, opened_at, closed_at, created_at, created_by
`

type OpenCampaignParams struct {
	ID              string
	DeterminationID *string
}

// Opening is a guarded transition, not a field update. The WHERE clause carries
// the guard so that two concurrent opens cannot both succeed: the second finds
// no draft row and gets no result, rather than overwriting the first one's
// determination.
func (q *Queries) OpenCampaign(ctx context.Context, arg OpenCampaignParams) (RecruitingCampaign, error) {
	row := q.db.QueryRow(ctx, openCampaign, arg.ID, arg.DeterminationID)
	var i RecruitingCampaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.RoleReference,
		&i.Jurisdiction,
		&i.DeterminationID,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const pinArtifact = `-- name: PinArtifact :exec
INSERT INTO recruiting.campaign_pin
    (campaign_id, tenant_id, artifact_type, artifact_id, digest, reference, version)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type PinArtifactParams struct {
	CampaignID   string
	TenantID     string
	ArtifactType string
	ArtifactID   string
	Digest       string
	Reference    string
	Version      string
}

func (q *Queries) PinArtifact(ctx context.Context, arg PinArtifactParams) error {
	_, err := q.db.Exec(ctx, pinArtifact,
		arg.CampaignID,
		arg.TenantID,
		arg.ArtifactType,
		arg.ArtifactID,
		arg.Digest,
		arg.Reference,
		arg.Version,
	)
	return err
}

const pinsForCampaign = `-- name: PinsForCampaign :many
SELECT campaign_id, artifact_type, artifact_id, digest, reference, version, pinned_at
FROM recruiting.campaign_pin
WHERE campaign_id = $1
ORDER BY artifact_type
`

type PinsForCampaignRow struct {
	CampaignID   string
	ArtifactType string
	ArtifactID   string
	Digest       string
	Reference    string
	Version      string
	PinnedAt     time.Time
}

func (q *Queries) PinsForCampaign(ctx context.Context, campaignID string) ([]PinsForCampaignRow, error) {
	rows, err := q.db.Query(ctx, pinsForCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PinsForCampaignRow{}
	for rows.Next() {
		var i PinsForCampaignRow
		if err := rows.Scan(
			&i.CampaignID,
			&i.ArtifactType,
			&i.ArtifactID,
			&i.Digest,
			&i.Reference,
			&i.Version,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const raiseReReview = `-- name: RaiseReReview :one
INSERT INTO recruiting.re_review
    (id, campaign_id, tenant_id, session_id, requested_by, reason,
     appealed_decision, original_reviewer, evaluation_id, result_digest,
     rubric_digest, bundle_digest, due_at)
VALUES ($1::uuid, $2::uuid, $3::uuid,
        $4::uuid, $5::uuid, $6::text,
        $7::uuid, $8::uuid,
        $9::uuid, $10::text,
        $11::text, $12::text,
        $13::timestamptz)
RETURNING id, session_id, requested_by, reason, appealed_decision,
          original_reviewer, evaluation_id, result_digest, rubric_digest,
          bundle_digest, assigned_to, raised_at, due_at, outcome,
          outcome_rationale, candidate_disclosure, resolved_by, resolved_at
`

type RaiseReReviewParams struct {
	ID               string
	CampaignID       string
	TenantID         string
	SessionID        string
	RequestedBy      string
	Reason           string
	AppealedDecision string
	OriginalReviewer string
	EvaluationID     string
	ResultDigest     string
	RubricDigest     string
	BundleDigest     string
	DueAt            time.Time
}

type RaiseReReviewRow struct {
	ID                  string
	SessionID           string
	RequestedBy         string
	Reason              string
	AppealedDecision    string
	OriginalReviewer    string
	EvaluationID        string
	ResultDigest        string
	RubricDigest        string
	BundleDigest        string
	AssignedTo          *string
	RaisedAt            time.Time
	DueAt               time.Time
	Outcome             pgtype.Text
	OutcomeRationale    pgtype.Text
	CandidateDisclosure pgtype.Text
	ResolvedBy          *string
	ResolvedAt          *time.Time
}

func (q *Queries) RaiseReReview(ctx context.Context, arg RaiseReReviewParams) (RaiseReReviewRow, error) {
	row := q.db.QueryRow(ctx, raiseReReview,
		arg.ID,
		arg.CampaignID,
		arg.TenantID,
		arg.SessionID,
		arg.RequestedBy,
		arg.Reason,
		arg.AppealedDecision,
		arg.OriginalReviewer,
		arg.EvaluationID,
		arg.ResultDigest,
		arg.RubricDigest,
		arg.BundleDigest,
		arg.DueAt,
	)
	var i RaiseReReviewRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RequestedBy,
		&i.Reason,
		&i.AppealedDecision,
		&i.OriginalReviewer,
		&i.EvaluationID,
		&i.ResultDigest,
		&i.RubricDigest,
		&i.BundleDigest,
		&i.AssignedTo,
		&i.RaisedAt,
		&i.DueAt,
		&i.Outcome,
		&i.OutcomeRationale,
		&i.CandidateDisclosure,
		&i.ResolvedBy,
		&i.ResolvedAt,
	)
	return i, err
}

const reInvitationsForCandidate = `-- name: ReInvitationsForCandidate :many
SELECT id, campaign_id, candidate_id, reason, decided_by, interrupted_session, consumed_session, created_at
FROM recruiting.re_invitation
WHERE campaign_id = $1 AND candidate_id = $2
ORDER BY created_at
`

type ReInvitationsForCandidateParams struct {
	CampaignID  string
	CandidateID string
}

type ReInvitationsForCandidateRow struct {
	ID                 string
	CampaignID         string
	CandidateID        string
	Reason             string
	DecidedBy          string
	InterruptedSession *string
	ConsumedSession    *string
	CreatedAt          time.Time
}

// The re-invitations a candidate holds on a campaign, for the recruiter's
// audit. Tenant scoping is the policy's.
func (q *Queries) ReInvitationsForCandidate(ctx context.Context, arg ReInvitationsForCandidateParams) ([]ReInvitationsForCandidateRow, error) {
	rows, err := q.db.Query(ctx, reInvitationsForCandidate, arg.CampaignID, arg.CandidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReInvitationsForCandidateRow{}
	for rows.Next() {
		var i ReInvitationsForCandidateRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.CandidateID,
			&i.Reason,
			&i.DecidedBy,
			&i.InterruptedSession,
			&i.ConsumedSession,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reReviewByID = `-- name: ReReviewByID :one
SELECT id, session_id, requested_by, reason, appealed_decision,
       original_reviewer, evaluation_id, result_digest, rubric_digest,
       bundle_digest, assigned_to, raised_at, due_at, outcome,
       outcome_rationale, candidate_disclosure, resolved_by, resolved_at
FROM recruiting.re_review
WHERE id = $1::uuid AND campaign_id = $2::uuid
`

type ReReviewByIDParams struct {
	ID         string
	CampaignID string
}

type ReReviewByIDRow struct {
	ID                  string
	SessionID           string
	RequestedBy         string
	Reason              string
	AppealedDecision    string
	OriginalReviewer    string
	EvaluationID        string
	ResultDigest        string
	RubricDigest        string
	BundleDigest        string
	AssignedTo          *string
	RaisedAt            time.Time
	DueAt               time.Time
	Outcome             pgtype.Text
	OutcomeRationale    pgtype.Text
	CandidateDisclosure pgtype.Text
	ResolvedBy          *string
	ResolvedAt          *time.Time
}

func (q *Queries) ReReviewByID(ctx context.Context, arg ReReviewByIDParams) (ReReviewByIDRow, error) {
	row := q.db.QueryRow(ctx, reReviewByID, arg.ID, arg.CampaignID)
	var i ReReviewByIDRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RequestedBy,
		&i.Reason,
		&i.AppealedDecision,
		&i.OriginalReviewer,
		&i.EvaluationID,
		&i.ResultDigest,
		&i.RubricDigest,
		&i.BundleDigest,
		&i.AssignedTo,
		&i.RaisedAt,
		&i.DueAt,
		&i.Outcome,
		&i.OutcomeRationale,
		&i.CandidateDisclosure,
		&i.ResolvedBy,
		&i.ResolvedAt,
	)
	return i, err
}

const reReviewsForSession = `-- name: ReReviewsForSession :many
SELECT id, session_id, requested_by, reason, appealed_decision,
       original_reviewer, evaluation_id, result_digest, rubric_digest,
       bundle_digest, assigned_to, raised_at, due_at, outcome,
       outcome_rationale, candidate_disclosure, resolved_by, resolved_at
FROM recruiting.re_review
WHERE session_id = $1::uuid
  AND campaign_id = $2::uuid
ORDER BY raised_at
`

type ReReviewsForSessionParams struct {
	SessionID  string
	CampaignID string
}

type ReReviewsForSessionRow struct {
	ID                  string
	SessionID           string
	RequestedBy         string
	Reason              string
	AppealedDecision    string
	OriginalReviewer    string
	EvaluationID        string
	ResultDigest        string
	RubricDigest        string
	BundleDigest        string
	AssignedTo          *string
	RaisedAt            time.Time
	DueAt               time.Time
	Outcome             pgtype.Text
	OutcomeRationale    pgtype.Text
	CandidateDisclosure pgtype.Text
	ResolvedBy          *string
	ResolvedAt          *time.Time
}

func (q *Queries) ReReviewsForSession(ctx context.Context, arg ReReviewsForSessionParams) ([]ReReviewsForSessionRow, error) {
	rows, err := q.db.Query(ctx, reReviewsForSession, arg.SessionID, arg.CampaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReReviewsForSessionRow{}
	for rows.Next() {
		var i ReReviewsForSessionRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RequestedBy,
			&i.Reason,
			&i.AppealedDecision,
			&i.OriginalReviewer,
			&i.EvaluationID,
			&i.ResultDigest,
			&i.RubricDigest,
			&i.BundleDigest,
			&i.AssignedTo,
			&i.RaisedAt,
			&i.DueAt,
			&i.Outcome,
			&i.OutcomeRationale,
			&i.CandidateDisclosure,
			&i.ResolvedBy,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAcceptance = `-- name: RecordAcceptance :exec
INSERT INTO recruiting.disclosure_acceptance
    (id, tenant_id, campaign_id, candidate_id, disclosure_digest, disclosure_version)
VALUES ($1, $2, $3, $4, $5, $6)
`

type RecordAcceptanceParams struct {
	ID                string
	TenantID          string
	CampaignID        string
	CandidateID       string
	DisclosureDigest  string
	DisclosureVersion string
}

func (q *Queries) RecordAcceptance(ctx context.Context, arg RecordAcceptanceParams) error {
	_, err := q.db.Exec(ctx, recordAcceptance,
		arg.ID,
		arg.TenantID,
		arg.CampaignID,
		arg.CandidateID,
		arg.DisclosureDigest,
		arg.DisclosureVersion,
	)
	return err
}

const recordAccommodationDecision = `-- name: RecordAccommodationDecision :execrows
INSERT INTO recruiting.accommodation_decision (id, tenant_id, request_id, granted, decided_by)
SELECT $1::uuid, $2::uuid, r.id, $3::boolean, $4::uuid
FROM recruiting.accommodation_request r
WHERE r.id = $5::uuid AND r.campaign_id = $6::uuid
`

type RecordAccommodationDecisionParams struct {
	ID         string
	TenantID   string
	Granted    bool
	DecidedBy  string
	RequestID  string
	CampaignID string
}

// The campaign guard is a join, not decoration: a decision lands only on a
// request that belongs to the named campaign, so a recruiter admitted to one
// campaign cannot answer another's request in the same tenant by its id. Zero
// rows means no such request on this campaign, which the store turns into a
// not-found rather than a silent no-op.
func (q *Queries) RecordAccommodationDecision(ctx context.Context, arg RecordAccommodationDecisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordAccommodationDecision,
		arg.ID,
		arg.TenantID,
		arg.Granted,
		arg.DecidedBy,
		arg.RequestID,
		arg.CampaignID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordAccommodationFulfilment = `-- name: RecordAccommodationFulfilment :exec
INSERT INTO recruiting.accommodation_fulfilment
    (id, tenant_id, request_id, session_id)
VALUES ($1, $2, $3, $4)
`

type RecordAccommodationFulfilmentParams struct {
	ID        string
	TenantID  string
	RequestID string
	SessionID string
}

// The requires-a-standing-grant rule is enforced by trigger here as well as
// by the store, so a future caller reaching for this query directly meets the
// same refusal the store would have given it.
func (q *Queries) RecordAccommodationFulfilment(ctx context.Context, arg RecordAccommodationFulfilmentParams) error {
	_, err := q.db.Exec(ctx, recordAccommodationFulfilment,
		arg.ID,
		arg.TenantID,
		arg.RequestID,
		arg.SessionID,
	)
	return err
}

const recordConsentDecision = `-- name: RecordConsentDecision :exec
INSERT INTO recruiting.consent_decision
    (id, tenant_id, campaign_id, candidate_id, purpose, required, granted, disclosure_digest)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type RecordConsentDecisionParams struct {
	ID               string
	TenantID         string
	CampaignID       string
	CandidateID      string
	Purpose          string
	Required         bool
	Granted          bool
	DisclosureDigest string
}

func (q *Queries) RecordConsentDecision(ctx context.Context, arg RecordConsentDecisionParams) error {
	_, err := q.db.Exec(ctx, recordConsentDecision,
		arg.ID,
		arg.TenantID,
		arg.CampaignID,
		arg.CandidateID,
		arg.Purpose,
		arg.Required,
		arg.Granted,
		arg.DisclosureDigest,
	)
	return err
}

const recordReviewDecision = `-- name: RecordReviewDecision :one

INSERT INTO recruiting.review_decision
    (id, campaign_id, tenant_id, session_id, decided_by, decision, reason,
     evaluation_id, result_digest, rubric_digest, overrides)
VALUES ($1::uuid, $2::uuid, $3::uuid,
        $4::uuid, $5::uuid,
        $6::text, $7::text,
        $8::uuid, $9::text,
        $10::text, $11::jsonb)
RETURNING id, session_id, decided_by, decision, reason, evaluation_id,
          result_digest, rubric_digest, overrides, created_at
`

type RecordReviewDecisionParams struct {
	ID           string
	CampaignID   string
	TenantID     string
	SessionID    string
	DecidedBy    string
	Decision     string
	Reason       string
	EvaluationID string
	ResultDigest string
	RubricDigest string
	Overrides    []byte
}

type RecordReviewDecisionRow struct {
	ID           string
	SessionID    string
	DecidedBy    string
	Decision     string
	Reason       string
	EvaluationID string
	ResultDigest string
	RubricDigest string
	Overrides    []byte
	CreatedAt    time.Time
}

// ── REV-03: the hiring decision, append-only.
// One named human's decision, with the evidence version it was informed
// by. Append-only: there is no update to converge with, a new decision is
// a new row and the history keeps them all.
func (q *Queries) RecordReviewDecision(ctx context.Context, arg RecordReviewDecisionParams) (RecordReviewDecisionRow, error) {
	row := q.db.QueryRow(ctx, recordReviewDecision,
		arg.ID,
		arg.CampaignID,
		arg.TenantID,
		arg.SessionID,
		arg.DecidedBy,
		arg.Decision,
		arg.Reason,
		arg.EvaluationID,
		arg.ResultDigest,
		arg.RubricDigest,
		arg.Overrides,
	)
	var i RecordReviewDecisionRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DecidedBy,
		&i.Decision,
		&i.Reason,
		&i.EvaluationID,
		&i.ResultDigest,
		&i.RubricDigest,
		&i.Overrides,
		&i.CreatedAt,
	)
	return i, err
}

const recruiterMayAccess = `-- name: RecruiterMayAccess :one
SELECT EXISTS (
    SELECT 1 FROM recruiting.campaign_recruiter
    WHERE campaign_id = $1 AND user_id = $2
) AS allowed
`

type RecruiterMayAccessParams struct {
	CampaignID string
	UserID     string
}

func (q *Queries) RecruiterMayAccess(ctx context.Context, arg RecruiterMayAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, recruiterMayAccess, arg.CampaignID, arg.UserID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const requestAccommodation = `-- name: RequestAccommodation :one
INSERT INTO recruiting.accommodation_request
    (id, tenant_id, campaign_id, candidate_id, adjustment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, campaign_id, candidate_id, adjustment, requested_at
`

type RequestAccommodationParams struct {
	ID          string
	TenantID    string
	CampaignID  string
	CandidateID string
	Adjustment  string
}

func (q *Queries) RequestAccommodation(ctx context.Context, arg RequestAccommodationParams) (RecruitingAccommodationRequest, error) {
	row := q.db.QueryRow(ctx, requestAccommodation,
		arg.ID,
		arg.TenantID,
		arg.CampaignID,
		arg.CandidateID,
		arg.Adjustment,
	)
	var i RecruitingAccommodationRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CampaignID,
		&i.CandidateID,
		&i.Adjustment,
		&i.RequestedAt,
	)
	return i, err
}

const requirementsForCampaign = `-- name: RequirementsForCampaign :many
SELECT id, campaign_id, text, span_start, span_end, status, extraction_version, created_at
FROM recruiting.campaign_requirement
WHERE campaign_id = $1
ORDER BY created_at, id
`

type RequirementsForCampaignRow struct {
	ID                string
	CampaignID        string
	Text              string
	SpanStart         int32
	SpanEnd           int32
	Status            string
	ExtractionVersion string
	CreatedAt         time.Time
}

// The campaign's requirements, in the order they were extracted, so the recruiter
// reads them against the job description's own order. Tenant scoping is the policy's.
func (q *Queries) RequirementsForCampaign(ctx context.Context, campaignID string) ([]RequirementsForCampaignRow, error) {
	rows, err := q.db.Query(ctx, requirementsForCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequirementsForCampaignRow{}
	for rows.Next() {
		var i RequirementsForCampaignRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Text,
			&i.SpanStart,
			&i.SpanEnd,
			&i.Status,
			&i.ExtractionVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveInvitationByToken = `-- name: ResolveInvitationByToken :one
SELECT id, tenant_id, campaign_id, recipient, email_id, issued_by,
       issued_at, expires_at, outcome, outcome_at
FROM recruiting.invitation
WHERE token_hash = $1
`

type ResolveInvitationByTokenRow struct {
	ID         string
	TenantID   string
	CampaignID string
	Recipient  string
	EmailID    string
	IssuedBy   string
	IssuedAt   time.Time
	ExpiresAt  time.Time
	Outcome    pgtype.Text
	OutcomeAt  *time.Time
}

// Read one invitation by the hash of the presented token, for the candidate
// acceptance path. Access is the token-scoped policy's: the row is visible only
// because the caller set app.invitation_token_hash to this same hash, which is
// proof they hold the token. The WHERE is that hash again, so the query names
// the one row the policy already narrowed to rather than trusting the scope
// alone.
func (q *Queries) ResolveInvitationByToken(ctx context.Context, tokenHash string) (ResolveInvitationByTokenRow, error) {
	row := q.db.QueryRow(ctx, resolveInvitationByToken, tokenHash)
	var i ResolveInvitationByTokenRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CampaignID,
		&i.Recipient,
		&i.EmailID,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Outcome,
		&i.OutcomeAt,
	)
	return i, err
}

const resolveReReview = `-- name: ResolveReReview :execrows
UPDATE recruiting.re_review
SET outcome = $1::text,
    outcome_rationale = $2::text,
    candidate_disclosure = $3::text,
    resolved_by = $4::uuid,
    resolved_at = now()
WHERE id = $5::uuid
  AND campaign_id = $6::uuid
  AND outcome IS NULL
  AND assigned_to = $4::uuid
`

type ResolveReReviewParams struct {
	Outcome    string
	Rationale  string
	Disclosure string
	ResolvedBy string
	ID         string
	CampaignID string
}

// Resolution, once, by the assigned reviewer themselves. The guards are
// the WHERE clause: unresolved, and resolver = assignee; the trigger and
// the CHECKs back them at the schema.
func (q *Queries) ResolveReReview(ctx context.Context, arg ResolveReReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveReReview,
		arg.Outcome,
		arg.Rationale,
		arg.Disclosure,
		arg.ResolvedBy,
		arg.ID,
		arg.CampaignID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reviewDecisionsForSession = `-- name: ReviewDecisionsForSession :many
SELECT id, session_id, decided_by, decision, reason, evaluation_id,
       result_digest, rubric_digest, overrides, created_at
FROM recruiting.review_decision
WHERE session_id = $1::uuid
  AND campaign_id = $2::uuid
ORDER BY created_at
`

type ReviewDecisionsForSessionParams struct {
	SessionID  string
	CampaignID string
}

type ReviewDecisionsForSessionRow struct {
	ID           string
	SessionID    string
	DecidedBy    string
	Decision     string
	Reason       string
	EvaluationID string
	ResultDigest string
	RubricDigest string
	Overrides    []byte
	CreatedAt    time.Time
}

// The whole history, oldest first: every decision ever recorded on the
// session, each with its true actor and the evidence version it read.
func (q *Queries) ReviewDecisionsForSession(ctx context.Context, arg ReviewDecisionsForSessionParams) ([]ReviewDecisionsForSessionRow, error) {
	rows, err := q.db.Query(ctx, reviewDecisionsForSession, arg.SessionID, arg.CampaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewDecisionsForSessionRow{}
	for rows.Next() {
		var i ReviewDecisionsForSessionRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DecidedBy,
			&i.Decision,
			&i.Reason,
			&i.EvaluationID,
			&i.ResultDigest,
			&i.RubricDigest,
			&i.Overrides,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCampaignAccess = `-- name: RevokeCampaignAccess :exec
DELETE FROM recruiting.campaign_recruiter WHERE campaign_id = $1 AND user_id = $2
`

type RevokeCampaignAccessParams struct {
	CampaignID string
	UserID     string
}

func (q *Queries) RevokeCampaignAccess(ctx context.Context, arg RevokeCampaignAccessParams) error {
	_, err := q.db.Exec(ctx, revokeCampaignAccess, arg.CampaignID, arg.UserID)
	return err
}

const revokeInvitation = `-- name: RevokeInvitation :one
UPDATE recruiting.invitation
SET outcome = 'revoked', outcome_at = now()
WHERE id = $1 AND campaign_id = $2 AND outcome IS NULL
RETURNING id, tenant_id, campaign_id, recipient, email_id, issued_by,
          issued_at, expires_at, outcome, outcome_at
`

type RevokeInvitationParams struct {
	ID         string
	CampaignID string
}

type RevokeInvitationRow struct {
	ID         string
	TenantID   string
	CampaignID string
	Recipient  string
	EmailID    string
	IssuedBy   string
	IssuedAt   time.Time
	ExpiresAt  time.Time
	Outcome    pgtype.Text
	OutcomeAt  *time.Time
}

// Revoke one invitation by id on one campaign, but only while it is still live.
// The campaign_id in the guard is the per-campaign scope: a recruiter admitted
// to one campaign cannot revoke another campaign's invitation in the same
// tenant by knowing its id, because the id alone matches nothing without the
// campaign the caller was checked against. The guard on a null outcome is what
// makes revocation honest: a link the candidate has already accepted or
// declined cannot be quietly revoked out from under the record of what they
// did, and revoking an already-revoked one is a no-op that returns nothing
// rather than a second ending. Nothing is deleted; the row and everything it
// points at stay exactly where they are.
func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (RevokeInvitationRow, error) {
	row := q.db.QueryRow(ctx, revokeInvitation, arg.ID, arg.CampaignID)
	var i RevokeInvitationRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CampaignID,
		&i.Recipient,
		&i.EmailID,
		&i.IssuedBy,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.Outcome,
		&i.OutcomeAt,
	)
	return i, err
}

const standingAccommodationDecision = `-- name: StandingAccommodationDecision :one
SELECT request_id, granted, decided_by, decided_at
FROM recruiting.accommodation_decision
WHERE request_id = $1
ORDER BY decided_at DESC
LIMIT 1
`

type StandingAccommodationDecisionRow struct {
	RequestID string
	Granted   bool
	DecidedBy string
	DecidedAt time.Time
}

// The latest decision for one request, which is the standing answer: a grant
// later withdrawn or a decline later reversed is a newer row, never an edit.
func (q *Queries) StandingAccommodationDecision(ctx context.Context, requestID string) (StandingAccommodationDecisionRow, error) {
	row := q.db.QueryRow(ctx, standingAccommodationDecision, requestID)
	var i StandingAccommodationDecisionRow
	err := row.Scan(
		&i.RequestID,
		&i.Granted,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const standingConsent = `-- name: StandingConsent :many
SELECT DISTINCT ON (purpose)
       purpose, required, granted, disclosure_digest, decided_at
FROM recruiting.consent_decision
WHERE campaign_id = $1 AND candidate_id = $2
ORDER BY purpose, decided_at DESC
`

type StandingConsentParams struct {
	CampaignID  string
	CandidateID string
}

type StandingConsentRow struct {
	Purpose          string
	Required         bool
	Granted          bool
	DisclosureDigest string
	DecidedAt        time.Time
}

// The latest decision per purpose. DISTINCT ON rather than a join on max, so
// one index scan answers it and a withdrawal recorded later automatically
// becomes the standing answer without any row being edited.
func (q *Queries) StandingConsent(ctx context.Context, arg StandingConsentParams) ([]StandingConsentRow, error) {
	rows, err := q.db.Query(ctx, standingConsent, arg.CampaignID, arg.CandidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StandingConsentRow{}
	for rows.Next() {
		var i StandingConsentRow
		if err := rows.Scan(
			&i.Purpose,
			&i.Required,
			&i.Granted,
			&i.DisclosureDigest,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeLiveInvitations = `-- name: SupersedeLiveInvitations :exec
UPDATE recruiting.invitation
SET outcome = 'superseded', outcome_at = now()
WHERE campaign_id = $1 AND recipient = $2 AND outcome IS NULL
`

type SupersedeLiveInvitationsParams struct {
	CampaignID string
	Recipient  string
}

// Retire every live link for this recipient on this campaign, which is what a
// resend does before it issues a fresh one: the old link stops working the
// instant the new one is promised, so a recipient forwarded two emails cannot
// accept twice. Only live rows are touched; a spent or revoked invitation
// keeps the ending it already has.
func (q *Queries) SupersedeLiveInvitations(ctx context.Context, arg SupersedeLiveInvitationsParams) error {
	_, err := q.db.Exec(ctx, supersedeLiveInvitations, arg.CampaignID, arg.Recipient)
	return err
}

const upsertJobContext = `-- name: UpsertJobContext :exec
INSERT INTO recruiting.job_context (campaign_id, tenant_id, source_text, extraction_version)
VALUES ($1, $2, $3, $4)
ON CONFLICT (campaign_id) DO UPDATE
SET source_text = EXCLUDED.source_text,
    extraction_version = EXCLUDED.extraction_version,
    submitted_at = now()
`

type UpsertJobContextParams struct {
	CampaignID        string
	TenantID          string
	SourceText        string
	ExtractionVersion string
}

// The job context, one per campaign, replaced wholesale on resubmission. The
// source is stored verbatim so requirement spans index into the exact bytes.
func (q *Queries) UpsertJobContext(ctx context.Context, arg UpsertJobContextParams) error {
	_, err := q.db.Exec(ctx, upsertJobContext,
		arg.CampaignID,
		arg.TenantID,
		arg.SourceText,
		arg.ExtractionVersion,
	)
	return err
}
