// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package recruitingdb

import (
	"context"
	"time"
)

const acceptancesFor = `-- name: AcceptancesFor :many
SELECT id, campaign_id, candidate_id, disclosure_digest, disclosure_version, accepted_at
FROM recruiting.disclosure_acceptance
WHERE campaign_id = $1 AND candidate_id = $2
ORDER BY accepted_at DESC
`

type AcceptancesForParams struct {
	CampaignID  string
	CandidateID string
}

type AcceptancesForRow struct {
	ID                string
	CampaignID        string
	CandidateID       string
	DisclosureDigest  string
	DisclosureVersion string
	AcceptedAt        time.Time
}

// Every acceptance, newest first. All of them rather than the latest, because
// "what had this person been told when they sat the interview" is a question
// about a moment, and answering it needs the history.
func (q *Queries) AcceptancesFor(ctx context.Context, arg AcceptancesForParams) ([]AcceptancesForRow, error) {
	rows, err := q.db.Query(ctx, acceptancesFor, arg.CampaignID, arg.CandidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcceptancesForRow{}
	for rows.Next() {
		var i AcceptancesForRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.CandidateID,
			&i.DisclosureDigest,
			&i.DisclosureVersion,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accommodationRequestsFor = `-- name: AccommodationRequestsFor :many
SELECT id, campaign_id, candidate_id, adjustment, requested_at
FROM recruiting.accommodation_request
WHERE campaign_id = $1 AND candidate_id = $2
ORDER BY requested_at DESC
`

type AccommodationRequestsForParams struct {
	CampaignID  string
	CandidateID string
}

type AccommodationRequestsForRow struct {
	ID          string
	CampaignID  string
	CandidateID string
	Adjustment  string
	RequestedAt time.Time
}

// Every request this candidate made on this campaign, newest first. The
// standing decision is read per request through StandingAccommodationDecision
// rather than joined here: a request nobody has answered has no decision row,
// and "no row" is an answer this store gives a specific meaning to
// ("requested") rather than a null it has to reinterpret.
func (q *Queries) AccommodationRequestsFor(ctx context.Context, arg AccommodationRequestsForParams) ([]AccommodationRequestsForRow, error) {
	rows, err := q.db.Query(ctx, accommodationRequestsFor, arg.CampaignID, arg.CandidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccommodationRequestsForRow{}
	for rows.Next() {
		var i AccommodationRequestsForRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.CandidateID,
			&i.Adjustment,
			&i.RequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accommodationsForSession = `-- name: AccommodationsForSession :many
SELECT r.adjustment, f.request_id, f.session_id, f.fulfilled_at
FROM recruiting.accommodation_fulfilment f
JOIN recruiting.accommodation_request r ON r.id = f.request_id
WHERE f.session_id = $1
ORDER BY f.fulfilled_at
`

type AccommodationsForSessionRow struct {
	Adjustment  string
	RequestID   string
	SessionID   string
	FulfilledAt time.Time
}

// What was actually applied to one session: the read the interview runner's
// port will serve when the composition root wires it. This is the record of
// an accommodation being exercised, and it lives here so that evaluation,
// which cannot name this schema, can never make a signal of it.
func (q *Queries) AccommodationsForSession(ctx context.Context, sessionID string) ([]AccommodationsForSessionRow, error) {
	rows, err := q.db.Query(ctx, accommodationsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccommodationsForSessionRow{}
	for rows.Next() {
		var i AccommodationsForSessionRow
		if err := rows.Scan(
			&i.Adjustment,
			&i.RequestID,
			&i.SessionID,
			&i.FulfilledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const campaignsForRecruiter = `-- name: CampaignsForRecruiter :many
SELECT c.id, c.tenant_id, c.name, c.status, c.role_reference, c.jurisdiction,
       c.determination_id, c.opened_at, c.closed_at, c.created_at, c.created_by
FROM recruiting.campaign c
JOIN recruiting.campaign_recruiter r ON r.campaign_id = c.id
WHERE r.user_id = $1
ORDER BY c.created_at DESC
`

// Scoped by the join rather than by a filter the caller supplies, so a caller
// that forgets to filter gets nothing rather than everything.
func (q *Queries) CampaignsForRecruiter(ctx context.Context, userID string) ([]RecruitingCampaign, error) {
	rows, err := q.db.Query(ctx, campaignsForRecruiter, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecruitingCampaign{}
	for rows.Next() {
		var i RecruitingCampaign
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Status,
			&i.RoleReference,
			&i.Jurisdiction,
			&i.DeterminationID,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const campaignsUsingArtifact = `-- name: CampaignsUsingArtifact :many
SELECT c.name
FROM recruiting.campaign c
JOIN recruiting.campaign_pin p ON p.campaign_id = c.id
WHERE c.status = 'open' AND p.reference = $1::text
ORDER BY c.name
`

// The open campaigns that pinned a given artifact reference.
//
// By reference rather than by digest, which is the opposite of how a campaign
// identifies its configuration and is deliberate. The question this answers is
// the author's: "may I remove this rubric", and they think in references. A
// digest match would answer only for the exact version pinned and would let
// the draft behind a running campaign be discarded.
//
// Open only. A closed campaign runs nothing and issues nothing, so it does not
// block an author from tidying up; what it already evaluated is pinned by
// digest and stays resolvable either way.
//
// Tenant scoping comes from the row-level security policy rather than a
// predicate here, so a caller who forgets to scope gets nothing rather than
// another workspace's campaign names.
func (q *Queries) CampaignsUsingArtifact(ctx context.Context, reference string) ([]string, error) {
	rows, err := q.db.Query(ctx, campaignsUsingArtifact, reference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeCampaign = `-- name: CloseCampaign :one
UPDATE recruiting.campaign
SET status = 'closed', closed_at = now()
WHERE id = $1 AND status = 'open'
RETURNING id, tenant_id, name, status, role_reference, jurisdiction,
          determination_id, opened_at, closed_at, created_at, created_by
`

func (q *Queries) CloseCampaign(ctx context.Context, id string) (RecruitingCampaign, error) {
	row := q.db.QueryRow(ctx, closeCampaign, id)
	var i RecruitingCampaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.RoleReference,
		&i.Jurisdiction,
		&i.DeterminationID,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO recruiting.campaign (id, tenant_id, name, role_reference, jurisdiction, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, status, role_reference, jurisdiction,
          determination_id, opened_at, closed_at, created_at, created_by
`

type CreateCampaignParams struct {
	ID            string
	TenantID      string
	Name          string
	RoleReference string
	Jurisdiction  string
	CreatedBy     string
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (RecruitingCampaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.RoleReference,
		arg.Jurisdiction,
		arg.CreatedBy,
	)
	var i RecruitingCampaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.RoleReference,
		&i.Jurisdiction,
		&i.DeterminationID,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const determinationByID = `-- name: DeterminationByID :one
SELECT id, jurisdiction, version, result_disclosure, appeal_status, approver, approved_at
FROM recruiting.jurisdiction_determination
WHERE id = $1
`

type DeterminationByIDRow struct {
	ID               string
	Jurisdiction     string
	Version          int32
	ResultDisclosure string
	AppealStatus     string
	Approver         string
	ApprovedAt       time.Time
}

func (q *Queries) DeterminationByID(ctx context.Context, id string) (DeterminationByIDRow, error) {
	row := q.db.QueryRow(ctx, determinationByID, id)
	var i DeterminationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Jurisdiction,
		&i.Version,
		&i.ResultDisclosure,
		&i.AppealStatus,
		&i.Approver,
		&i.ApprovedAt,
	)
	return i, err
}

const grantCampaignAccess = `-- name: GrantCampaignAccess :exec
INSERT INTO recruiting.campaign_recruiter (campaign_id, tenant_id, user_id, granted_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (campaign_id, user_id) DO NOTHING
`

type GrantCampaignAccessParams struct {
	CampaignID string
	TenantID   string
	UserID     string
	GrantedBy  string
}

func (q *Queries) GrantCampaignAccess(ctx context.Context, arg GrantCampaignAccessParams) error {
	_, err := q.db.Exec(ctx, grantCampaignAccess,
		arg.CampaignID,
		arg.TenantID,
		arg.UserID,
		arg.GrantedBy,
	)
	return err
}

const latestDeterminationFor = `-- name: LatestDeterminationFor :one
SELECT id, jurisdiction, version, result_disclosure, appeal_status, approver, approved_at
FROM recruiting.jurisdiction_determination
WHERE jurisdiction = $1
ORDER BY version DESC
LIMIT 1
`

type LatestDeterminationForRow struct {
	ID               string
	Jurisdiction     string
	Version          int32
	ResultDisclosure string
	AppealStatus     string
	Approver         string
	ApprovedAt       time.Time
}

// The current determination for a jurisdiction. Absence is the answer that
// matters: ADR-0020 makes a missing determination a refusal to open, not a
// permissive default.
func (q *Queries) LatestDeterminationFor(ctx context.Context, jurisdiction string) (LatestDeterminationForRow, error) {
	row := q.db.QueryRow(ctx, latestDeterminationFor, jurisdiction)
	var i LatestDeterminationForRow
	err := row.Scan(
		&i.ID,
		&i.Jurisdiction,
		&i.Version,
		&i.ResultDisclosure,
		&i.AppealStatus,
		&i.Approver,
		&i.ApprovedAt,
	)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, tenant_id, name, status, role_reference, jurisdiction,
       determination_id, opened_at, closed_at, created_at, created_by
FROM recruiting.campaign
ORDER BY created_at DESC
`

// Every campaign in the tenant, newest first.
//
// Deliberately not joined to campaign_recruiter: campaign.read is unscoped in
// the catalogue precisely so a recruiter can see which campaigns exist before
// being assigned to one. What stays behind the join is everything about a
// particular campaign. Tenant scoping is the row-level security policy's, so a
// caller who forgets to scope gets nothing rather than another workspace's
// roster of roles.
func (q *Queries) ListCampaigns(ctx context.Context) ([]RecruitingCampaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecruitingCampaign{}
	for rows.Next() {
		var i RecruitingCampaign
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Status,
			&i.RoleReference,
			&i.Jurisdiction,
			&i.DeterminationID,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openCampaign = `-- name: OpenCampaign :one
UPDATE recruiting.campaign
SET status = 'open', determination_id = $2, opened_at = now()
WHERE id = $1 AND status = 'draft'
RETURNING id, tenant_id, name, status, role_reference, jurisdiction,
          determination_id, opened_at, closed_at, created_at, created_by
`

type OpenCampaignParams struct {
	ID              string
	DeterminationID *string
}

// Opening is a guarded transition, not a field update. The WHERE clause carries
// the guard so that two concurrent opens cannot both succeed: the second finds
// no draft row and gets no result, rather than overwriting the first one's
// determination.
func (q *Queries) OpenCampaign(ctx context.Context, arg OpenCampaignParams) (RecruitingCampaign, error) {
	row := q.db.QueryRow(ctx, openCampaign, arg.ID, arg.DeterminationID)
	var i RecruitingCampaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.RoleReference,
		&i.Jurisdiction,
		&i.DeterminationID,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const pinArtifact = `-- name: PinArtifact :exec
INSERT INTO recruiting.campaign_pin
    (campaign_id, tenant_id, artifact_type, artifact_id, digest, reference, version)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type PinArtifactParams struct {
	CampaignID   string
	TenantID     string
	ArtifactType string
	ArtifactID   string
	Digest       string
	Reference    string
	Version      string
}

func (q *Queries) PinArtifact(ctx context.Context, arg PinArtifactParams) error {
	_, err := q.db.Exec(ctx, pinArtifact,
		arg.CampaignID,
		arg.TenantID,
		arg.ArtifactType,
		arg.ArtifactID,
		arg.Digest,
		arg.Reference,
		arg.Version,
	)
	return err
}

const pinsForCampaign = `-- name: PinsForCampaign :many
SELECT campaign_id, artifact_type, artifact_id, digest, reference, version, pinned_at
FROM recruiting.campaign_pin
WHERE campaign_id = $1
ORDER BY artifact_type
`

type PinsForCampaignRow struct {
	CampaignID   string
	ArtifactType string
	ArtifactID   string
	Digest       string
	Reference    string
	Version      string
	PinnedAt     time.Time
}

func (q *Queries) PinsForCampaign(ctx context.Context, campaignID string) ([]PinsForCampaignRow, error) {
	rows, err := q.db.Query(ctx, pinsForCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PinsForCampaignRow{}
	for rows.Next() {
		var i PinsForCampaignRow
		if err := rows.Scan(
			&i.CampaignID,
			&i.ArtifactType,
			&i.ArtifactID,
			&i.Digest,
			&i.Reference,
			&i.Version,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAcceptance = `-- name: RecordAcceptance :exec
INSERT INTO recruiting.disclosure_acceptance
    (id, tenant_id, campaign_id, candidate_id, disclosure_digest, disclosure_version)
VALUES ($1, $2, $3, $4, $5, $6)
`

type RecordAcceptanceParams struct {
	ID                string
	TenantID          string
	CampaignID        string
	CandidateID       string
	DisclosureDigest  string
	DisclosureVersion string
}

func (q *Queries) RecordAcceptance(ctx context.Context, arg RecordAcceptanceParams) error {
	_, err := q.db.Exec(ctx, recordAcceptance,
		arg.ID,
		arg.TenantID,
		arg.CampaignID,
		arg.CandidateID,
		arg.DisclosureDigest,
		arg.DisclosureVersion,
	)
	return err
}

const recordAccommodationDecision = `-- name: RecordAccommodationDecision :exec
INSERT INTO recruiting.accommodation_decision
    (id, tenant_id, request_id, granted, decided_by)
VALUES ($1, $2, $3, $4, $5)
`

type RecordAccommodationDecisionParams struct {
	ID        string
	TenantID  string
	RequestID string
	Granted   bool
	DecidedBy string
}

func (q *Queries) RecordAccommodationDecision(ctx context.Context, arg RecordAccommodationDecisionParams) error {
	_, err := q.db.Exec(ctx, recordAccommodationDecision,
		arg.ID,
		arg.TenantID,
		arg.RequestID,
		arg.Granted,
		arg.DecidedBy,
	)
	return err
}

const recordAccommodationFulfilment = `-- name: RecordAccommodationFulfilment :exec
INSERT INTO recruiting.accommodation_fulfilment
    (id, tenant_id, request_id, session_id)
VALUES ($1, $2, $3, $4)
`

type RecordAccommodationFulfilmentParams struct {
	ID        string
	TenantID  string
	RequestID string
	SessionID string
}

// The requires-a-standing-grant rule is enforced by trigger here as well as
// by the store, so a future caller reaching for this query directly meets the
// same refusal the store would have given it.
func (q *Queries) RecordAccommodationFulfilment(ctx context.Context, arg RecordAccommodationFulfilmentParams) error {
	_, err := q.db.Exec(ctx, recordAccommodationFulfilment,
		arg.ID,
		arg.TenantID,
		arg.RequestID,
		arg.SessionID,
	)
	return err
}

const recordConsentDecision = `-- name: RecordConsentDecision :exec
INSERT INTO recruiting.consent_decision
    (id, tenant_id, campaign_id, candidate_id, purpose, required, granted, disclosure_digest)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type RecordConsentDecisionParams struct {
	ID               string
	TenantID         string
	CampaignID       string
	CandidateID      string
	Purpose          string
	Required         bool
	Granted          bool
	DisclosureDigest string
}

func (q *Queries) RecordConsentDecision(ctx context.Context, arg RecordConsentDecisionParams) error {
	_, err := q.db.Exec(ctx, recordConsentDecision,
		arg.ID,
		arg.TenantID,
		arg.CampaignID,
		arg.CandidateID,
		arg.Purpose,
		arg.Required,
		arg.Granted,
		arg.DisclosureDigest,
	)
	return err
}

const recruiterMayAccess = `-- name: RecruiterMayAccess :one
SELECT EXISTS (
    SELECT 1 FROM recruiting.campaign_recruiter
    WHERE campaign_id = $1 AND user_id = $2
) AS allowed
`

type RecruiterMayAccessParams struct {
	CampaignID string
	UserID     string
}

func (q *Queries) RecruiterMayAccess(ctx context.Context, arg RecruiterMayAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, recruiterMayAccess, arg.CampaignID, arg.UserID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const requestAccommodation = `-- name: RequestAccommodation :one
INSERT INTO recruiting.accommodation_request
    (id, tenant_id, campaign_id, candidate_id, adjustment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, campaign_id, candidate_id, adjustment, requested_at
`

type RequestAccommodationParams struct {
	ID          string
	TenantID    string
	CampaignID  string
	CandidateID string
	Adjustment  string
}

func (q *Queries) RequestAccommodation(ctx context.Context, arg RequestAccommodationParams) (RecruitingAccommodationRequest, error) {
	row := q.db.QueryRow(ctx, requestAccommodation,
		arg.ID,
		arg.TenantID,
		arg.CampaignID,
		arg.CandidateID,
		arg.Adjustment,
	)
	var i RecruitingAccommodationRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CampaignID,
		&i.CandidateID,
		&i.Adjustment,
		&i.RequestedAt,
	)
	return i, err
}

const revokeCampaignAccess = `-- name: RevokeCampaignAccess :exec
DELETE FROM recruiting.campaign_recruiter WHERE campaign_id = $1 AND user_id = $2
`

type RevokeCampaignAccessParams struct {
	CampaignID string
	UserID     string
}

func (q *Queries) RevokeCampaignAccess(ctx context.Context, arg RevokeCampaignAccessParams) error {
	_, err := q.db.Exec(ctx, revokeCampaignAccess, arg.CampaignID, arg.UserID)
	return err
}

const standingAccommodationDecision = `-- name: StandingAccommodationDecision :one
SELECT request_id, granted, decided_by, decided_at
FROM recruiting.accommodation_decision
WHERE request_id = $1
ORDER BY decided_at DESC
LIMIT 1
`

type StandingAccommodationDecisionRow struct {
	RequestID string
	Granted   bool
	DecidedBy string
	DecidedAt time.Time
}

// The latest decision for one request, which is the standing answer: a grant
// later withdrawn or a decline later reversed is a newer row, never an edit.
func (q *Queries) StandingAccommodationDecision(ctx context.Context, requestID string) (StandingAccommodationDecisionRow, error) {
	row := q.db.QueryRow(ctx, standingAccommodationDecision, requestID)
	var i StandingAccommodationDecisionRow
	err := row.Scan(
		&i.RequestID,
		&i.Granted,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const standingConsent = `-- name: StandingConsent :many
SELECT DISTINCT ON (purpose)
       purpose, required, granted, disclosure_digest, decided_at
FROM recruiting.consent_decision
WHERE campaign_id = $1 AND candidate_id = $2
ORDER BY purpose, decided_at DESC
`

type StandingConsentParams struct {
	CampaignID  string
	CandidateID string
}

type StandingConsentRow struct {
	Purpose          string
	Required         bool
	Granted          bool
	DisclosureDigest string
	DecidedAt        time.Time
}

// The latest decision per purpose. DISTINCT ON rather than a join on max, so
// one index scan answers it and a withdrawal recorded later automatically
// becomes the standing answer without any row being edited.
func (q *Queries) StandingConsent(ctx context.Context, arg StandingConsentParams) ([]StandingConsentRow, error) {
	rows, err := q.db.Query(ctx, standingConsent, arg.CampaignID, arg.CandidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StandingConsentRow{}
	for rows.Next() {
		var i StandingConsentRow
		if err := rows.Scan(
			&i.Purpose,
			&i.Required,
			&i.Granted,
			&i.DisclosureDigest,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
