// Code generated by tools/authzgen. DO NOT EDIT.
//
// Source: packages/contracts/authz/capabilities.yaml (version 1)
//
// The contract is the source and this file is derived from it. Editing here is
// undone by the next `make` generate, and the drift gate in CI fails first.

package authz

// The catalogue, version 1.
const CatalogueVersion = 1

const (
	// Handling a candidate's appeal against an evaluation, resolving a
	// re-review included. Wider than raising one, because changing an
	// evaluation's standing answers for the workspace.
	AppealManage Capability = "appeal.manage"

	// Raising a re-review of an evaluation. Asking the question is
	// separate from answering it: anyone doing the recruiting work can
	// flag an evaluation they can already read, and appeal.manage decides
	// what happens to it.
	AppealRaise Capability = "appeal.raise"

	// Changing a campaign needs an explicit assignment to it. Tenant
	// membership is not authority over every campaign in the tenant.
	CampaignManage Capability = "campaign.manage"

	// Reading campaigns inside one tenant. Unscoped, because a recruiter
	// may see which campaigns exist before being assigned to one.
	CampaignRead Capability = "campaign.read"

	// Deleting practice history is irreversible, so it needs recent
	// authentication rather than a session opened this morning.
	CandidatePracticeDeleteOwn Capability = "candidate.practice.delete_own"

	// Practice history is the candidate's alone. This is the capability
	// that makes practice private, and no tenant authority satisfies it.
	CandidatePracticeReadOwn Capability = "candidate.practice.read_own"

	// A candidate's own profile. Owner rather than tenant, because an
	// employer must never reach it.
	CandidateProfileReadOwn Capability = "candidate.profile.read_own"

	// Only the candidate edits their own profile. Nobody edits it on their
	// behalf.
	CandidateProfileWriteOwn Capability = "candidate.profile.write_own"

	// Drafting a platform artifact - a persona, prompt, rubric or policy.
	// Platform authority because these shape every tenant's interviews; a
	// draft changes nothing until somebody else publishes it.
	ContentArtifactDraft Capability = "content.artifact_draft"

	// Publishing changes how every future candidate is evaluated, which is
	// the definition of what step-up exists for. ADR-0011 adds the
	// structural half: the registry refuses a publish whose actor drafted
	// the version, so this capability alone is never sufficient for one
	// person to ship their own artifact.
	ContentArtifactPublish Capability = "content.artifact_publish"

	// Rolling back repoints the current version to an earlier publication.
	// Step-up for publishing's reason, and it is its own capability rather
	// than publish reused, because who may react to a bad artifact is a
	// different and usually wider question than who may ship one.
	ContentArtifactRollback Capability = "content.artifact_rollback"

	// Comparing candidates. Scoped and step-up: comparison is off by
	// default under responsible-hiring.md and is the most consequential
	// thing a recruiter can do.
	EvaluationCompare Capability = "evaluation.compare"

	// Reading a screening evaluation. Scoped, because an evaluation
	// belongs to a campaign and not to everyone in the tenant.
	EvaluationReadScreen Capability = "evaluation.read_screen"

	// Recording a human review of an evaluation. Step-up, because it
	// changes how a candidate is assessed.
	EvaluationReview Capability = "evaluation.review"

	// Issuing or revoking an invitation affects a candidate's access, so
	// it is scoped to the campaign rather than to the tenant.
	InvitationManage Capability = "invitation.manage"

	// Reading invitations for a campaign the recruiter is assigned to.
	InvitationRead Capability = "invitation.read"

	// Aggregate platform analytics. Platform authority, which is separate
	// from tenant authority rather than a superset of it.
	PlatformAnalyticsRead Capability = "platform.analytics_read"

	// Reading the audit trail, which is itself an auditable act.
	PlatformAuditRead Capability = "platform.audit_read"

	// Running an operational action. Privileged: it needs an active
	// elevation carrying a reason and a ticket.
	PlatformOperationsExecute Capability = "platform.operations_execute"

	// Reading operational state across the platform.
	PlatformOperationsRead Capability = "platform.operations_read"

	// Requesting elevation. Privileged and step-up, because it is the gate
	// every other privileged action passes through.
	PlatformPrivilegedElevate Capability = "platform.privileged_elevate"

	// Changing a tenant's quota.
	PlatformQuotaManage Capability = "platform.quota_manage"

	// Drafting a rubric. Unpublished drafts change nothing.
	RubricDraft Capability = "rubric.draft"

	// Publishing a rubric changes how every future candidate is evaluated,
	// so it needs recent authentication.
	RubricPublish Capability = "rubric.publish"

	// Reading the tenant's rubric library.
	RubricRead Capability = "rubric.read"

	// Accepting a screening invitation is the candidate's decision and
	// nobody else's.
	SessionAcceptInvitation Capability = "session.accept_invitation"

	// A candidate starts their own practice session. Owner, because a
	// recruiter starting one on somebody's behalf would be practice data
	// an employer produced.
	SessionCreatePractice Capability = "session.create_practice"

	// Being in the interview. Owner, because participation is by the
	// person invited.
	SessionParticipate Capability = "session.participate"

	// Reading one's own practice session.
	SessionReadOwnPractice Capability = "session.read_own_practice"

	// A candidate may see that their screening interview completed. What
	// the employer saw is a different capability.
	SessionReadScreenConfirmation Capability = "session.read_screen_confirmation"

	// Reading billing and usage.
	TenantBillingRead Capability = "tenant.billing_read"

	// Integrations move candidate data to systems outside Prepeet, so this
	// needs recent authentication.
	TenantIntegrationManage Capability = "tenant.integration_manage"

	// Adding or removing members changes who can see candidate evidence,
	// so it needs recent authentication.
	TenantMemberManage Capability = "tenant.member_manage"

	// Seeing who belongs to the workspace, with each person's role. Every
	// membership role holds it, because a colleague list is not authority
	// over anyone and hiding it only obscures who to ask for access.
	TenantMemberRead Capability = "tenant.member_read"

	// Retention determines when candidate data is destroyed, which is
	// irreversible.
	TenantRetentionManage Capability = "tenant.retention_manage"

	// Tenant configuration.
	TenantSettingsManage Capability = "tenant.settings_manage"
)

// catalogue maps every capability to what it requires.
var catalogue = map[Capability]Requirement{
	AppealManage:                  {Tenant: true, Scope: ScopeCampaign},
	AppealRaise:                   {Tenant: true, Scope: ScopeCampaign},
	CampaignManage:                {Tenant: true, Scope: ScopeCampaign},
	CampaignRead:                  {Tenant: true},
	CandidatePracticeDeleteOwn:    {Owner: true, StepUp: true},
	CandidatePracticeReadOwn:      {Owner: true},
	CandidateProfileReadOwn:       {Owner: true},
	CandidateProfileWriteOwn:      {Owner: true},
	ContentArtifactDraft:          {Platform: true},
	ContentArtifactPublish:        {Platform: true, StepUp: true},
	ContentArtifactRollback:       {Platform: true, StepUp: true},
	EvaluationCompare:             {Tenant: true, Scope: ScopeCampaign},
	EvaluationReadScreen:          {Tenant: true, Scope: ScopeCampaign},
	EvaluationReview:              {Tenant: true, Scope: ScopeCampaign},
	InvitationManage:              {Tenant: true},
	InvitationRead:                {Tenant: true},
	PlatformAnalyticsRead:         {Platform: true},
	PlatformAuditRead:             {Platform: true, Privileged: true},
	PlatformOperationsExecute:     {Platform: true, Privileged: true},
	PlatformOperationsRead:        {Platform: true},
	PlatformPrivilegedElevate:     {Platform: true, StepUp: true},
	PlatformQuotaManage:           {Platform: true, Privileged: true, StepUp: true},
	RubricDraft:                   {Tenant: true},
	RubricPublish:                 {Tenant: true, StepUp: true},
	RubricRead:                    {Tenant: true},
	SessionAcceptInvitation:       {Owner: true},
	SessionCreatePractice:         {Owner: true},
	SessionParticipate:            {Owner: true},
	SessionReadOwnPractice:        {Owner: true},
	SessionReadScreenConfirmation: {Owner: true},
	TenantBillingRead:             {Tenant: true},
	TenantIntegrationManage:       {Tenant: true, StepUp: true},
	TenantMemberManage:            {Tenant: true, StepUp: true},
	TenantMemberRead:              {Tenant: true},
	TenantRetentionManage:         {Tenant: true, StepUp: true},
	TenantSettingsManage:          {Tenant: true},
}

// Role is a bundle of capabilities.
//
// Never a check of its own. Nothing asks whether somebody is an owner; it asks
// whether they hold a capability, and a role is only how they came to hold it.
type Role string

const (
	// The tenant administrator: full access to every candidate in the
	// workspace and to all configuration - rubrics, members, integrations,
	// retention and billing. Granted sparingly, and identical in
	// capability to owner: what distinguishes an owner is being anchored
	// to the workspace's creation, not holding more.
	RoleAdmin Role = "admin"

	// What somebody holds with no tenant membership. Every capability here
	// is owner-scoped, so it reaches that person's own data and nothing
	// else. No tenant authority can satisfy any of them, which is what
	// keeps practice private from employers.
	RoleCandidate Role = "candidate"

	// A recruiter who additionally answers for outcomes: everything the
	// recruiting work needs, plus resolving the re-reviews recruiters
	// raise. Still scoped, still no workspace configuration.
	RoleHiringManager Role = "hiring_manager"

	// Whoever created the workspace, and anybody they make an owner. The
	// same capabilities as admin; the anchor exists so a workspace always
	// has an administrator nobody inside it can remove.
	RoleOwner Role = "owner"

	// Somebody invited to a workspace to do the recruiting work. They can
	// see what exists and act on the campaigns they are assigned to, raise
	// a re-review but not resolve one, and they cannot change how the
	// workspace itself is configured.
	RoleRecruiter Role = "recruiter"

	// Read-only. Can see campaigns, invitations and the evaluations they
	// are scoped to, and cannot record a decision, send an invitation or
	// change anything - the role for oversight without authority.
	RoleViewer Role = "viewer"
)

// bundles maps a role to what it grants.
var bundles = map[Role][]Capability{
	RoleAdmin: {
		AppealManage,
		AppealRaise,
		CampaignManage,
		CampaignRead,
		EvaluationReadScreen,
		EvaluationReview,
		InvitationManage,
		InvitationRead,
		RubricDraft,
		RubricPublish,
		RubricRead,
		TenantBillingRead,
		TenantIntegrationManage,
		TenantMemberManage,
		TenantMemberRead,
		TenantRetentionManage,
		TenantSettingsManage,
	},
	RoleCandidate: {
		CandidatePracticeDeleteOwn,
		CandidatePracticeReadOwn,
		CandidateProfileReadOwn,
		CandidateProfileWriteOwn,
		SessionAcceptInvitation,
		SessionCreatePractice,
		SessionParticipate,
		SessionReadOwnPractice,
		SessionReadScreenConfirmation,
	},
	RoleHiringManager: {
		AppealManage,
		AppealRaise,
		CampaignManage,
		CampaignRead,
		EvaluationReadScreen,
		EvaluationReview,
		InvitationManage,
		InvitationRead,
		RubricRead,
		TenantMemberRead,
	},
	RoleOwner: {
		AppealManage,
		AppealRaise,
		CampaignManage,
		CampaignRead,
		EvaluationReadScreen,
		EvaluationReview,
		InvitationManage,
		InvitationRead,
		RubricDraft,
		RubricPublish,
		RubricRead,
		TenantBillingRead,
		TenantIntegrationManage,
		TenantMemberManage,
		TenantMemberRead,
		TenantRetentionManage,
		TenantSettingsManage,
	},
	RoleRecruiter: {
		AppealRaise,
		CampaignManage,
		CampaignRead,
		EvaluationReadScreen,
		EvaluationReview,
		InvitationManage,
		InvitationRead,
		RubricRead,
		TenantMemberRead,
	},
	RoleViewer: {
		CampaignRead,
		EvaluationReadScreen,
		InvitationRead,
		RubricRead,
		TenantMemberRead,
	},
}
