// Code generated by tools/authzgen. DO NOT EDIT.
//
// Source: packages/contracts/authz/capabilities.yaml (version 1)
//
// The contract is the source and this file is derived from it. Editing here is
// undone by the next `make` generate, and the drift gate in CI fails first.

package authz

// The catalogue, version 1.
const CatalogueVersion = 1

const (
	// Handling a candidate's appeal against an evaluation.
	AppealManage Capability = "appeal.manage"

	// Changing a campaign needs an explicit assignment to it. Tenant
	// membership is not authority over every campaign in the tenant.
	CampaignManage Capability = "campaign.manage"

	// Reading campaigns inside one tenant. Unscoped, because a recruiter
	// may see which campaigns exist before being assigned to one.
	CampaignRead Capability = "campaign.read"

	// Deleting practice history is irreversible, so it needs recent
	// authentication rather than a session opened this morning.
	CandidatePracticeDeleteOwn Capability = "candidate.practice.delete_own"

	// Practice history is the candidate's alone. This is the capability
	// that makes practice private, and no tenant authority satisfies it.
	CandidatePracticeReadOwn Capability = "candidate.practice.read_own"

	// A candidate's own profile. Owner rather than tenant, because an
	// employer must never reach it.
	CandidateProfileReadOwn Capability = "candidate.profile.read_own"

	// Only the candidate edits their own profile. Nobody edits it on their
	// behalf.
	CandidateProfileWriteOwn Capability = "candidate.profile.write_own"

	// Comparing candidates. Scoped and step-up: comparison is off by
	// default under responsible-hiring.md and is the most consequential
	// thing a recruiter can do.
	EvaluationCompare Capability = "evaluation.compare"

	// Reading a screening evaluation. Scoped, because an evaluation
	// belongs to a campaign and not to everyone in the tenant.
	EvaluationReadScreen Capability = "evaluation.read_screen"

	// Recording a human review of an evaluation. Step-up, because it
	// changes how a candidate is assessed.
	EvaluationReview Capability = "evaluation.review"

	// Issuing or revoking an invitation affects a candidate's access, so
	// it is scoped to the campaign rather than to the tenant.
	InvitationManage Capability = "invitation.manage"

	// Reading invitations for a campaign the recruiter is assigned to.
	InvitationRead Capability = "invitation.read"

	// Aggregate platform analytics. Platform authority, which is separate
	// from tenant authority rather than a superset of it.
	PlatformAnalyticsRead Capability = "platform.analytics_read"

	// Reading the audit trail, which is itself an auditable act.
	PlatformAuditRead Capability = "platform.audit_read"

	// Running an operational action. Privileged: it needs an active
	// elevation carrying a reason and a ticket.
	PlatformOperationsExecute Capability = "platform.operations_execute"

	// Reading operational state across the platform.
	PlatformOperationsRead Capability = "platform.operations_read"

	// Requesting elevation. Privileged and step-up, because it is the gate
	// every other privileged action passes through.
	PlatformPrivilegedElevate Capability = "platform.privileged_elevate"

	// Changing a tenant's quota.
	PlatformQuotaManage Capability = "platform.quota_manage"

	// Drafting a rubric. Unpublished drafts change nothing.
	RubricDraft Capability = "rubric.draft"

	// Publishing a rubric changes how every future candidate is evaluated,
	// so it needs recent authentication.
	RubricPublish Capability = "rubric.publish"

	// Reading the tenant's rubric library.
	RubricRead Capability = "rubric.read"

	// Accepting a screening invitation is the candidate's decision and
	// nobody else's.
	SessionAcceptInvitation Capability = "session.accept_invitation"

	// A candidate starts their own practice session. Owner, because a
	// recruiter starting one on somebody's behalf would be practice data
	// an employer produced.
	SessionCreatePractice Capability = "session.create_practice"

	// Being in the interview. Owner, because participation is by the
	// person invited.
	SessionParticipate Capability = "session.participate"

	// Reading one's own practice session.
	SessionReadOwnPractice Capability = "session.read_own_practice"

	// A candidate may see that their screening interview completed. What
	// the employer saw is a different capability.
	SessionReadScreenConfirmation Capability = "session.read_screen_confirmation"

	// Reading billing and usage.
	TenantBillingRead Capability = "tenant.billing_read"

	// Integrations move candidate data to systems outside Prepeet, so this
	// needs recent authentication.
	TenantIntegrationManage Capability = "tenant.integration_manage"

	// Adding or removing members changes who can see candidate evidence,
	// so it needs recent authentication.
	TenantMemberManage Capability = "tenant.member_manage"

	// Retention determines when candidate data is destroyed, which is
	// irreversible.
	TenantRetentionManage Capability = "tenant.retention_manage"

	// Tenant configuration.
	TenantSettingsManage Capability = "tenant.settings_manage"
)

// catalogue maps every capability to what it requires.
var catalogue = map[Capability]Requirement{
	AppealManage:                  {Tenant: true, Scope: ScopeCampaign},
	CampaignManage:                {Tenant: true, Scope: ScopeCampaign},
	CampaignRead:                  {Tenant: true},
	CandidatePracticeDeleteOwn:    {Owner: true, StepUp: true},
	CandidatePracticeReadOwn:      {Owner: true},
	CandidateProfileReadOwn:       {Owner: true},
	CandidateProfileWriteOwn:      {Owner: true},
	EvaluationCompare:             {Tenant: true, Scope: ScopeCampaign},
	EvaluationReadScreen:          {Tenant: true, Scope: ScopeCampaign},
	EvaluationReview:              {Tenant: true, Scope: ScopeCampaign},
	InvitationManage:              {Tenant: true},
	InvitationRead:                {Tenant: true},
	PlatformAnalyticsRead:         {Platform: true},
	PlatformAuditRead:             {Platform: true, Privileged: true},
	PlatformOperationsExecute:     {Platform: true, Privileged: true},
	PlatformOperationsRead:        {Platform: true},
	PlatformPrivilegedElevate:     {Platform: true, StepUp: true},
	PlatformQuotaManage:           {Platform: true, Privileged: true, StepUp: true},
	RubricDraft:                   {Tenant: true},
	RubricPublish:                 {Tenant: true, StepUp: true},
	RubricRead:                    {Tenant: true},
	SessionAcceptInvitation:       {Owner: true},
	SessionCreatePractice:         {Owner: true},
	SessionParticipate:            {Owner: true},
	SessionReadOwnPractice:        {Owner: true},
	SessionReadScreenConfirmation: {Owner: true},
	TenantBillingRead:             {Tenant: true},
	TenantIntegrationManage:       {Tenant: true, StepUp: true},
	TenantMemberManage:            {Tenant: true, StepUp: true},
	TenantRetentionManage:         {Tenant: true, StepUp: true},
	TenantSettingsManage:          {Tenant: true},
}

// Role is a bundle of capabilities.
//
// Never a check of its own. Nothing asks whether somebody is an owner; it asks
// whether they hold a capability, and a role is only how they came to hold it.
type Role string

const (
	// What somebody holds with no tenant membership. Every capability here
	// is owner-scoped, so it reaches that person's own data and nothing
	// else. No tenant authority can satisfy any of them, which is what
	// keeps practice private from employers.
	RoleCandidate Role = "candidate"

	// Somebody invited to a workspace to do the recruiting work. They can
	// see what exists and act on the campaigns they are assigned to, and
	// they cannot change how the workspace itself is configured.
	RoleMember Role = "member"

	// Whoever created the workspace, and anybody they make an owner.
	// Everything a member holds, plus configuring the workspace itself:
	// who belongs to it, what it retains, what it is billed for, and which
	// rubrics are published.
	RoleOwner Role = "owner"
)

// bundles maps a role to what it grants.
var bundles = map[Role][]Capability{
	RoleCandidate: {
		CandidatePracticeDeleteOwn,
		CandidatePracticeReadOwn,
		CandidateProfileReadOwn,
		CandidateProfileWriteOwn,
		SessionAcceptInvitation,
		SessionCreatePractice,
		SessionParticipate,
		SessionReadOwnPractice,
		SessionReadScreenConfirmation,
	},
	RoleMember: {
		AppealManage,
		CampaignManage,
		CampaignRead,
		EvaluationReadScreen,
		EvaluationReview,
		InvitationManage,
		InvitationRead,
		RubricRead,
	},
	RoleOwner: {
		AppealManage,
		CampaignManage,
		CampaignRead,
		EvaluationReadScreen,
		EvaluationReview,
		InvitationManage,
		InvitationRead,
		RubricDraft,
		RubricPublish,
		RubricRead,
		TenantBillingRead,
		TenantIntegrationManage,
		TenantMemberManage,
		TenantRetentionManage,
		TenantSettingsManage,
	},
}
