package main

import (
	"fmt"
	"sort"
	"strings"
)

// goIdentifier turns an event type into an exported Go name.
//
// identity.user_registered.v1 becomes IdentityUserRegisteredV1. Derived rather
// than declared in the schema, so that a name cannot disagree with the type it
// belongs to, which is the only thing a consumer actually subscribes on.
func goIdentifier(eventType string) string {
	var name strings.Builder
	for _, segment := range strings.FieldsFunc(eventType, func(r rune) bool {
		return r == '.' || r == '_'
	}) {
		name.WriteString(strings.ToUpper(segment[:1]))
		name.WriteString(segment[1:])
	}
	return name.String()
}

// generateGo renders the registry the Go side validates and publishes against.
//
// A registry rather than a struct per event. The outbox has to answer two
// questions about an event it was handed at runtime, "is this a type we own"
// and "does this payload carry what it must", and neither can be answered by a
// type the caller chose not to use. Producers get the constants; the registry is
// what makes a raw payload checkable.
func generateGo(c *Catalogue) string {
	var b strings.Builder

	b.WriteString("// Code generated by tools/eventgen. DO NOT EDIT.\n//\n")
	b.WriteString("// The durable event catalogue, from packages/contracts/events.\n")
	b.WriteString("// See ADR-0004 and docs/contracts/event-catalog.md.\n\n")
	b.WriteString("package prepeetevents\n\n")

	b.WriteString("// Type is an event type, including its contract version.\n//\n")
	b.WriteString("// A named type rather than a bare string so that a function taking one\n")
	b.WriteString("// cannot be handed an arbitrary string that happens to be in scope.\n")
	b.WriteString("type Type string\n\n")

	b.WriteString("// The event types this system owns.\nconst (\n")
	for _, event := range c.Sorted() {
		b.WriteString(fmt.Sprintf("\t// %s\n", wrapComment(event.Description, "\t// ")))
		b.WriteString(fmt.Sprintf("\t//\n\t// Owner: %s. Consumers: %s.\n",
			event.Owner, strings.Join(event.Consumers, ", ")))
		b.WriteString(fmt.Sprintf("\t%s Type = %q\n\n", goIdentifier(event.Type), event.Type))
	}
	b.WriteString(")\n\n")

	b.WriteString("// Definition is what publication needs to know about one event type.\n")
	b.WriteString("type Definition struct {\n")
	b.WriteString("\t// Owner is the bounded context answerable for it.\n\tOwner string\n")
	b.WriteString("\t// SchemaVersion is the payload's version within this contract.\n\tSchemaVersion string\n")
	b.WriteString("\t// Required names the payload fields that must be present.\n\tRequired []string\n")
	b.WriteString("\t// Known names every field the payload may carry. A field outside this\n")
	b.WriteString("\t// set is refused rather than passed through, because a payload nobody\n")
	b.WriteString("\t// declared is one no consumer was told to expect.\n\tKnown []string\n")
	b.WriteString("}\n\n")

	b.WriteString("// Catalogue is every event type this system may publish.\n//\n")
	b.WriteString("// Publication refuses a type that is not here. An event nobody declared is\n")
	b.WriteString("// one no consumer subscribes to, so emitting it writes a row that will be\n")
	b.WriteString("// delivered to nobody and discovered by nobody.\n")
	b.WriteString("var Catalogue = map[Type]Definition{\n")
	for _, event := range c.Sorted() {
		b.WriteString(fmt.Sprintf("\t%s: {\n", goIdentifier(event.Type)))
		b.WriteString(fmt.Sprintf("\t\tOwner:         %q,\n", event.Owner))
		b.WriteString(fmt.Sprintf("\t\tSchemaVersion: %q,\n", event.SchemaVersion))
		b.WriteString(fmt.Sprintf("\t\tRequired:      []string{%s},\n", quoteAll(event.Payload.Required)))
		b.WriteString(fmt.Sprintf("\t\tKnown:         []string{%s},\n", quoteAll(propertyNames(event.Payload))))
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("// EnvelopeRequired names the envelope fields every event carries.\n//\n")
	b.WriteString("// Checked at publication rather than trusted, because these are what a\n")
	b.WriteString("// consumer relies on without knowing the event type, and one missing is a\n")
	b.WriteString("// row that cannot be deduplicated, attributed or audited.\n")
	b.WriteString(fmt.Sprintf("var EnvelopeRequired = []string{%s}\n", quoteAll(c.Envelope.Required)))

	return b.String()
}

// generateTypeScript renders the same catalogue for the browser and any Node
// consumer.
//
// A union of literal types rather than an enum, because a value arriving from
// the network is a string and an enum would have to be widened back to one at
// every boundary, which is where the checking would then not happen.
func generateTypeScript(c *Catalogue) string {
	var b strings.Builder

	b.WriteString("// Code generated by tools/eventgen. DO NOT EDIT.\n//\n")
	b.WriteString("// The durable event catalogue, from packages/contracts/events.\n")
	b.WriteString("// See ADR-0004 and docs/contracts/event-catalog.md.\n\n")

	b.WriteString("/** Every event type this system publishes. */\nexport type EventType =\n")
	for _, event := range c.Sorted() {
		b.WriteString(fmt.Sprintf("  | %q\n", event.Type))
	}
	b.WriteString(";\n\n")

	b.WriteString("/** What a consumer needs to know about one event type. */\n")
	b.WriteString("export interface EventDefinition {\n")
	b.WriteString("  /** The bounded context answerable for it. */\n  readonly owner: string;\n")
	b.WriteString("  /** The payload's version within this contract. Tolerate a higher one. */\n")
	b.WriteString("  readonly schemaVersion: string;\n")
	b.WriteString("  /** Payload fields that are always present. */\n  readonly required: readonly string[];\n")
	b.WriteString("  /** Every field the payload may carry. */\n  readonly known: readonly string[];\n")
	b.WriteString("}\n\n")

	b.WriteString("/**\n * The catalogue.\n *\n")
	b.WriteString(" * A consumer tolerates a field it does not know rather than refusing the\n")
	b.WriteString(" * event, because refusing one is how an additive change becomes a breaking\n")
	b.WriteString(" * one. See ADR-0004.\n */\n")
	b.WriteString("export const EVENT_CATALOGUE: Readonly<Record<EventType, EventDefinition>> = {\n")
	for _, event := range c.Sorted() {
		b.WriteString(fmt.Sprintf("  %q: {\n", event.Type))
		b.WriteString(fmt.Sprintf("    owner: %q,\n", event.Owner))
		b.WriteString(fmt.Sprintf("    schemaVersion: %q,\n", event.SchemaVersion))
		b.WriteString(fmt.Sprintf("    required: [%s],\n", quoteAll(event.Payload.Required)))
		b.WriteString(fmt.Sprintf("    known: [%s],\n", quoteAll(propertyNames(event.Payload))))
		b.WriteString("  },\n")
	}
	b.WriteString("} as const;\n\n")

	b.WriteString("/** Envelope fields present on every event. */\n")
	b.WriteString(fmt.Sprintf("export const ENVELOPE_REQUIRED: readonly string[] = [%s];\n",
		quoteAll(c.Envelope.Required)))

	return b.String()
}

// propertyNames returns a schema's property names in a stable order.
func propertyNames(schema *Schema) []string {
	names := make([]string, 0, len(schema.Properties))
	for name := range schema.Properties {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// quoteAll renders a string slice as quoted, comma-separated literals.
func quoteAll(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	return strings.Join(quoted, ", ")
}

// wrapComment folds a description onto continuation lines.
//
// Descriptions are the reasoning behind each event and are long on purpose. One
// line each would put them past any reasonable width, and gofmt does not wrap
// comments.
func wrapComment(text, prefix string) string {
	const width = 72

	var lines []string
	line := ""
	for _, word := range strings.Fields(text) {
		if line == "" {
			line = word
			continue
		}
		if len(line)+1+len(word) > width {
			lines = append(lines, line)
			line = word
			continue
		}
		line += " " + word
	}
	if line != "" {
		lines = append(lines, line)
	}
	return strings.Join(lines, "\n"+prefix)
}
