// What the generated registry has to be true of.
//
// The generator's output is what the outbox validates against and what a
// consumer decodes with, so the properties asserted here are the ones a
// producer and a consumer are each relying on without being able to see the
// other.
package main

import (
	"path/filepath"
	"strings"
	"testing"
)

func loadForGeneration(t *testing.T) *Catalogue {
	t.Helper()

	catalogue, err := Load(filepath.Join(repoRoot, "packages/contracts/events"))
	if err != nil {
		t.Fatalf("loading the event contracts: %v", err)
	}
	return catalogue
}

func TestGeneratedGoIsStableBetweenRuns(t *testing.T) {
	catalogue := loadForGeneration(t)

	// Map iteration in Go is deliberately random, so a generator that walks one
	// without sorting produces a different file every run. That does not fail
	// the generator; it fails the drift gate, days later, on somebody else's
	// unrelated change.
	first := generateGo(catalogue)
	for range 5 {
		if generateGo(catalogue) != first {
			t.Fatal("generateGo produced different output for the same input")
		}
	}
}

func TestGeneratedTypeScriptIsStableBetweenRuns(t *testing.T) {
	catalogue := loadForGeneration(t)

	first := generateTypeScript(catalogue)
	for range 5 {
		if generateTypeScript(catalogue) != first {
			t.Fatal("generateTypeScript produced different output for the same input")
		}
	}
}

func TestEveryEventReachesBothLanguages(t *testing.T) {
	catalogue := loadForGeneration(t)

	goSource := generateGo(catalogue)
	tsSource := generateTypeScript(catalogue)

	for _, event := range catalogue.Sorted() {
		// The event type as a string literal, which is what a producer publishes
		// and a consumer subscribes on. A type present in one language and not
		// the other is a fact one half of the system cannot express.
		quoted := `"` + event.Type + `"`
		if !strings.Contains(goSource, quoted) {
			t.Errorf("%s is missing from the generated Go", event.Type)
		}
		if !strings.Contains(tsSource, quoted) {
			t.Errorf("%s is missing from the generated TypeScript", event.Type)
		}
	}
}

func TestTheRegistryCarriesWhatValidationNeeds(t *testing.T) {
	catalogue := loadForGeneration(t)
	goSource := generateGo(catalogue)

	// The outbox refuses an unknown event type and a payload missing a required
	// field. Both answers come from the generated registry, so a registry that
	// dropped either would leave publication validating nothing while appearing
	// to validate.
	for _, event := range catalogue.Sorted() {
		for _, required := range event.Payload.Required {
			if !strings.Contains(goSource, `"`+required+`"`) {
				t.Errorf("%s requires %q, which is absent from the generated registry",
					event.Type, required)
			}
		}
	}
}

func TestGeneratedFilesSayTheyAreGenerated(t *testing.T) {
	catalogue := loadForGeneration(t)

	// The architecture test that forbids hand-written SQL skips generated files
	// by looking for this line, and an engineer opening the file needs to know
	// not to edit it. Both fail silently if the header is dropped.
	for name, source := range map[string]string{
		"Go":         generateGo(catalogue),
		"TypeScript": generateTypeScript(catalogue),
	} {
		if !strings.Contains(source, "Code generated by") {
			t.Errorf("the generated %s carries no generated-code header", name)
		}
	}
}

func TestGoIdentifiersAreDerivedFromEventTypes(t *testing.T) {
	cases := map[string]string{
		"identity.user_registered.v1":       "IdentityUserRegisteredV1",
		"evaluation.insufficient_evidence.v1": "EvaluationInsufficientEvidenceV1",
		"tenant.membership_changed.v1":      "TenantMembershipChangedV1",
	}

	for eventType, want := range cases {
		if got := goIdentifier(eventType); got != want {
			t.Errorf("goIdentifier(%q) = %q, want %q", eventType, got, want)
		}
	}
}
