// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package tenantadmindb

import (
	"context"
	"time"
)

const completeAccessReview = `-- name: CompleteAccessReview :execrows
UPDATE tenancy.access_reviews
SET status = 'completed', completed_at = now(), completed_by = $1::uuid
WHERE tenant_id = $2::uuid
  AND id = $3::uuid
  AND status = 'open'
`

type CompleteAccessReviewParams struct {
	CompletedBy string
	TenantID    string
	ID          string
}

// Guarded on still being open for the same reason the item decision is.
func (q *Queries) CompleteAccessReview(ctx context.Context, arg CompleteAccessReviewParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeAccessReview, arg.CompletedBy, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const configurationAtVersion = `-- name: ConfigurationAtVersion :one
SELECT version, settings, changed_by::text AS changed_by, changed_at
FROM tenancy.tenant_configuration
WHERE tenant_id = $1::uuid
  AND version = $2::integer
`

type ConfigurationAtVersionParams struct {
	TenantID string
	Version  int32
}

type ConfigurationAtVersionRow struct {
	Version   int32
	Settings  []byte
	ChangedBy string
	ChangedAt time.Time
}

// The pin re-read: what a campaign created at this version was created
// under. Append-only storage is what makes this answer stable.
func (q *Queries) ConfigurationAtVersion(ctx context.Context, arg ConfigurationAtVersionParams) (ConfigurationAtVersionRow, error) {
	row := q.db.QueryRow(ctx, configurationAtVersion, arg.TenantID, arg.Version)
	var i ConfigurationAtVersionRow
	err := row.Scan(
		&i.Version,
		&i.Settings,
		&i.ChangedBy,
		&i.ChangedAt,
	)
	return i, err
}

const configurationHistory = `-- name: ConfigurationHistory :many
SELECT version, settings, changed_by::text AS changed_by, changed_at
FROM tenancy.tenant_configuration
WHERE tenant_id = $1::uuid
ORDER BY version DESC
`

type ConfigurationHistoryRow struct {
	Version   int32
	Settings  []byte
	ChangedBy string
	ChangedAt time.Time
}

// Every version, newest first, with who saved it. The document is returned
// too: "what was it before" is answered by reading the row, not by trusting
// a description of the change.
func (q *Queries) ConfigurationHistory(ctx context.Context, tenantID string) ([]ConfigurationHistoryRow, error) {
	rows, err := q.db.Query(ctx, configurationHistory, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigurationHistoryRow{}
	for rows.Next() {
		var i ConfigurationHistoryRow
		if err := rows.Scan(
			&i.Version,
			&i.Settings,
			&i.ChangedBy,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingAccessReviewItems = `-- name: CountPendingAccessReviewItems :one
SELECT count(*) AS pending
FROM tenancy.access_review_items
WHERE tenant_id = $1::uuid
  AND review_id = $2::uuid
  AND decision = 'pending'
`

type CountPendingAccessReviewItemsParams struct {
	TenantID string
	ReviewID string
}

func (q *Queries) CountPendingAccessReviewItems(ctx context.Context, arg CountPendingAccessReviewItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingAccessReviewItems, arg.TenantID, arg.ReviewID)
	var pending int64
	err := row.Scan(&pending)
	return pending, err
}

const currentConfiguration = `-- name: CurrentConfiguration :one


SELECT version, settings, changed_by::text AS changed_by, changed_at
FROM tenancy.tenant_configuration
WHERE tenant_id = $1::uuid
ORDER BY version DESC
LIMIT 1
`

type CurrentConfigurationRow struct {
	Version   int32
	Settings  []byte
	ChangedBy string
	ChangedAt time.Time
}

// Tenant administration's queries. sqlc generates the Go beside this file;
// ADR-0010 records why no SQL lives in Go source.
//
// Tables this module owns: tenancy.tenant_configuration,
// tenancy.access_reviews, tenancy.access_review_items. It reads audit.events,
// which no context owns, and writes its own rows there. It reads nothing else
// belonging to another module: the roster of members arrives through a port,
// because who belongs to a workspace is identity's answer and not this
// module's query.
// ───────────────────────────────────────────────── settings (TEN-01)
// The highest version is the current one. There is no "is_current" flag to
// get out of step with the rows.
func (q *Queries) CurrentConfiguration(ctx context.Context, tenantID string) (CurrentConfigurationRow, error) {
	row := q.db.QueryRow(ctx, currentConfiguration, tenantID)
	var i CurrentConfigurationRow
	err := row.Scan(
		&i.Version,
		&i.Settings,
		&i.ChangedBy,
		&i.ChangedAt,
	)
	return i, err
}

const decideAccessReviewItem = `-- name: DecideAccessReviewItem :execrows
UPDATE tenancy.access_review_items
SET decision = $1::text,
    decided_at = now(),
    decided_by = $2::uuid,
    note = $3::text
WHERE tenant_id = $4::uuid
  AND id = $5::uuid
  AND decision = 'pending'
`

type DecideAccessReviewItemParams struct {
	Decision  string
	DecidedBy string
	Note      string
	TenantID  string
	ID        string
}

// Guarded on still being pending, so a second reviewer deciding the same
// item loses on rows affected rather than overwriting the first decision.
func (q *Queries) DecideAccessReviewItem(ctx context.Context, arg DecideAccessReviewItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideAccessReviewItem,
		arg.Decision,
		arg.DecidedBy,
		arg.Note,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findOpenAccessReview = `-- name: FindOpenAccessReview :one
SELECT id::text AS id, status, opened_at, coalesce(opened_by::text, '')::text AS opened_by,
       due_at, dormant_after_days, completed_at,
       coalesce(completed_by::text, '')::text AS completed_by
FROM tenancy.access_reviews
WHERE tenant_id = $1::uuid AND status = 'open'
`

type FindOpenAccessReviewRow struct {
	ID               string
	Status           string
	OpenedAt         time.Time
	OpenedBy         string
	DueAt            time.Time
	DormantAfterDays int32
	CompletedAt      *time.Time
	CompletedBy      string
}

func (q *Queries) FindOpenAccessReview(ctx context.Context, tenantID string) (FindOpenAccessReviewRow, error) {
	row := q.db.QueryRow(ctx, findOpenAccessReview, tenantID)
	var i FindOpenAccessReviewRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.OpenedAt,
		&i.OpenedBy,
		&i.DueAt,
		&i.DormantAfterDays,
		&i.CompletedAt,
		&i.CompletedBy,
	)
	return i, err
}

const getAccessReview = `-- name: GetAccessReview :one
SELECT id::text AS id, status, opened_at, coalesce(opened_by::text, '')::text AS opened_by,
       due_at, dormant_after_days, completed_at,
       coalesce(completed_by::text, '')::text AS completed_by
FROM tenancy.access_reviews
WHERE tenant_id = $1::uuid AND id = $2::uuid
`

type GetAccessReviewParams struct {
	TenantID string
	ID       string
}

type GetAccessReviewRow struct {
	ID               string
	Status           string
	OpenedAt         time.Time
	OpenedBy         string
	DueAt            time.Time
	DormantAfterDays int32
	CompletedAt      *time.Time
	CompletedBy      string
}

func (q *Queries) GetAccessReview(ctx context.Context, arg GetAccessReviewParams) (GetAccessReviewRow, error) {
	row := q.db.QueryRow(ctx, getAccessReview, arg.TenantID, arg.ID)
	var i GetAccessReviewRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.OpenedAt,
		&i.OpenedBy,
		&i.DueAt,
		&i.DormantAfterDays,
		&i.CompletedAt,
		&i.CompletedBy,
	)
	return i, err
}

const getAccessReviewItem = `-- name: GetAccessReviewItem :one
SELECT id::text AS id, review_id::text AS review_id, membership_id::text AS membership_id,
       user_id::text AS user_id, role, last_active_at, dormant, decision,
       decided_at, coalesce(decided_by::text, '')::text AS decided_by, note
FROM tenancy.access_review_items
WHERE tenant_id = $1::uuid AND id = $2::uuid
`

type GetAccessReviewItemParams struct {
	TenantID string
	ID       string
}

type GetAccessReviewItemRow struct {
	ID           string
	ReviewID     string
	MembershipID string
	UserID       string
	Role         string
	LastActiveAt *time.Time
	Dormant      bool
	Decision     string
	DecidedAt    *time.Time
	DecidedBy    string
	Note         string
}

func (q *Queries) GetAccessReviewItem(ctx context.Context, arg GetAccessReviewItemParams) (GetAccessReviewItemRow, error) {
	row := q.db.QueryRow(ctx, getAccessReviewItem, arg.TenantID, arg.ID)
	var i GetAccessReviewItemRow
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.MembershipID,
		&i.UserID,
		&i.Role,
		&i.LastActiveAt,
		&i.Dormant,
		&i.Decision,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.Note,
	)
	return i, err
}

const insertAccessReview = `-- name: InsertAccessReview :exec

INSERT INTO tenancy.access_reviews
    (id, tenant_id, opened_by, due_at, dormant_after_days)
VALUES ($1::uuid, $2::uuid, $3::uuid,
        $4::timestamptz, $5::integer)
`

type InsertAccessReviewParams struct {
	ID               string
	TenantID         string
	OpenedBy         string
	DueAt            time.Time
	DormantAfterDays int32
}

// ───────────────────────────────────────────── access review (TEN-03)
func (q *Queries) InsertAccessReview(ctx context.Context, arg InsertAccessReviewParams) error {
	_, err := q.db.Exec(ctx, insertAccessReview,
		arg.ID,
		arg.TenantID,
		arg.OpenedBy,
		arg.DueAt,
		arg.DormantAfterDays,
	)
	return err
}

const insertAccessReviewItem = `-- name: InsertAccessReviewItem :exec
INSERT INTO tenancy.access_review_items
    (id, tenant_id, review_id, membership_id, user_id, role, last_active_at, dormant)
VALUES ($1::uuid, $2::uuid, $3::uuid,
        $4::uuid, $5::uuid, $6::text,
        $7::timestamptz, $8::boolean)
`

type InsertAccessReviewItemParams struct {
	ID           string
	TenantID     string
	ReviewID     string
	MembershipID string
	UserID       string
	Role         string
	LastActiveAt *time.Time
	Dormant      bool
}

func (q *Queries) InsertAccessReviewItem(ctx context.Context, arg InsertAccessReviewItemParams) error {
	_, err := q.db.Exec(ctx, insertAccessReviewItem,
		arg.ID,
		arg.TenantID,
		arg.ReviewID,
		arg.MembershipID,
		arg.UserID,
		arg.Role,
		arg.LastActiveAt,
		arg.Dormant,
	)
	return err
}

const insertConfiguration = `-- name: InsertConfiguration :exec
INSERT INTO tenancy.tenant_configuration (tenant_id, version, settings, changed_by)
VALUES ($1::uuid, $2::integer,
        $3::jsonb, $4::uuid)
`

type InsertConfigurationParams struct {
	TenantID  string
	Version   int32
	Settings  []byte
	ChangedBy string
}

// A save is an insert. Two administrators saving the same version collide on
// the primary key, so the second is refused rather than quietly winning.
func (q *Queries) InsertConfiguration(ctx context.Context, arg InsertConfigurationParams) error {
	_, err := q.db.Exec(ctx, insertConfiguration,
		arg.TenantID,
		arg.Version,
		arg.Settings,
		arg.ChangedBy,
	)
	return err
}

const insertTenantAuditEvent = `-- name: InsertTenantAuditEvent :exec

INSERT INTO audit.events
    (id, tenant_id, actor_id, actor_type, action, subject_type, subject_id, outcome, detail)
VALUES ($1::uuid, $2::uuid, $3::uuid, 'user',
        $4::text, $5::text, $6::text,
        'allowed', $7::jsonb)
`

type InsertTenantAuditEventParams struct {
	ID          string
	TenantID    string
	ActorID     string
	Action      string
	SubjectType string
	SubjectID   string
	Detail      []byte
}

// ─────────────────────────────────────────────────────────── audit
// This module's audit append. Settings versions and review completions are
// the decisions worth reviewing later.
func (q *Queries) InsertTenantAuditEvent(ctx context.Context, arg InsertTenantAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertTenantAuditEvent,
		arg.ID,
		arg.TenantID,
		arg.ActorID,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.Detail,
	)
	return err
}

const lastActivityByActor = `-- name: LastActivityByActor :many
SELECT actor_id::text AS actor_id, max(occurred_at)::timestamptz AS last_active_at
FROM audit.events
WHERE tenant_id = $1::uuid AND actor_id IS NOT NULL
GROUP BY actor_id
`

type LastActivityByActorRow struct {
	ActorID      string
	LastActiveAt time.Time
}

// When each person was last seen acting in this workspace.
//
// Read from the audit trail because that is where a workspace's record of
// what people did lives, and it is the only source that is tenant-scoped:
// a session belongs to a person across every workspace they belong to, so it
// cannot answer "dormant here". The consequence is stated where it is used:
// somebody who only ever read pages has no audited act and reads as dormant,
// which prompts a confirmation rather than hiding them.
func (q *Queries) LastActivityByActor(ctx context.Context, tenantID string) ([]LastActivityByActorRow, error) {
	rows, err := q.db.Query(ctx, lastActivityByActor, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LastActivityByActorRow{}
	for rows.Next() {
		var i LastActivityByActorRow
		if err := rows.Scan(&i.ActorID, &i.LastActiveAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestCompletedAccessReview = `-- name: LatestCompletedAccessReview :one
SELECT id::text AS id, status, opened_at, coalesce(opened_by::text, '')::text AS opened_by,
       due_at, dormant_after_days, completed_at,
       coalesce(completed_by::text, '')::text AS completed_by
FROM tenancy.access_reviews
WHERE tenant_id = $1::uuid AND status = 'completed'
ORDER BY completed_at DESC
LIMIT 1
`

type LatestCompletedAccessReviewRow struct {
	ID               string
	Status           string
	OpenedAt         time.Time
	OpenedBy         string
	DueAt            time.Time
	DormantAfterDays int32
	CompletedAt      *time.Time
	CompletedBy      string
}

// What "due" is measured from. A workspace that has never completed one is
// due immediately, which is the absence of a row rather than a special case.
func (q *Queries) LatestCompletedAccessReview(ctx context.Context, tenantID string) (LatestCompletedAccessReviewRow, error) {
	row := q.db.QueryRow(ctx, latestCompletedAccessReview, tenantID)
	var i LatestCompletedAccessReviewRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.OpenedAt,
		&i.OpenedBy,
		&i.DueAt,
		&i.DormantAfterDays,
		&i.CompletedAt,
		&i.CompletedBy,
	)
	return i, err
}

const listAccessReviewItems = `-- name: ListAccessReviewItems :many
SELECT id::text AS id, review_id::text AS review_id, membership_id::text AS membership_id,
       user_id::text AS user_id, role, last_active_at, dormant, decision,
       decided_at, coalesce(decided_by::text, '')::text AS decided_by, note
FROM tenancy.access_review_items
WHERE tenant_id = $1::uuid AND review_id = $2::uuid
ORDER BY dormant DESC, last_active_at ASC NULLS FIRST, id
`

type ListAccessReviewItemsParams struct {
	TenantID string
	ReviewID string
}

type ListAccessReviewItemsRow struct {
	ID           string
	ReviewID     string
	MembershipID string
	UserID       string
	Role         string
	LastActiveAt *time.Time
	Dormant      bool
	Decision     string
	DecidedAt    *time.Time
	DecidedBy    string
	Note         string
}

// Dormant first, because the prompt exists to put the access nobody has used
// in front of the person who can remove it.
func (q *Queries) ListAccessReviewItems(ctx context.Context, arg ListAccessReviewItemsParams) ([]ListAccessReviewItemsRow, error) {
	rows, err := q.db.Query(ctx, listAccessReviewItems, arg.TenantID, arg.ReviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessReviewItemsRow{}
	for rows.Next() {
		var i ListAccessReviewItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.MembershipID,
			&i.UserID,
			&i.Role,
			&i.LastActiveAt,
			&i.Dormant,
			&i.Decision,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
