-- 0001: schemas, connection roles, tenancy, and the row-level security that
-- every tenant-owned table inherits from here on.
--
-- ADR-0002 decides the shape. Two rules are enforced here rather than
-- documented, because a rule that depends on the next engineer remembering it
-- is not a rule:
--
--   1. A tenant-owned table is created with its policy in the same migration
--      that creates the table. Adding the policy later ships a window in which
--      the table leaks.
--   2. Policies are FORCEd, because PostgreSQL exempts a table's owner from its
--      own policies otherwise, and the migrator owns every table.

-- ─────────────────────────────────────────────────────── extensions
-- citext gives case-insensitive email comparison without a functional index on
-- every lookup. pgcrypto provides gen_random_uuid for rows whose identifier is
-- generated by the database rather than by the application.
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ─────────────────────────────────────────────────────── module schemas
-- Schema is an ownership boundary, not a tenant boundary. A module reads and
-- writes only its own schema; PLT-04 enforces that in the import graph.
CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS tenancy;
CREATE SCHEMA IF NOT EXISTS candidate;
CREATE SCHEMA IF NOT EXISTS content;
CREATE SCHEMA IF NOT EXISTS interview;
CREATE SCHEMA IF NOT EXISTS media;
CREATE SCHEMA IF NOT EXISTS evaluation;
CREATE SCHEMA IF NOT EXISTS recruiting;
CREATE SCHEMA IF NOT EXISTS progression;
CREATE SCHEMA IF NOT EXISTS billing;
CREATE SCHEMA IF NOT EXISTS integration;
CREATE SCHEMA IF NOT EXISTS audit;

-- ─────────────────────────────────────────────────────── connection roles
-- The application role can neither bypass row-level security nor own the
-- tables it reads, so a mistake in application code cannot turn the policy off.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'prepeet_app') THEN
        CREATE ROLE prepeet_app LOGIN NOSUPERUSER NOBYPASSRLS
            NOCREATEDB NOCREATEROLE NOINHERIT PASSWORD :'app_password';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'prepeet_readonly') THEN
        CREATE ROLE prepeet_readonly NOLOGIN NOSUPERUSER NOBYPASSRLS
            NOCREATEDB NOCREATEROLE NOINHERIT;
    END IF;
END
$$;

GRANT USAGE ON SCHEMA identity, tenancy, candidate, content, interview, media,
                       evaluation, recruiting, progression, billing, integration, audit
    TO prepeet_app, prepeet_readonly;

-- ─────────────────────────────────────────────────────── tenancy
CREATE TABLE tenancy.tenants (
    id          uuid        PRIMARY KEY,
    name        text        NOT NULL,
    slug        text        NOT NULL UNIQUE,
    -- Region is a property of the tenant rather than of the deployment, so
    -- residency is decidable per tenant from the first row. See ADR-0001.
    region      text        NOT NULL,
    status      text        NOT NULL DEFAULT 'active'
                            CHECK (status IN ('active', 'suspended', 'closed')),
    -- Optimistic concurrency on every mutable aggregate, per the data
    -- architecture conventions.
    version     integer     NOT NULL DEFAULT 1,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE tenancy.tenants IS
    'One employer workspace. Carries no tenant_id because it is the tenant; '
    'row-level security scopes it by id instead.';

-- The tenants table is the one place tenant_id would be circular, so the policy
-- is written against the primary key.
--
-- NULLIF is not decoration. A setting that was never set reads as NULL, but one
-- set with SET LOCAL reverts to the empty string when the transaction ends, and
-- ''::uuid raises rather than matching nothing. Without NULLIF the first
-- unscoped query after any tenant-scoped transaction on a pooled connection
-- fails with a cast error instead of quietly returning no rows.
ALTER TABLE tenancy.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenancy.tenants FORCE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON tenancy.tenants
    USING (id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    WITH CHECK (id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

CREATE TABLE tenancy.tenant_settings (
    id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   uuid        NOT NULL REFERENCES tenancy.tenants (id) ON DELETE CASCADE,
    key         text        NOT NULL,
    value       text        NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, key)
);

-- tenant_id leads the index because every query is tenant scoped and the
-- planner needs the leading column to match, per ADR-0002's consequences.
CREATE INDEX tenant_settings_tenant_key_idx ON tenancy.tenant_settings (tenant_id, key);

ALTER TABLE tenancy.tenant_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenancy.tenant_settings FORCE ROW LEVEL SECURITY;

-- With no tenant set the expression is NULL, and a comparison with NULL is not
-- true, so an unscoped query returns nothing rather than everything. Forgetting
-- the context fails closed.
CREATE POLICY tenant_isolation ON tenancy.tenant_settings
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

-- ─────────────────────────────────────────────────────── identity
-- A user is a person, not a tenant member. The same person can practise alone
-- and screen for several employers, so identity is deliberately global and
-- carries no tenant_id.
CREATE TABLE identity.users (
    id             uuid        PRIMARY KEY,
    email          citext,
    email_verified boolean     NOT NULL DEFAULT false,
    status         text        NOT NULL DEFAULT 'active'
                               CHECK (status IN ('active', 'suspended', 'deleted')),
    version        integer     NOT NULL DEFAULT 1,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE identity.users IS
    'A person. Global rather than tenant scoped: the same person may practise '
    'privately and screen for several employers, and their practice history is '
    'never reachable from any employer authority.';

CREATE UNIQUE INDEX users_email_idx ON identity.users (email) WHERE email IS NOT NULL;

-- ─────────────────────────────────────────────────────── membership
-- Membership is what connects a global person to one tenant, and it is where
-- tenant scoping starts for identity.
CREATE TABLE tenancy.memberships (
    id          uuid        PRIMARY KEY,
    tenant_id   uuid        NOT NULL REFERENCES tenancy.tenants (id) ON DELETE CASCADE,
    user_id     uuid        NOT NULL REFERENCES identity.users (id) ON DELETE CASCADE,
    status      text        NOT NULL DEFAULT 'active'
                            CHECK (status IN ('invited', 'active', 'revoked')),
    version     integer     NOT NULL DEFAULT 1,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, user_id)
);

CREATE INDEX memberships_tenant_user_idx ON tenancy.memberships (tenant_id, user_id);
CREATE INDEX memberships_user_idx ON tenancy.memberships (user_id);

ALTER TABLE tenancy.memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenancy.memberships FORCE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON tenancy.memberships
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

-- ─────────────────────────────────────────────────────── grants
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA tenancy, identity TO prepeet_app;
GRANT SELECT ON ALL TABLES IN SCHEMA tenancy, identity TO prepeet_readonly;

-- Tables added by later migrations inherit these grants, so a new table is
-- usable without a grant being forgotten.
ALTER DEFAULT PRIVILEGES IN SCHEMA identity, tenancy, candidate, content, interview, media,
                                  evaluation, recruiting, progression, billing, integration, audit
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO prepeet_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA identity, tenancy, candidate, content, interview, media,
                                  evaluation, recruiting, progression, billing, integration, audit
    GRANT SELECT ON TABLES TO prepeet_readonly;
